Карпихин Глеб, Web-22
frontend-park-mail-ru/homework_2024_2 pull request #1
Opened 2024-08-26 18:39 UTC by JOJOSoderqvist

2024-08-26 19:02 UTC, JOJOSoderqvist commented
Web-21, если быть точнее

2024-08-30 19:06 UTC, Nikita-hub000 commented
Привет! Меня зовут Никита. Поздравляю с переходом на 2 семестр и желаю успехов в учебе:)
Я буду твоим проверяющим ДЗ№0. Если возникнут вопросы, не стесняйся обращаться)

1. Некорректное название ПРа. Оно должно быть «Фамилия Имя студента»
2. Отсутствует пустая строка в конце файлов .js

2024-08-30 19:35 UTC, Nikita-hub000 commented on source/anagram.js
> +'use strict';
Круто, что добавил use strict! Можешь вкратце объяснить: что это и для чего это?)

2024-08-30 19:35 UTC, Nikita-hub000 commented on source/anagram.js
> +function anagram(input) {
Попробуй использовать всегда ( ну или почти всегда ) стрелочные функции. Очень редко когда это может сыграть в минус, они лучше читаются в коде:)
Можешь [здесь](https://learn.javascript.ru/arrow-functions-basics) глянуть про них 

Также давай лучше переименуем параметр функции input в то что будет чуть лучше раскрывать суть программы:) Например `words`

2024-08-30 19:35 UTC, Nikita-hub000 commented on source/anagram.js
> +    input.forEach((value) => {
Молодец, что используешь встроенные методы в js, а не обычные for циклы:)
Они делают код более читаемым

`value`  здесь наверное не самое лучшее имя для переменной, может лучше `word` ?:)

2024-08-30 19:35 UTC, Nikita-hub000 commented on source/anagram.js
> +        const letters = value.split('').sort();
А что если в словах будут буквы не только английского алфавита? 

P.S. https://learn.javascript.ru/string#sravnenie-strok :)

2024-08-30 19:35 UTC, Nikita-hub000 commented on source/anagram.js
> +        if (!(letters in arrayMap)) {
Тут letters является массивом и в объекте arrayMap будет работать не совсем как ожидается)
Попробуй сделать `console.log(arrayMap)` как есть сейчас. Затем преобразуй letters в строку и тоже выведи. Как думаешь почему такой результат?)

2024-08-30 19:35 UTC, Nikita-hub000 commented on source/anagram.js
> +    return Object.values(arrayMap).filter(value => value.length > 1).map(value => value.sort()).sort();
Здесь тоже самое. А что если в словах будут буквы не только английского алфавита?


P.S. https://learn.javascript.ru/string#sravnenie-strok :)

2024-08-30 19:35 UTC, Nikita-hub000 commented on source/anagram.js
> +}
Пустая строка нужна в конце файла)
Вообще это можно настроить в eslint и не мучаться проставляя руками
https://eslint.org/docs/latest/rules/eol-last

2024-08-30 19:35 UTC, Nikita-hub000 commented on tests/anagram.js
> +	});
Пустая строка нужна в конце файла)
Вообще это можно настроить в eslint и не мучаться проставляя руками
https://eslint.org/docs/latest/rules/eol-last

2024-08-30 19:35 UTC, Nikita-hub000 commented on source/anagram.js
> +
Не обработан случай когда будет подаваться не массив, а что то другое
Также не обработан случай когда подается массив с не строками ( пример: `[1,2,3]` ) и со смешанными типами ( пример: `[1,true, [], 'error']`
На такие случаи нужно выбрасывать ошибку

2024-08-30 19:35 UTC, Nikita-hub000 commented on tests/anagram.js
> +
Нужно будет добавить тесты на разные алфавиты, если подается не массив и массив с не строками и смешанными типами:)

2024-09-02 11:53 UTC, JOJOSoderqvist commented on source/anagram.js
> +'use strict';
Это директива, которая необходима для включения строгого режима, что помогает избежать некоторых ошибок в коде, например
-  Нельзя определять функцию с одинаковыми параметрами дважды
- ```x = 5``` не создаст глобальную переменную
А так же многих других паттернов, которые считаются ошибочными либо устаревшими

2024-09-02 12:03 UTC, JOJOSoderqvist commented on source/anagram.js
> +        if (!(letters in arrayMap)) {
В Object массив если выступает как ключ, то переводится в строку, а так как он перед этим сортируется, то проверка in работает корректно

2024-09-02 13:00 UTC, Nikita-hub000 commented
Все гуд. Осталось только пустую строку в конце файлов добавить

2024-09-03 11:12 UTC, JOJOSoderqvist commented
Очень странно, что их нет на гитхабе, так как в ide они присутсвуют, и если попытаться их там убрать, то в git diff появляюься изменения 
![image](https://github.com/user-attachments/assets/949d3769-dcfd-4807-95b6-afa1741792a5)
![image](https://github.com/user-attachments/assets/a7046310-4bc9-4a48-8c36-3169c7c83e68)

2024-09-03 13:56 UTC, Nikita-hub000 reviewed
Да, такая проблема уже попадалась у других студентов. Так очень сложно сказать в таком случае. Т.К. не вижу твоего компа:)
Давай я тебя переведу дальше, т.к. задание по сути выполнено, но уточни этот вопрос у Дмитрия Пешкова еще. ( смотри его в assigners)

2024-09-04 15:36 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-04 15:36 UTC, DPeshkoff commented on source/anagram.js
> +const anagram = (words) => {
А чем такая функция отличается от обычной?

2024-09-04 15:36 UTC, DPeshkoff commented on source/anagram.js
> +        throw new Error('Argument must be an array');
Лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2024-09-04 15:36 UTC, DPeshkoff commented on source/anagram.js
> +    if (words.some(word => typeof word !== 'string' || word === '' || [...word].some(symbol => !isNaN(symbol)))) {
Не пройдем

<img width="233" alt="Снимок экрана 2024-09-04 в 18 32 35" src="https://github.com/user-attachments/assets/9f789f48-56fd-44a1-8855-a092190cb65c">

2024-09-04 15:36 UTC, DPeshkoff commented on source/anagram.js
> +    if (words.some(word => typeof word !== 'string' || word === '' || [...word].some(symbol => !isNaN(symbol)))) {
А чем isNaN отличается от Number.isNaN? Аргументируй, что лучше именно здесь?

2024-09-05 10:57 UTC, JOJOSoderqvist commented on source/anagram.js
> +const anagram = (words) => {
Такая функция имеет 2 основных отличия от ```function declaration```:
1. Время создания функции движком JavaScript: при объявлении функции как ```function declaration```, она им ищется и создается в самом начале, перед выполнением скрипта, тогда как при ```function expression``` создается только когда выполние доходит до ее объявления.
2. Область видимости. При ```function declaration``` область видимости функции ограничена блоком кода, в котором она объявлена, а при ```function expression```, область видимости функции ничем не ограничена.

2024-09-05 12:26 UTC, JOJOSoderqvist commented on source/anagram.js
> +    if (words.some(word => typeof word !== 'string' || word === '' || [...word].some(symbol => !isNaN(symbol)))) {
```isNaN()``` переводит аргумент в число, и если получается, то возвращается ```false```, если не получается (при переводе получился ```NaN```) - то ```true```, а ```Number.isNaN()``` возвращает ```true``` только в том случае, если агрумент - ```NaN```. Поэтому для нашей задачи лучше использовать ```isNaN()``` (например для случая ```[...'ток123'].some(symbol => !isNaN(symbol))``` вернет ```true```, что подходит под логику проверки).

2024-09-08 19:23 UTC, DPeshkoff requested changes

2024-09-08 19:23 UTC, DPeshkoff commented on source/anagram.js
> +const anagram = (words) => {
А что насчет this?

2024-09-08 21:07 UTC, JOJOSoderqvist commented
У стрелочных функций отсутсвует собственный ```this``` в отличие от обычных, поэтому, например, тут:
```js
'use strict';

const User = {
    age: 10,
    commonFunc() {
        console.log(this);
    },
    arrowFunc: () => {
        console.log(this);
    },
    outsideFunc() {
        const insideArrowFunc = () => {
            console.log(this)
        }
        insideArrowFunc()
    }
};

User.commonFunc();
User.arrowFunc();
User.outsideFunc();
```
- В первом случае выведется ```User```, так как в обычной функции ```this``` это ```User```.
- Во втором случае ничего не выведется (```undefined```), так как значение берется из внешнего контекста (```window``` без ```'use stict'```).
- В третьем варианте также выведется ```User``` из-за того, что в данном случае у стрелочной функции контекст - обычная функция, в которой ```this``` выступает ```User-ом```.

2024-09-10 20:54 UTC, DPeshkoff approved these changes

2024-09-10 20:59 UTC, closed without merging