Илья Денисенко
frontend-park-mail-ru/homework_2024_2 pull request #11
Opened 2024-08-31 15:41 UTC by MatiXxD

Вариант: 6
Условие задачи:
Напишите функцию `tree`, которая рисует ASCII-ёлочку высотой N символов из звёздочек

2024-09-01 20:57 UTC, let-robots-reign reviewed
Привет, Илья!
Поздравляю с переходом на 2-й семестр, желаю успехов в постижении фронтенда)
Меня зовут Алексей, я дам фидбек по твоему ДЗ0. Мой контакт в Телеграме: @let_robots_reign. Можешь писать по любым вопросам

Ниже оставил замечания по коду и несколько вопросов по JS

2024-09-01 20:57 UTC, let-robots-reign commented on source/tree.js
> +  if (isNaN(Number(treeHeight))) return null;
Перед началом работы над проектами полезно изучить [рекомендации к стилю кода](https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda). Давай применим их к этим условиям и добавим скобки. К тому же ты можешь упростить эти условия и сделать одно

Также тут проверены не все случаи. В JS есть такое значение `Infinity`, которое является числом. Попробуй запустить свою функцию с этим аргументом и посмотри, что получится
Когда поправишь условие, рекомендую добавить тесты на `Infinity`, `-Infinity` и `NaN`

2024-09-01 20:57 UTC, let-robots-reign commented on source/tree.js
> +  if (treeHeight <= 2) return null;
Давай вынесем 2 в константу с названием, которое отражает смысл этой проверки

И все-таки тут тоже добавим фигурные скобки в условие

2024-09-01 20:57 UTC, let-robots-reign commented on source/tree.js
> +  treeHeight = Math.trunc(Number(treeHeight));
Считается плохой практикой изменять параметры, пришедшие в функцию, из-за этого она перестает быть [чистой](https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D1%81%D1%82%D0%BE%D1%82%D0%B0_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8). Чистые и не чистые функции как понятия существуют в большинстве языков, не только в JS
Предлагаю сделать нашу функцию чистой

2024-09-01 20:57 UTC, let-robots-reign commented on source/tree.js
> +  for (let i = 0; i != treeHeight - 1; ++i) {
`i != treeHeight - 1` - интересное условие, обычно в циклах пишут все же как `i < treeHeight - 1`
Не ошибка, а придирка, конечно, но лучше писать стандартно, чтобы у других разработчиков, которые читали код, не возникли сомнения, не закладывал ли ты какую-то иную логику
Заодно поясни, пожалуйста, разницу между `!=` и `!==`

2024-09-01 20:57 UTC, let-robots-reign commented on source/tree.js
> +    let starts = "*".repeat(2 * i + 1);
Кажется, опечатка) Должно быть `stars`

2024-09-01 20:57 UTC, let-robots-reign commented on source/tree.js
> +    let spaces = " ".repeat(treeHeight - i - 2);
Почему решил использовать let для этих двух переменных?

2024-09-01 20:57 UTC, let-robots-reign commented on source/tree.js
> +  treeString += " ".repeat(treeHeight - 2) + "|" + " ".repeat(treeHeight - 2) + "\n";
Предлагаю тут использовать [шаблонные строки](https://doka.guide/js/template-strings/)

2024-09-01 20:57 UTC, let-robots-reign commented on tests/tree.js
С тестами все хорошо, только добавь еще один `QUnit.test()` для значений, которые я упомянул выше

2024-09-02 12:16 UTC, MatiXxD commented on source/tree.js
> +"use strict";
`"use strict"` включает строгий режим. В данном режиме ошибки не будут игнорироваться, что позволяет легче их находить. К примеру без использования `"use strict"` можно использовать переменные без объявления: `var = 2;`.

2024-09-02 12:16 UTC, MatiXxD commented on source/tree.js
> +let tree = treeHeight => {
Различие между `let` и `const` заключается в том что если переменная объявлена с помощью `const`, то её значение не может быть изменено. Оператор `var` является устаревшим аналогом `let`. Тут лучше будет использовать `const` поскольку данная переменная будет содержать только функцию `tree()` и меняться не будет.

Другие варианты как объявить функцию:

1. `function tree(...) { ... }`
2. `let tree = function(...) { ... }`

2024-09-02 12:17 UTC, MatiXxD commented on source/tree.js
> +  for (let i = 0; i != treeHeight - 1; ++i) {
У меня просто привычка в таких циклах использовать `!=`. `!==` сначала сравнивает тип переменных а потом их значения, `!=` приводит к одному типу и затем сравнивает.

2024-09-02 12:17 UTC, MatiXxD commented on source/tree.js
> +    let spaces = " ".repeat(treeHeight - i - 2);
Для `treeString` использую `let`, поскольку буду дописывать в строку => значение будет меняться. Для локальных переменных цикла лучше будет использовать `const`, поскольку их значения меняться не будут.

2024-09-02 12:17 UTC, MatiXxD commented
Привет, спасибо за проверку, правки внёс.

2024-09-02 19:38 UTC, let-robots-reign reviewed
Правки увидел, еще несколько мелочей и можно ставить аппрув!
И еще общий момент: добавь, пожалуйста, пустые строки в конце js-файлов. Это еще одно "правило хорошего тона", вот [тут](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file) есть несколько причин, почему разработчики условились так делать

2024-09-02 19:38 UTC, let-robots-reign commented on source/tree.js
> +  const startsRowsCount = Math.trunc(Number(treeHeight)) - 1;
Думаю, тут тоже опечатка) `starsRowsCount`

2024-09-02 19:38 UTC, let-robots-reign commented on source/tree.js
> +  for (let i = 0; i != startsRowsCount ; ++i) {
Мелочь, но давай уберем пробел тут: `i != startsRowsCount ; ++i`

2024-09-02 19:38 UTC, let-robots-reign commented on source/tree.js
> +  ) {
Да, я тут намекал на `isFinite`, отлично)
Но теперь `typeof treeHeight === "object"` выглядит избыточно, достаточно проверить только `treeHeight === null`. Или даже проще

2024-09-02 20:39 UTC, MatiXxD commented on source/tree.js
> +  ) {
Мне кажется тут вообще можно не проверять `treeHeight === null`, т.к. в этом случае у нас не пройдет условие на минимальную высоту.

2024-09-03 08:45 UTC, let-robots-reign commented on source/tree.js
> +  ) {
По сути да, ты прав, так как сработает приведение типов в `startsRowsCount + 1` (null + 1 = 1)

Но иногда лучше все же условия типа `!treeHeight` писать явно, так как это легче считывается другими разработчиками. В таком случае команде не нужно будет вчитываться в какое-то сложное условие и перепроверять, что где-то внутри сработает приведение типов и все будет ок

2024-09-03 08:48 UTC, let-robots-reign reviewed
Привет, есть еще одна маленькая правка: добавь, пожалуйста, JSDoc к своей функции)

2024-09-03 10:07 UTC, MatiXxD commented
Привет, JSDoc для `tree` добавил.

2024-09-03 10:24 UTC, let-robots-reign commented
Спасибо! 2 момента по JSDoc:
1) Имя параметра должно соответствовать тому, что написано в аргументах функции (то есть `treeHeight`)
2) Раз уж ты добавил `@example`, обрати внимание, что вывод не полный - забыл последнюю строку с "|" у дерева

2024-09-03 11:22 UTC, let-robots-reign commented
От меня аппрув, хорошая работа!

2024-09-06 20:09 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, совсем чуть-чуть накинул)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-06 20:09 UTC, DPeshkoff commented on source/tree.js
> +    !isFinite(treeHeight) ||
В чем отличие isFinite от Number.isFinite и почему используешь именно isFinite?

2024-09-06 20:09 UTC, DPeshkoff commented on source/tree.js
> +  let treeString = "";
Вообще чаще используют одиночные кавычки - давай везде на них переделаем

2024-09-07 18:30 UTC, MatiXxD commented on source/tree.js
> +    !isFinite(treeHeight) ||
Различие в том, что в случае `Number.isFinite` не будет происходить преобразования типа (будет проверка на то, что аргумент является числом), к примеру такой случай `tree("4")` работать не будут, т.к. строку `"4"` не будет преобразована к числу. Поэтому в данной проверке использую `isFinite`.

2024-09-07 18:30 UTC, MatiXxD commented
Привет, спасибо за проверку, все правки внес.

2024-09-10 21:06 UTC, DPeshkoff approved these changes

2024-09-10 21:06 UTC, closed without merging