Шишков Иван
frontend-park-mail-ru/homework_2024_2 pull request #12
Opened 2024-08-31 16:38 UTC by damedelion

Напишите функцию `rle`, которая реализует RLE сжатие

2024-09-01 16:13 UTC, mafin1799 reviewed
Привет)
Поздравляю с переходом на 2 семестр и началом лучшего курса по Фронтенд-разработке
Меня зовут Никита, я буду проверять твое ДЗ №0


Общее автоформатирование можно настроить с помощью линтеров, чтобы не забывать ; и прочие прелести. https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

Если сделаешь это в рамках этой задачки, то не надо пушить в репу конфиги и тд

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +    if ( str == undefined || typeof(str) != "string") {
Как работает оператор typeof? Какие значения он может возвращать?
Почему здесь используется строгое равенство !== вместо !=? В чем разница?
Почему проверка типа str важна в этой функции?

Кстати тут избыточное условие, можно сократить

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +    if (str.length <= 1) {
Тут ок, но можно объединить с условием выше. Но это на твой вкус

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +    let strNew = "";
Нужно более понятное название.
Лучше не использовать такие дефолтные штуки как str, data, state
Нужно в названии накинуть контекста

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +    for (let i = 0; i < str.length; i++) {
Можешь попробовать for..of 
Будет более выразительно и не похоже на флешбеки из c++

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +            strNew += char + ((count === 1) ? "" : count);
Попробуй тут шаблонные строки использовать. Будет более читаемо 100%

Шаблонные строки это `${}`

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +    let strNew = "";
Почему для создания новой строки используется let, а не const?
Почему инициализация строки начинается с пустой строки ('')?

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +    let char = str[0];
Что делает синтаксис str[0]? Почему важно инициализировать char первым символом строки?
В каких случаях доступ к символам строки через индекс может быть неочевиден?

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +            count++;
Что делает оператор ++? Как он отличается от count += 1?

2024-09-01 16:13 UTC, mafin1799 commented on source/rle.js
> +            strNew += char + ((count === 1) ? "" : count);
Как работают шаблонные строки в JavaScript? Почему они удобны?
Что делает оператор += в данном контексте?
Как работает тернарный оператор ? :?

2024-09-03 05:13 UTC, mafin1799 commented
А еще нужно написать jsdoc

2024-09-03 10:12 UTC, damedelion commented on source/rle.js
> +'use strict';
use strict активирует использование новых функций языка, которые не поддерживаются старыми стандартами. без этой директивы некоторые функции могут работать по-другому (по старому стандарту), но зато будет обратная совместимость со старыми скриптами на старом стандарте

2024-09-03 10:49 UTC, damedelion commented on source/rle.js
> +let rle = (str) => {
стрелочная функция позволяет создавать функцию и присваивать ее переменной. однострочная стрелочная функция (например, результат выражения) пишется без return. разница в сравнении с обычной функцией в том, что обычная функция создается перед выполнением кода и может быть использована во всем блоке, а стрелочная функция (как и функциональные выражения Function Expression) создается только когда до нее доходит поток выполнения

let создает переменную, var - устаревший формат объявления переменной, const создает константу. в данном случае можно было использовать const

2024-09-03 11:08 UTC, damedelion commented on source/rle.js
> +    if ( str == undefined || typeof(str) != "string") {
typeof вовращает тип аргумента
строгое равенство проверяет равеноство без приведения типов, в отличие от обычного. вообще-то я здесь использую обычное равенство, т.к. здесь приведения типов не играет большой роли

проверка типа важна, так функция обрабатывает только строку в качестве аргумента.

да, действительно условие избыточно, вторая часть включает в себя первую, так что можно ограничиться только ей

2024-09-03 11:10 UTC, damedelion commented on source/rle.js
> +    if (str.length <= 1) {
как и зачем, если они разные значения возвращают?

2024-09-03 11:18 UTC, damedelion commented on source/rle.js
> +    let strNew = "";
да, согласен, но сразу не придумал как накинуть контекста

2024-09-03 11:20 UTC, damedelion commented on source/rle.js
> +    for (let i = 0; i < str.length; i++) {
да, согласен, просто привык писать на плюсах)

2024-09-03 11:28 UTC, damedelion commented on source/rle.js
> +            strNew += char + ((count === 1) ? "" : count);
шаблонные строки позволяют вставлять переменные и выражения сразу в строку с помощью `${}`, выражение которое находится в фигурных скобках вычисляется и преобразуется в строку в этом месте.

оператор += вычисялет выражение справа от него и прибавляет к переменной слева

тернарный оператор проверяет истинность выражения перед знаком вопроса и, если оно истинно, возвращает значение перед двоеточием, если ложно - значение после двоеточия

2024-09-03 11:31 UTC, damedelion commented on source/rle.js
> +    let strNew = "";
потому что тогда будет создана константная неизменяемая строка

строка инициализируется пустой строкой, так как нужна переменная типа `string`, а иначе будет создана переменная типа `undefined`

2024-09-03 11:36 UTC, damedelion commented on source/rle.js
> +    let char = str[0];
`str[0]` берет первый символ строки. `char` нужно инициализировать первым символо строки, чтобы он не имел тип `undefined`

если индекс находится за пределами строки или если пытаемся по индексу изменить символ константной строки

2024-09-03 11:41 UTC, damedelion commented on source/rle.js
> +            count++;
оператор ++ прибавляет к переменной единицу. отличается от +=1 тем, что имеет 2 формы: префиксную и постфиксную. в префиксной форме ++x единица добавляется перед вычислением остального выражения, в постфиксной форме x++ единица добавится после выполнения остального выражения

2024-09-03 14:04 UTC, damedelion commented
внес правки, добавил jsdocs

2024-09-03 17:06 UTC, mafin1799 commented on source/rle.js
> +let rle = (str) => {
Давай поправим на const

2024-09-03 17:08 UTC, mafin1799 commented on source/rle.js
> +    if (str.length <= 1) {
Ой соре. Ошибся. Прошу прощения))

2024-09-03 17:11 UTC, mafin1799 commented
Остался один вопрос по use strict:))

2024-09-04 11:32 UTC, damedelion commented on source/rle.js
> +'use strict';
при использовании модулей и/или классов

2024-09-04 12:34 UTC, mafin1799 approved these changes
Все ок
Вопросов не имею

2024-09-04 13:14 UTC, damedelion commented
Спасибо за ревью

2024-09-06 20:55 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-06 20:55 UTC, DPeshkoff commented on source/rle.js
> +    if ( typeof(inputString) !== "string") {
Буп и все сломалось

<img width="240" alt="Снимок экрана 2024-09-06 в 20 52 34" src="https://github.com/user-attachments/assets/64201863-b02e-4392-b056-e0a4ec3bfdc7">

Давай подумаем, как починить

2024-09-06 20:55 UTC, DPeshkoff commented on source/rle.js
> +const rle = (inputString) => {
А чем такие функции отличаются от обычных?

2024-09-06 20:55 UTC, DPeshkoff commented on source/rle.js
> +    for (let stringSymbol of inputString) {
Давай подумаем, как можно упростить этот код, заюзав перебирающий метод

2024-09-09 03:49 UTC, damedelion commented on source/rle.js
> +    if ( typeof(inputString) !== "string") {
добавил проверку

2024-09-09 03:51 UTC, damedelion commented on source/rle.js
> +    for (let stringSymbol of inputString) {
переписал с помощью перебирающего метода forEach, но не думаю, что здесь это сильно упростит код

2024-09-09 03:52 UTC, damedelion commented
добавил проверку на принадлежность классу String и переписал цикл с помощью forEach

2024-09-10 21:13 UTC, DPeshkoff approved these changes

2024-09-10 21:13 UTC, closed without merging