Ягмуров Игорь В12
frontend-park-mail-ru/homework_2024_2 pull request #13
Opened 2024-08-31 21:25 UTC by UnicoYal

Напишите функцию minmax, которая находит минимальное и максимальное значения в строке. Возвращает массив, в котором первый элемент — это минимальное число в строке, второй элемент — максимальное

Написано 2 решения, на случай, если нельзя использовать встроенные функции min/max.
Комментарии для предвидения ваших вопросов)

2024-09-01 21:32 UTC, Shureks-den commented
Привет! Поздравляю с поступлением на курс веб-разработки, а в частности на курс фронтенда. Меня зовут Саша и я буду проверять твое дз, по всем вопросам пиши в телегу https://t.me/aklonov  Будет весело)

2024-09-01 21:52 UTC, Shureks-den requested changes

2024-09-01 21:52 UTC, Shureks-den commented on index.html
> +    <script src="tests/max.js"></script>
Давай уберем max.js и тесты для них

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax.js
> +'use strict';
Круто, что сделал два решения, но давай уберем это, так как задание все таки предполагает, что реализация функций min и max на нас

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax_hashmap.js
> +let minmaxHashmap = (numberString) => {
В мире современного фронтенда поняли, что типы, в целом, вещь полезная, поэтому придумали typescript. Мы пока его не готовы тут использовать, но давай оформим функцию с JSDoc, чтобы понимать ее аргументы и возвращаемое значение

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax_hashmap.js
> +let minmaxHashmap = (numberString) => {
Первые 2 вопросика: тут ты использовал стрелочные функции для определения функции. Можно ли как то еще сделать функцию? 

Какие способы объявления переменных ты знаешь, есть ли тут вариант, более подходящий, чем `let`?

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax_hashmap.js
> +  // render some special response, but it would be an overengineering for this task, so just raise message.
Как такого, обработчика ошибок по умолчанию в js нет - есть блоки try catch, которые перехватывают ошибки, но так как мы пишем низкоуровневую функу, то от нее обычно ожидается всплытие ошибки, так что тут все верно)

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax_hashmap.js
> +  let current_max = hashmap.get('max');
Значения не меняешь -> `const`, и лучше функцию объявить выше, до ее применения

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax_hashmap.js
> +let setMapValues = (hashmap, number) => {
Тоже JSDoc

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax_hashmap.js
> +  extremeValues.set('max', undefined);
Можно проинициализировать мапу сразу https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/Map

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax_hashmap.js
> +    if (current_num != 0 && !Number(current_num)) {
Вопросик по операторам: `!=` как еще операторы сравнения есть? В чем между ними разница, и лучше ли использовать другой?

2024-09-01 21:52 UTC, Shureks-den commented on source/minmax_hashmap.js
> +    if (current_num != 0 && !Number(current_num)) {
Еще мне кажется, что лучше поменять условия местами, как и в плюсах если в блоке с логическим И не выполнится первое условие, то другие не будут выполнятся

2024-09-02 16:56 UTC, UnicoYal commented on source/minmax_hashmap.js
> +    if (current_num != 0 && !Number(current_num)) {
Со вторым комментом полностью согласен, упустил из виду.
К первому: Есть еще ==, ===, !==, >, <, >=, <=. Последние 4 понятно как работают. Вопросы может вызвать == и === или != и !==. Там где 3 символа называются сторогими. Разница в том, что в строгих не будет неявного преобразования типов(Если я правильно помню, то приводится будет левый операнд). Насчет использования тут !== не уверен, что это обязательно. Сравнение идет с 0, а там как правило все достаточно тривиально

2024-09-02 17:03 UTC, UnicoYal commented on source/minmax_hashmap.js
> +let minmaxHashmap = (numberString) => {
Функцию можно объявить еще с помощью Function Declaration и Function Expression
```js
// Declaration
function minmax(numberString) {
  // ...
}

// Expression
const minmax = function(numberString) {
  // ...
};
```
Способы объявления переменных: let, const, var. В основом отличие в области видимости и в том, что const нельзя переопределить. Думаю, что тут можно поменять на const, потому что функция не должна быть изменяемой после создания плюс защита от случайного переопределения

2024-09-03 10:31 UTC, Shureks-den commented on source/minmax_hashmap.js
> +    if (current_num != 0 && !Number(current_num)) {
Лучше всегда использовать строгое сравнение, чтобы не было непредсказуемых тайпкастов

2024-09-03 10:32 UTC, Shureks-den commented on source/minmax_hashmap.js
> +    if (current_num != 0 && !Number(current_num)) {
Поправь и апрувну

2024-09-03 14:02 UTC, UnicoYal commented on source/minmax_hashmap.js
> +    if (current_num != 0 && !Number(current_num)) {
Поправил

2024-09-03 16:52 UTC, Shureks-den approved these changes

2024-09-07 07:26 UTC, UnicoYal commented on source/minmax.js
> +'use strict';
При помощи "use strict" активируется строгий режим, который будет выдавать исключения на те ошибки, которые в неограниченном режиме были просто опущены. + Вводит ограничения, например: нельзя присваивать значение в неопределённую переменную в строгом режиме

2024-09-07 08:15 UTC, UnicoYal commented on source/minmax.js
> +// Arrow funcions are more readable for me, comparing with function expressions
1) Точно еще помню, что в обычных функциях создается this, т.е. есть контекст. В стрелочных нет, если там обратиться к this, то возьмется предыдущее объявление. Поэтому если происходит взаимодействие с this, то лучше использовать обычные функции
2) Кажется, что стрелочная функция должна быть объявлена выше ее использования, для обычных вроде не обязательно
3) Вроде как нельзя использовать стрелочную функцию в качестве конструктора класса

2024-09-10 21:24 UTC, DPeshkoff commented on tests/minmax.js
>  });
отступы(

2024-09-10 22:05 UTC, UnicoYal commented on tests/minmax.js
>  });
Странно, что в IDE все ок, но если заново поставить этот отступ, то появился дифф)
Поправил

2024-09-12 07:47 UTC, DPeshkoff approved these changes

2024-09-12 07:48 UTC, closed without merging