Стремин Валентин В19
frontend-park-mail-ru/homework_2024_2 pull request #14
Opened 2024-09-01 12:29 UTC by supchaser

Задание:
Напишите функцию sorting, которая принимает на вход массив plain-объектов и массив имён свойств, по которым необходимо отсортировать массив объектов, и реализует устойчивую сортировку этого массива в порядке возрастания (строки сортируются лексикографически, числа — в порядке возрастания).

1) Написана функция sorting;
2) добавлены два теста:
 а) sorting корректно сортирует объекты с отрицательными числовыми свойствами;
 б) sorting корректно сортирует объекты с числовыми свойствами разных знаков.

![image](https://github.com/user-attachments/assets/ebe30663-aa26-4c31-8a24-f546877228e0)

2024-09-02 12:51 UTC, AlexandraSmirnova commented
Привет, Валя! Меня зовут Саша. Поздравляю с переходом на 2-ой семестр. Я твой ментор по ДЗ0 и уже скоро приступлю к проверке. 
Прежде чем начну проверять, хочу попросить тебя исправить конфликты в ПР, их быть не должно :)
Если будут вопросы - мой ник в телеге @alexandrius23

2024-09-03 12:39 UTC, AlexandraSmirnova commented on source/sorting.js
> +  arr.sort((a, b) => {
В задании с сортировкой функцию sort нужно написать самому) Перепиши, пожалуйста, без использования встроенной функции sort

2024-09-03 12:41 UTC, AlexandraSmirnova commented on README.md
> +# frontend-homework, вариант №19
Тут изменений быть не должно, направь пожалуйста ПР в ветку своего варианта, а не в мастер. Тогда будут видны изменения, сделанные только тобой в этом варианте

2024-09-05 07:50 UTC, AlexandraSmirnova requested changes

2024-09-05 07:50 UTC, AlexandraSmirnova commented on source/sorting.js
> +const sorting = (arr, props) => {
Добавь, пожалуйста, jsdoc к функции

2024-09-05 07:50 UTC, AlexandraSmirnova commented on source/sorting.js
> +  for (let i = 0; i < sortedArr.length - 1; i++) {
Тут очень большая вложенность. Как можно уменьшить количество циклов? И какие встроенные методы работы с массивамиможно использовать вместо цикла for?

2024-09-05 07:50 UTC, AlexandraSmirnova commented on tests/sorting.js
> -QUnit.module('Тестируем функцию sorting', function () {
Верни, пожалуйста, табы :) По прежнему вижу изменения всего файла, а не только добавленное / измененное)

2024-09-05 21:04 UTC, supchaser commented on source/sorting.js
> +const sorting = (arr, props) => {
Добавил

2024-09-05 21:13 UTC, supchaser commented on source/sorting.js
> +  for (let i = 0; i < sortedArr.length - 1; i++) {
Исправил. Для уменьшения количества циклов можно использовать различные встроенные методы:
 `arr.sort`, `arr.forEach`, `arr.map`, `arr.reduce`, `arr.some`, `arr.every`, `arr.find`, `arr.flat`, `arr.concat`, `arr.slice` и др.
 Вместо цикла for можно использовать встроенный метод `arr.forEach`

2024-09-05 21:14 UTC, supchaser commented on tests/sorting.js
> -QUnit.module('Тестируем функцию sorting', function () {
Вернул

2024-09-06 20:46 UTC, DeDxYk594 commented on source/sorting.js
> + * @throws {TypeError} Выдаст ошибку, если хотя бы один объект не содержит свойство, по которому arr сортируется
Он выдаст не TypeError, если хотя бы один объект не содержит свойство, по которому arr сортируется

2024-09-09 09:02 UTC, AlexandraSmirnova requested changes

2024-09-09 15:24 UTC, supchaser commented on source/sorting.js
> +      if (elem[prop] === undefined) {
Спасибо за замечание!
Но если `elem[prop]` будет равно, например, 0, то `if(!(elem[prop])` сработает, и ошибка выдастся, когда она не должна выдаваться.
Возможно, я Вас неправильно понял.

2024-09-09 15:32 UTC, supchaser commented on source/sorting.js
> +    throw new TypeError("Either arr or props is undefined");
Поправил

2024-09-10 08:51 UTC, AlexandraSmirnova requested changes

2024-09-10 08:51 UTC, AlexandraSmirnova commented on source/sorting.js
> +      if (elem[prop] === undefined) {
Да, все так, тут возможна явная проверка на undefined. А выше, где `if (arr === undefined || props === undefined) ` можно в краткой форме. Кстати, можно также добавить в тест описанный тобой случай, когда `elem[prop] === 0`

2024-09-10 16:03 UTC, supchaser commented on source/sorting.js
> +      if (elem[prop] === undefined) {
Исправил проверку и добавил новый тест

2024-09-11 12:30 UTC, AlexandraSmirnova requested changes

2024-09-11 12:30 UTC, AlexandraSmirnova commented on source/sorting.js
> +	return sortedArr;
Функция по итогу получилась очень большая. Возможно ли ее как-то декомпозировать?

2024-09-12 14:22 UTC, supchaser commented on source/sorting.js
> +		if (elem[prop] === undefined) {
Поправил

2024-09-14 10:28 UTC, DPeshkoff approved these changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, мне ок)

2024-09-14 10:28 UTC, closed without merging