Мироненко Даниил В15
frontend-park-mail-ru/homework_2024_2 pull request #15
Opened 2024-09-01 16:49 UTC by daronenko

Напишите функцию `filter`, которая фильтрует html-код, оставляя только разрешённые html-теги.

2024-09-02 12:52 UTC, AlexandraSmirnova commented
Привет, Даня! Меня зовут Саша. Поздравляю с переходом на 2-ой семестр. Я твой ментор по ДЗ0 и уже скоро приступлю к проверке. Если будут вопросы - мой ник в телеге @alexandrius23

2024-09-03 10:21 UTC, AlexandraSmirnova requested changes

2024-09-03 10:21 UTC, AlexandraSmirnova commented on tests/filter.js
> +  QUnit.test("filter экранирует символы в обычном тексте", function (assert) {
Давай вернем те отступы, которые были в задании:) Здесь, например, один таб. В этом случае будет изменен не весь файл, а только те строки, где были осмысленные изменения (что-то убрал, добавил, поменял)
Это касается и других файлов, отступы должны быть одинаковыми

2024-09-03 10:21 UTC, AlexandraSmirnova commented on source/filter.js
> +"use strict";
Расскажи для чего используется эта строка?

2024-09-03 10:21 UTC, AlexandraSmirnova commented on source/filter.js
> +const parseTagName = (tag) => {
Отлично, что используешь стрелочные функции) Какие еще способы создания функций знаешь?

2024-09-03 10:21 UTC, AlexandraSmirnova commented on source/filter.js
> +  while (i < chars.length) {
Какие методы работы с массивами js можно здесь изпользовать вместо while?

2024-09-03 20:32 UTC, daronenko commented on source/filter.js
> +"use strict";
Эта директива включает строгий режим, который помогает избежать некоторых ошибок в коде. В этом режиме js будет выбрасывать исключения в ситуациях, которые в обычном режиме могли бы быть проигнорированы, но потенциально могли привести к ошибкам.

2024-09-03 20:49 UTC, daronenko commented on source/filter.js
> +const parseTagName = (tag) => {
* **function declaration** - такая функция может быть вызвана до ее определения:

```javascript
function sum(a, b) {
  return a + b;
}
```

* **function expression** - такие функции можно определять и использовать динамически, то есть присваивая их переменным:

```javascript
const sum = function(a, b) {
  return a + b;
};
```

2024-09-03 21:16 UTC, daronenko commented on source/filter.js
> +  while (i < chars.length) {
Да, думаю, что здесь также можно использовать методы `forEach`, `map` или `reduce`, однако логику придется немного изменить.

Примеры использования этих методов:

* `forEach` - вызывает переданную функцию для каждого элемента массива:

```javascript
chars.forEach((char, i) => {
  ...
});
```

* `map` - создает новый массив из элементов, которые возвращает переданная функция:

```javascript
let i = 0;
return chars.map((char) => {
  ...
}).join("");
```

* `reduce` - накапливает строку из элементов, которые возвращает переданная функция:

```javascript
let i = 0;
return chars.reduce((result, char) => {
  ...
}, "");
```

2024-09-03 21:18 UTC, daronenko commented on tests/filter.js
> +  QUnit.test("filter экранирует символы в обычном тексте", function (assert) {
Вернул исходный code style и сделал отступы одинаковыми

2024-09-05 07:57 UTC, AlexandraSmirnova commented on source/filter.js
> +"use strict";
Можешь привести пример таких ситуаций?

2024-09-05 08:01 UTC, AlexandraSmirnova requested changes

2024-09-06 12:10 UTC, daronenko commented on source/filter.js
> +  while (i < chars.length) {
Переписал цикл `while`, используя метод `reduce`, однако пришлось ввести новую переменную `shouldSkip`, потому что методы `reduce`, `map` и `forEach` не позволяют изменить индекс на текущий символ.

2024-09-06 12:23 UTC, daronenko commented on source/filter.js
> +"use strict";
`use strict`:

* не позволяет использовать одинаковые имена для параметров одной функции
* возвращает `undefined` при обращении к `this` внутри функции (вместо window object)
* не позволяет использовать ключевые слова в качестве имени
* запрещает обращение к переменной, не имеющей корректного объявления (например, если переменная объявлена внутри функции с ключевым словом `var`)

2024-09-09 07:55 UTC, AlexandraSmirnova approved these changes

2024-09-09 07:55 UTC, AlexandraSmirnova commented on source/filter.js
> +            (item) => typeof item === 'string' || item instanceof String,
В коде вижу 3 проверки на строку, предлагаю вынести это в отдельную функцию, чтобы не повторяться, допустим isString.

2024-09-12 14:56 UTC, closed without merging