Станислав Керимов В6
frontend-park-mail-ru/homework_2024_2 pull request #17
Opened 2024-09-02 13:46 UTC by wiseStann

Добрый день!
Задание: напишите функцию `tree`, которая рисует ASCII-ёлочку высотой N символов из звёздочек

2024-09-03 11:21 UTC, F4lkr4m commented
Привет! Меня зовут Сережа, я ментор по фронтенду и буду проверять у тебя ДЗ №0. К твоему решению я задам несколько вопросов и оставлю комментарии) Как поправишь замечания можешь смело меня пинговать в личку (https://t.me/Falkr4m), так мы сможем ускорить процесс проверки.

![image](https://github.com/user-attachments/assets/d656cd29-71b9-4ca2-b881-6d2c629b08ca)

2024-09-03 11:21 UTC, F4lkr4m commented
Давай уберем "В6" из названия, достаточно будет Имя Фамилия

2024-09-03 11:41 UTC, F4lkr4m requested changes
Все круто, поправь замечания и смело пингуй меня)

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +'use strict';
Подскажи, для чего нужна эта директива?

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +const tree = function (count) {
Тут не хватает описания функции по JSDoc, добавь, пожалуйста)

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +const tree = function (count) {
Тут все смешалось. Ты создал переменную и положил в нее функцию, хотя можно было просто создать функцию. Подскажи, какие есть варианты создания функций в  JS? И чем они отличаются?

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +    if (count < 3) {
Я так понимаю это проверка краевого случая. Тут есть несколько замечаний:
1. Все что не 0, -1, 1 - это MagicNumber, поэтому такие числа надо класть в константы с понятным названием, напр, MIN_TREE_LAYERS_COUNT
2. Тут стоит возвращать не null. Просто тогда не понятно что произошло в функции. Идейно твоя функция. должна либо возвращать результат виде строки, либо выкидывать ошибку. Поэтому было бы классно тут выкидывать ошибку.
3. Что будет если в функцию передать объект, массив или ничего не передать?

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +    let width = (count - 1) * 2 - 1;
Ты использовал для создания переменной let? А почему? А какие варианты задания переменных в JS существуют и чем они отличаются?)

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +    let width = (count - 1) * 2 - 1;
Так же тут получается 2 - это тоже не понятное число, что откуда берется не совсем прозрачно

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +    let expected = "";
Тут ты строку задаешь через `""`, а также там дальше используешь `''` - выбери лишь один вариант)

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +                if (center - stars <= j && j <= center + stars)
Давай сделаем код более читаемым и каждое тело после if выделять фигурными скобками, а также выделять тело переносами

`if (condition) {\n /... \n}`

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +            else {
Если в первом if'е написать continue, то эта лишняя вложенность через else не понадобится

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +const tree = function (count) {
count - не совсем очевидное название, может что-нибудь более говорящее используем?

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +    let expected = "";
Что значит expected?  Если это resultTree, или accumulator, то давай так и назовем

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +        stars++;
А stars у тебя не равно i?

2024-09-03 11:41 UTC, F4lkr4m commented on source/tree.js
> +                if (center - stars <= j && j <= center + stars)
И тут скорее тебе стоит выделить конкретно этот случай и в обратном делать основной алгоритм цикла, те:
```
if (i === count - 1) { // добавляем палочку; continue; } 
// ... основная логика
```

2024-09-03 11:41 UTC, F4lkr4m commented on tests/tree.js
> +	QUnit.test('Ёлочка высотой 6', function (assert) {
Классно, что добавил свои тесты. 
Также добавь проверки краевых случаев - когда передаем в аргументы - объект, массив или ничего

2024-09-03 13:20 UTC, wiseStann commented on source/tree.js
> +'use strict';
Используя данную директиву, мы переводим скрипт в "строгий режим". В этом режиме интерпретатор будет более педантично и точно интерпретировать скрипт. Таким образом улучшается безопасность кода и предотвращаются ошибки. И ещё насколько мне известно, в строгом режиме повышается качество оптимизации кода.

2024-09-03 13:59 UTC, wiseStann commented on source/tree.js
> +const tree = function (count) {
На данный момент я могу выделить три основных вида создания функций: функции типа declaration statement, функции типа definition expression и стрелочные функции. Первые функции являются самыми обычными функциями, такими же как в Си или Пайтоне. Вторые можно использовать как результат выражения и присваивать переменным для того, чтобы впоследствии передать в качестве аргумента, например. Третьи функции всегда анонимны, имеют укороченный синтаксис и лексически связывают значение this.

2024-09-03 14:06 UTC, wiseStann commented on source/tree.js
> +    if (count < 3) {
Судя по моим тестам, ничего страшного не произойдёт, ничего не упадёт, что может привести к багам в будущем. Добавил выкидывание ошибки.

2024-09-03 15:18 UTC, wiseStann commented on source/tree.js
> +    let width = (count - 1) * 2 - 1;
Переменные можно объявить с помощью ключевых слов var, let или const. Переменные, объявленные с помощью var, let в отличие от const переменных могут быть изменены в будущем. Переменная, объявленная с помощью ключевого слова var, может быть доступна глобально или локально в блоке кода, в то время как let переменная доступна только из блока, где она объявлена. let является более предпочтительным и современным способом объявления переменных.

2024-09-03 16:05 UTC, F4lkr4m commented on source/tree.js
> +'use strict';
Ну вообще если более простым языком оно включает современный режим и запрещает использовать "старые" конструкции по типу объявления переменных через var

2024-09-03 16:16 UTC, F4lkr4m commented on source/tree.js
> +const tree = function (count) {
Да, по факту просто их делят на стрелочные функции не стрелочные. Но стрелочные имеют особенности:
1. Не имеют своего контекста - опираются на внешний
2. Не имеют массива arguments
3. Не могут быть вызваны у дочерних классов в случае объявления в родительском

2024-09-03 16:23 UTC, F4lkr4m requested changes

2024-09-03 16:23 UTC, F4lkr4m commented on source/tree.js
> + *
Не хватает описания выбрасываемых ошибок

2024-09-03 16:23 UTC, F4lkr4m commented on source/tree.js
> +function tree(height) {
Го поменяем на модную стрелочную функцию)

2024-09-03 16:23 UTC, F4lkr4m commented on source/tree.js
> +    if (typeof height !== "number" && typeof height !== "string" ||
А если передать дробное число?

2024-09-03 16:23 UTC, F4lkr4m commented on source/tree.js
> +    let width = (height - 1) * STARS_PER_LINE_INCREM_FACTOR - 1;
Почему тут не const?

2024-09-03 16:25 UTC, F4lkr4m requested changes

2024-09-03 16:25 UTC, F4lkr4m commented on source/tree.js
> +            if (i == height - 1) {
Почему двойное равно? Какие виды сравнения переменных бывают?

2024-09-04 10:34 UTC, wiseStann commented on source/tree.js
> +            if (i == height - 1) {
Двойное равно проверяет только на равенство значений, а тройное ещё и на равенство типов

2024-09-04 19:29 UTC, F4lkr4m requested changes

2024-09-04 19:29 UTC, F4lkr4m commented on source/tree.js
> + * @param {(number|string)} height
Можно без круглых скобок

2024-09-04 19:29 UTC, F4lkr4m commented on source/tree.js
> +const heightIsCorrect = (height) => {
`isHeightCorrect`

2024-09-04 19:29 UTC, F4lkr4m commented on source/tree.js
> +    const heightInt = parseFloat(height);
Почему parseFloat?

2024-09-04 19:32 UTC, F4lkr4m requested changes

2024-09-04 19:32 UTC, F4lkr4m commented on tests/tree.js
> -		assert.strictEqual(tree(0), null);
Кажется я тебя дизориентировал. Давай тесты исходные не менять. 
Сделаем так:
- При корректных числах < 3 возвращать null как в изначальных тестах
- При некорректных входных бросать ошибку

2024-09-05 10:19 UTC, wiseStann commented on source/tree.js
> +    const heightInt = parseFloat(height);
Это упрощает процесс проверки. parseInt успешно парсит входное дробное число до точки, поэтому приходится делать доп. проверки на то, что на входе всё-таки float, а не int. А parseFloat спарсит как целое, так и дробное число, поэтому тут как-то удобнее это вышло...

2024-09-05 10:19 UTC, wiseStann commented on source/tree.js
> +}
GitHub обрезает...

2024-09-05 10:27 UTC, F4lkr4m requested changes

2024-09-05 10:27 UTC, F4lkr4m commented on source/tree.js
> +const isHeightIsCorrect = (height) => {
isHeightCorrect просто

2024-09-05 10:27 UTC, F4lkr4m commented on source/tree.js
> +    return Number.isInteger(heightInt);
Можно попробовать обойтись без `parseFloat` и сделать просто `Number.isInteger(+heightInt)`

2024-09-05 10:27 UTC, F4lkr4m commented on source/tree.js
> + *
Пробельные строки между строчками с собачками можно не ставить

2024-09-05 10:27 UTC, F4lkr4m commented on source/tree.js
> +    } else if (height < MIN_TREE_LAYERS_COUNT) {
Давай без else if оно же, просто if. У тебя некорректная величина сюда уже попасть не сможет

2024-09-05 10:40 UTC, F4lkr4m requested changes

2024-09-05 10:40 UTC, F4lkr4m commented on source/tree.js
> +    if (typeof height !== 'number' && typeof height !== 'string') {
А возможно и без этой проверки можно обойтись :D

2024-09-05 11:12 UTC, wiseStann commented on source/tree.js
> +    if (typeof height !== 'number' && typeof height !== 'string') {
И правда можно 😅

2024-09-05 11:15 UTC, F4lkr4m requested changes

2024-09-05 11:15 UTC, F4lkr4m commented on source/tree.js
> +const isHeightCorrect = (height) => {
Давай уже без промежуточной функции, просто в ифаке напиши  `!Number.isInteger(+height)`

2024-09-05 11:47 UTC, F4lkr4m requested changes

2024-09-05 11:47 UTC, F4lkr4m commented on source/tree.js
> +                if (j === center) {
Предлагаю это упростить до такой конструкции `resultTree += j === center ? '|' : ' ';`

2024-09-05 11:47 UTC, F4lkr4m commented on source/tree.js
> +            if (center - i <= j && j <= center + i) {
Это условие можно запихнуть в `isTree` и сделать такой же тернарник как сверху

2024-09-05 12:18 UTC, F4lkr4m requested changes

2024-09-05 12:42 UTC, F4lkr4m approved these changes
lgtm

2024-09-08 18:27 UTC, DPeshkoff approved these changes

2024-09-08 18:27 UTC, closed without merging