Демченко Лев
frontend-park-mail-ru/homework_2024_2 pull request #18
Opened 2024-09-02 13:52 UTC by qwerty268

2024-09-03 11:42 UTC, F4lkr4m commented
Привет! Меня зовут Сережа, я ментор по фронтенду и буду проверять у тебя ДЗ №0. К твоему решению я задам несколько вопросов и оставлю комментарии) Как поправишь замечания можешь смело меня пинговать в личку (https://t.me/Falkr4m), так мы сможем ускорить процесс проверки.

![image](https://github.com/user-attachments/assets/350d12c1-1940-4b51-b071-85e75aa49dad)

2024-09-03 11:52 UTC, F4lkr4m commented
Также было бы классно добавить тестов к функции, так мы будем писать более качественный код

2024-09-03 11:53 UTC, F4lkr4m requested changes
Молодец, лаконичное решение получилось, жду правок, как сделаешь - смело пингуй

2024-09-03 11:53 UTC, F4lkr4m commented on source/zip.js
> +'use strict';
Подскажи, что это за директива и для чего она нужна?

2024-09-03 11:53 UTC, F4lkr4m commented on source/zip.js
> +function zip(...objects) {
Тут ты задал функцию через `function`. Подскажи какие есть варианты создания функций в JS? И чем они отличаются?

2024-09-03 11:53 UTC, F4lkr4m commented on source/zip.js
> +function zip(...objects) {
Не хватает JSDoc, давай его докинем :D

2024-09-03 11:53 UTC, F4lkr4m commented on source/zip.js
> +    const result = {};
Используешь const для создания переменной. А какие есть еще варианты создания переменных и чем они отличаются?

2024-09-03 11:53 UTC, F4lkr4m commented on source/zip.js
> +    for (const obj of objects) {
Я понимаю, что в учебе привычно использовать классический for, но го перепишем это на джаваскриптизерский манер: https://learn.javascript.ru/array-iteration - выбери отсюда наиболее подходящий метод

2024-09-03 11:53 UTC, F4lkr4m commented on source/zip.js
> +        for (const key in obj) {
Где-то используешь `const key in obj`, а где то `const key of obj`, подскажи чем они отличаются?  И где что для чего используешь?

2024-09-03 11:53 UTC, F4lkr4m commented on source/zip.js
> +function zip(...objects) {
А что если передать в аргументы ничего, или строку, или undefined? Надо добавить обработку краевых случаев)

2024-09-03 11:53 UTC, F4lkr4m commented on source/zip.js
> +        for (const key in obj) {
Также как можно переписать данный цикл с помощью методов массивов джса?

2024-09-03 19:45 UTC, qwerty268 commented on source/zip.js
> +'use strict';
Включает строгий режим. Не дает программе выполняться, если есть ошибки.

2024-09-03 19:54 UTC, qwerty268 commented on source/zip.js
> +function zip(...objects) {
какие есть варианты создания функций в JS?
через function, стрелочная и асинхронная.

чем они отличаются?
В стрелочной ссылка this указывает на объект из старшей по стеку функции.

2024-09-03 19:59 UTC, qwerty268 commented on source/zip.js
> +    const result = {};
vat и let. let видно только в блоке {}, а var переменную видно во всей функции

2024-09-03 20:27 UTC, qwerty268 commented on source/zip.js
> +        for (const key in obj) {
of проходит по значениям, а In по свойствам.
Переписать можно так:
objects.forEach((obj) => {
            for (const key in obj) {
                if (!result.hasOwnProperty(key)) {
                    result[key] = obj[key];
                }
            }
        }
)

2024-09-04 19:12 UTC, F4lkr4m commented on source/zip.js
> +'use strict';
Ну если есть ошибки, то она в целом не выполнится. А что именно за строгий режим?

2024-09-04 19:14 UTC, F4lkr4m commented on source/zip.js
> +function zip(...objects) {
Ну по факту два варианта создания - стрелочная и через `function`

Помимо того, что стрелочная берет внешний контекст, также стрелочная функция не имеет массив arguments, и не может быть использована в классах потомках

2024-09-04 19:21 UTC, F4lkr4m requested changes
Давай еще не забудем добавить свои тесты на эту функцию!

2024-09-04 19:21 UTC, F4lkr4m commented on source/zip.js
> +/*** функция выделяющая все параметры и их значения */
Это неправильный формат JSDoc, JSDoc также в базовом варианте содержит передаваемые аргументы, возвращаемое значение и выкидываемые ошибки

2024-09-04 19:21 UTC, F4lkr4m commented on source/zip.js
> +function zip(...objects) {
Давай еще перепишем эту функцию на модную стрелочную функцию

2024-09-04 19:21 UTC, F4lkr4m commented on source/zip.js
> +    if (objects.size() == 0) {
А `!objects.length` не подойдет?

2024-09-04 19:21 UTC, F4lkr4m commented on source/zip.js
> +         throw new Error('No parameters');
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error - в JS есть уже готовые типы ошибки, выбери наиболее подходящий отсюда

2024-09-04 19:21 UTC, F4lkr4m commented on source/zip.js
> +        for (const key in obj) {
Можно также использовать `Object.entries()` заместо `for (const key in obj) `

2024-09-04 19:21 UTC, F4lkr4m commented on source/zip.js
> +            if (obj[key] === undefined) {
`if (!obj[key])`

2024-09-04 19:21 UTC, F4lkr4m commented on source/zip.js
> +                throw new Error('Parameter is undefined!');
Тут тоже можно выбрасывать готовую ошибку

2024-09-10 06:45 UTC, F4lkr4m requested changes

2024-09-10 06:45 UTC, F4lkr4m commented on source/zip.js
> +    * @throws {TypeError} Если параметр nil
Что значит nil?) Мы тут гошкой не пользуемся

2024-09-10 06:45 UTC, F4lkr4m commented on source/zip.js
> +    * @param {obj} ...objects - Объекты, из которых выделяем значения и параметры
Такого типа `obj` нет

2024-09-10 06:45 UTC, F4lkr4m commented on source/zip.js
> +    * @param {obj} ...objects - Объекты, из которых выделяем значения и параметры
И у тебя получается здесь массив должен быть

2024-09-10 06:45 UTC, F4lkr4m commented on source/zip.js
> +        for (const [key, value] of Object.entries(obj)) {
`Object.entries(obj).forEach(...)`

2024-09-10 06:45 UTC, F4lkr4m commented on source/zip.js
> +    objects.forEach((obj) => {
А если вызвать функцию с `zip(1, 2, 3)` или `zip(new Number(1), 2, 3)` или `zip('hello', ' ', 'world')` и тд? Нам нужно убедиться, что в аргументах объекты

2024-09-10 06:52 UTC, qwerty268 commented on source/zip.js
> +'use strict';
это режим выполнения, который вводит более строгие правила для написания кода.
Режим включает:

- Запрет неявных глобальных переменных.
- Ошибки при использовании зарезервированных слов
- Запрет на удаление переменных
- Защита от дублирования параметров
- В строгом режиме this будет undefined

2024-09-10 07:33 UTC, F4lkr4m approved these changes
lgtm

2024-09-12 13:34 UTC, Sarafa2n commented
А если я передам в значение new Array() или new String()

2024-09-13 08:04 UTC, qwerty268 commented
Вернется пустой объект

2024-09-13 09:40 UTC, qwerty268 commented
Все работает

`a = new String('ss')
String {'ss'}
zip(a)
{0: 's', 1: 's'}0: "s"1: "s"[[Prototype]]: Object
a
String {'ss'}0: "s"1: "s"length: 2[[Prototype]]: String[[PrimitiveValue]]: "ss"`

2024-09-13 09:43 UTC, qwerty268 commented
Если отдать не пустую строку, то все работает
input:
a = new String('ss')
zip(ss)
Output:
{0: 's', 1: 's'}

2024-09-13 09:44 UTC, qwerty268 commented
> А если я передам в значение new Array() или new String() ??
Если отдать не пустую строку, то все работает
input:
a = new String('ss')
zip(ss)
Output:
{0: 's', 1: 's'}

2024-09-13 15:39 UTC, closed without merging