Новиков Александр
frontend-park-mail-ru/homework_2024_2 pull request #19
Opened 2024-09-02 14:39 UTC by Wolfsanek2

Вариант 19
Группа WEB-21

2024-09-03 19:06 UTC, let-robots-reign commented
И еще 2 общих момента:
1) Добавь, пожалуйста, JSDoc для своей функции
2) Было бы хорошо добавить пустые строки в конце js-файлов. Это такое "правило хорошего тона", вот [тут](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file) есть несколько причин, почему разработчики условились так делать

2024-09-06 09:59 UTC, Wolfsanek2 commented on source/sorting.js
> +'use strict';
'use strict' переключает интерпретатор js в более строгий режим и не позволяет делать некоторые небезопасные вещи, например обязывает при объявлении переменной использовать ключевые слова let и const.

2024-09-06 11:32 UTC, Wolfsanek2 commented on source/sorting.js
> +        initial.sort((a, b) => {
Стрелочная функция является функциональным выражением, т.е. может быть присвоена какой-либо переменной, например объявленной с помощью const. В таком случае переприсвоить значение такой переменной не получится. Также стрелочная функция имеет более короткий синтаксис по сравнению с обычным функциональным выражением и не имеет собственного собственного контекста this

2024-09-06 11:40 UTC, Wolfsanek2 commented on source/sorting.js
> +            return a[field] < b[field] ? -1 : 1;
== это оператор нестрогого сравнения с приведением типов, т.е. например '5' == 5 вернет true. === сравнивает значения без приведения типов, что позволяет избежать неожиданных результатов

2024-09-06 11:57 UTC, let-robots-reign commented on source/sorting.js
> +'use strict';
> обязывает при объявлении переменной использовать ключевые слова let и const

Надо поточнее сказать, посмотри на примеры:
Есть ошибка:
```
"use strict";

a = 1;
```
let и const не использую, нет ошибки:
```
"use strict";

var a = 1;
```

2024-09-06 12:05 UTC, let-robots-reign commented on source/sorting.js
> +const sorting = (initial, fields) => {
Я бы тут еще добавил обработку краевых случаев для параметров: когда они не переданы или неправильный тип
И добавить тесты на это

2024-09-06 12:22 UTC, Wolfsanek2 commented on source/sorting.js
> +'use strict';
Ну да, "use strict" не позволяет использовать необъявленные переменные. Без него js автоматически объявил бы ее в глобальной области видимости

2024-09-06 18:27 UTC, let-robots-reign approved these changes
Отлично, быстро все поправил
У меня замечаний не осталось, ставлю аппрув

2024-09-08 18:29 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 18:29 UTC, DPeshkoff commented on source/sorting.js
> +        if (typeof field !== 'string') {
Не пройдем

<img width="233" alt="Снимок экрана 2024-09-04 в 18 32 35" src="https://github.com/user-attachments/assets/9f789f48-56fd-44a1-8855-a092190cb65c">

2024-09-08 18:29 UTC, DPeshkoff commented on source/sorting.js
> +                throw new Error('initial must contain only strings');
Объекты или строки?)

2024-09-10 21:09 UTC, DPeshkoff approved these changes

2024-09-10 21:09 UTC, closed without merging