Variant-8
frontend-park-mail-ru/homework_2024_2 pull request #2
Opened 2024-08-26 19:40 UTC by Alexeyzem

Земляков Алексей 
WEB-21

2024-08-30 20:05 UTC, sonichka-s commented
Привет! Поздравляю тебя с переходом на второй семестр и желаю провести его максимально круто!)
Меня зовут Соня, я буду проверять твое ДЗ №0. Если возникнут любые вопросы, можешь смело обращаться ко мне)

Для начала пара небольших правок:

1. Некорректное название ПРа, оно должно содержать твои фамилию и имя. Номер варианта можешь добавить в коментарий
2. Папку .idea стоит отправить в gitignore
3. Отсутсиве пустой строки в конце файлов .js
4. Откуда взялись файлы max.js? По заданию необходимо реализовать только sort

2024-08-31 06:58 UTC, Alexeyzem commented
Вариант-8

2024-08-31 10:36 UTC, sonichka-s reviewed
Общая рекомендация: обрати внимание на код-стайл, много где забыты ";". Для автоформатирования можно использовать линтеры. Пустую строку забыл..

2024-08-31 10:36 UTC, sonichka-s commented on source/sort.js
> +const collator = new Intl.Collator()
Здорово, что ты знаешь такой объект! Но может быть здесь его использование избыточно?

2024-08-31 10:36 UTC, sonichka-s commented on source/sort.js
> +    words.sort(collator.compare)
К сожалению, в этом задании не рекомендуется использовать встроенные методы.
Как сортировка работает для символов? Сможешь написать самостоятельную реализацию sort?

2024-08-31 10:36 UTC, sonichka-s commented on source/sort.js
> +function sortSentence(sentence) {
Что случится если будет передано число или какой-то другой тип данных? Надо бы проверить что входные данные валидны

2024-08-31 10:36 UTC, sonichka-s commented on source/sort.js
> +    for (let i in words) {
Для более удобного перебора массива в js существуют специальные методы ([дока](https://learn.javascript.ru/array-iteration)). Подумай, какой лучше подойдет в твоем случае?

2024-08-31 10:36 UTC, sonichka-s commented on tests/sort.js
> +	QUnit.test('Функция работает правильно если входная строка пуста', function (assert) {
Хорошие тесты! Как и писала выше, добавь кейс с невалидными данными

2024-08-31 10:36 UTC, sonichka-s commented on source/sort.js
> +        if (letterArray.length > 0) {
Может лучше перенести проверку в начало блока? Зачем нам выполнять со строкой столько опраций если она в итоге окажется пустой?

2024-08-31 17:22 UTC, Alexeyzem commented on source/sort.js
> +'use strict';
До определенного времени JS был обратно совместим, потом вышла обнова и добавились новые функциональности. И чтобы строго прописать, что теперь используем "современный" js прописываем эту директиву

2024-08-31 17:24 UTC, Alexeyzem commented on source/sort.js
> +const collator = new Intl.Collator()
Без данного обьекта ё не будет сортироваться верно, так как в кодировке, которая используется в js ё стоит раньше чем все остальные русские буквы алфавита

2024-08-31 17:26 UTC, Alexeyzem commented on source/sort.js
> +    words.sort(collator.compare)
Сортировка для символов:
Сравнивается их кодировка, начиная с первого символа в слове, так у кого больше, то слово и является больше, если равны, то переходит к следующему символу и так до конца, в случае, если одно слово заканчивается, то больше то слово, которое не закончилось

2024-08-31 17:32 UTC, Alexeyzem commented on source/sort.js
> +    for (let i in words) {
Можно через for-each, чтобы сделать все in-place, так как map создаст новый массив и выделит память для этого

2024-08-31 17:45 UTC, Alexeyzem commented on source/sort.js
> +function sortSentence(sentence) {
По поводу стрелочной функции - обычно насколько я понял ее используют, если однострочное действие, но тут оно посложнее. Второе предположение - чтобы указать, что эта функция что-то возвращает

Валидацию добавлю

2024-08-31 17:55 UTC, Alexeyzem commented on source/sort.js
> +    words.sort(collator.compare)
По собственной реализации - да, смогу, но тут тогда надо будет две реализации писать, одна для слова, одна для предложения, но в примере и README рекомендовали как будто использовать встроенные возможности языка

2024-09-01 14:30 UTC, sonichka-s commented on source/sort.js
> +function sortSentence(sentence) {
Действие не обязательно должно быть однострочное, скорее это относится именно к небольшому или несложному участку кода, где она упрощает синтаксис. В дальнейшем без острой необходимости рекомендую использовать именно их. 
Таже это относится к твоей второй фукции и колбэку внутри forEach.

2024-09-01 14:43 UTC, sonichka-s commented on source/sort.js
> +const collator = new Intl.Collator()
Для буквы "ё" можно придумать альтернативное решение, например заменять её на "е"

2024-09-01 14:49 UTC, sonichka-s commented on source/sort.js
> +    words.sort(collator.compare)
Да, встроенные возможности использовать стиот, но в даннный вариант подразумевает именно твою реализацию. Возможно получится обойтись и одной реализацией, ведь массив букв сортируется по тому же принципу что и массив строк

2024-09-01 20:35 UTC, sonichka-s commented
Молодец! Ставлю ОК)

2024-09-01 20:49 UTC, sonichka-s reviewed
Молодец! Еще одна небольшая правка и ставлю ок)

2024-09-01 20:49 UTC, sonichka-s commented on source/sort.js
> +        return ""
Хорошо что добавил обработку, но лучше явно выбросить ошибку и описать что именно пошло не так

2024-09-01 20:49 UTC, sonichka-s commented on source/sort.js
> +        return ""
То же самое

2024-09-04 15:28 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-04 15:28 UTC, DPeshkoff commented on index.html
> -<script src="source/max.js"></script>
Давай оставим оригинальный код и не будем его удалять

2024-09-04 15:28 UTC, DPeshkoff commented on source/max.js
> -const max = numbers => Math.max(...numbers);
И этот файлик вернем)

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +const sort = (sentence) => {
Давай добавим JSDOC

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +const sort = (sentence) => {
А чем отличаются обычные функции от стрелочных? Распиши, пожалуйста

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +    if (sentence.length === 0){
Можно [упростить](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +    sentence = sentence.trim()
А у нас меняется или не меняется в этом случае исходная переменная? Не нарушаем ли принцип чистых функций?)

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +    let str = sentence.toLowerCase().replaceAll('ё', 'е');
А зачем мы так делаем?)

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +        throw new Error("empty data")
Есть различные виды [ошибок](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) - давай подумаем какие можно использовать

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +    if (typeof(sentence) !== 'string') {
А если так?

<img width="250" alt="Снимок экрана 2024-09-04 в 18 26 02" src="https://github.com/user-attachments/assets/e6e152d3-89dd-4d6e-a8c1-ad1d437a3365">

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +        throw new Error("wrong type of data: should be string")
В JS приняты одиночные кавычки, а еще давай ставить в конце точку с запятой

Почему? Давай подумаем, почему падает код

<img width="413" alt="Снимок экрана 2024-09-04 в 18 27 14" src="https://github.com/user-attachments/assets/4dc73df8-ddb1-4f9b-a4e3-ad3adbfdae13">

2024-09-04 15:28 UTC, DPeshkoff commented on source/sort.js
> +const mySort = (array) => {
Тут аналогично)

2024-09-04 15:28 UTC, DPeshkoff commented on tests/sort.js
> +	QUnit.test('Функция работает правильно при неккоретных входных данных', function (assert) {
https://qunitjs.com/api/assert/throws/

2024-09-04 16:03 UTC, Alexeyzem commented on source/sort.js
> +        throw new Error("wrong type of data: should be string")
Так как пытается взять 3 элемент строки и пройтись по нему, поэтому упадет

точку с запятой добавлю
Кавычки исправлю

2024-09-11 20:47 UTC, DPeshkoff requested changes

2024-09-11 20:47 UTC, DPeshkoff commented on source/sort.js
> +let sortLetterInWords = (words) => {
чем let от const отличаются? почему тут let?

2024-09-11 20:47 UTC, DPeshkoff commented on tests/max.js
> +        assert.strictEqual(max([ -1, -2, -3 ]), -1, 'max([-1, -2, -3]) === -1');
<img width="702" alt="Снимок экрана 2024-09-11 в 23 47 05" src="https://github.com/user-attachments/assets/bd1d3217-3323-4899-86ea-cb6344f2fed5">

давай не будем ломать отступы

2024-09-12 07:52 UTC, Alexeyzem commented on source/sort.js
> +let sortLetterInWords = (words) => {
let - переменную после этого можно изменять, const - нельзя.
Если захотим потом динамически изменить вариант сортировки букв в слове, то сможем это сделать, поэтому let

2024-09-12 07:58 UTC, Alexeyzem commented on tests/max.js
> +        assert.strictEqual(max([ -1, -2, -3 ]), -1, 'max([-1, -2, -3]) === -1');
Поправил

2024-09-13 06:45 UTC, DPeshkoff approved these changes

2024-09-13 06:45 UTC, closed without merging