Данил Злобин
frontend-park-mail-ru/homework_2024_2 pull request #20
Opened 2024-09-03 11:02 UTC by Danil-Zlo

2024-09-03 12:00 UTC, F4lkr4m commented
Привет! Меня зовут Сережа, я ментор по фронтенду и буду проверять у тебя ДЗ №0. К твоему решению я задам несколько вопросов и оставлю комментарии) Как поправишь замечания можешь смело меня пинговать в личку (https://t.me/Falkr4m), так мы сможем ускорить процесс проверки.

![image](https://github.com/user-attachments/assets/c3aa1a02-e757-4220-8083-3549a038811f)

2024-09-03 12:13 UTC, F4lkr4m requested changes
Хорошее решение получилось, поправь комменты и смело пингуй меня)

2024-09-03 12:13 UTC, F4lkr4m commented on index.html
> -<div id="qunit"></div>
Давай тут ничего не менять и не удалять, просто добавляем свои скриты, лишних действий нам не надо)

2024-09-03 12:13 UTC, F4lkr4m commented on source/euclid.js
> +"use strict";
Подскажи, для чего используется эта директива?

2024-09-03 12:13 UTC, F4lkr4m commented on source/euclid.js
> +function euclid(...numbers) {
Тут ты задаешь функцию через ключевое слово `function`, подскажи какие еще методы создания функций есть в js? И  чем они отличаются?

2024-09-03 12:13 UTC, F4lkr4m commented on source/euclid.js
> +function euclid(...numbers) {
Также стоит добавить описание функции в формате JSDoc)

2024-09-03 12:13 UTC, F4lkr4m commented on source/euclid.js
> +  if (!numbers.every(Number.isInteger)) {
Классно, что обрабатываешь входные данные! А если вызвать функцию без аргументов? `euclid()`

2024-09-03 12:13 UTC, F4lkr4m commented on source/euclid.js
> +    return 'Error';
Возвращать не понятную строку не совсем корректно. Твоя функция по факту должна либо возвращать значение конкретное, либо выбрасывать ошибку. Давай будем выбрасывать ошибку

2024-09-03 12:13 UTC, F4lkr4m commented on source/euclid.js
> +    while (b !== 0) {
По идее ты тут ищешь нод двух чисел, можно это все записать в отдельную функцию

2024-09-03 12:13 UTC, F4lkr4m commented on source/euclid.js
> +  let result = numbers[0];
Возможно стоит результат назвать как resultNOD - что будет более очевидно для читателей твоего кода

2024-09-03 12:13 UTC, F4lkr4m commented on tests/euclid.js
> +	QUnit.test('ДОБ.: Функция должна уметь обрабатывать отрицательные числа', function (assert) {
Молодец, что добавил тесты!

2024-09-03 12:13 UTC, F4lkr4m commented on source/euclid.js
> +    while (b !== 0) {
Какие варианты сравнения переменных в JS есть?

2024-09-06 12:15 UTC, Danil-Zlo commented on source/euclid.js
> +"use strict";
В JavaScript директива 'use strict' используется для включения строгого режима. Строгий режим - это способ оптимального выбора ограниченной версии JavaScript, который помогает обнаруживать общие ошибки и улучшает качество кода.

2024-09-06 12:18 UTC, Danil-Zlo commented on source/euclid.js
> +function euclid(...numbers) {
Синтаксис, который я использовал, называется Function Declaration (Объявление Функции):

function sayHi() {
  alert( "Привет" );
}
Существует ещё способ создания функций, который называется Function Expression (Функциональное Выражение).

Данный синтаксис позволяет нам создавать новую функцию в середине любого выражения.

Это выглядит следующим образом:

let sayHi = function() {
  alert( "Привет" );
};

После ключевого слова function нет имени. Для Function Expression допускается его отсутствие.

Другой синтаксис, который часто лучше, чем Function Expression, называется «функции-стрелки» или «стрелочные функции» (arrow functions), т.к. выглядит следующим образом:

let func = (arg1, arg2, ...argN) => expression;
Это создаёт функцию func, которая принимает аргументы arg1..argN, затем вычисляет expression в правой части с их использованием и возвращает результат.

Другими словами, это сокращённая версия:

let func = function(arg1, arg2, ...argN) {
  return expression;
};

2024-09-06 12:19 UTC, Danil-Zlo commented on source/euclid.js
> +  if (!numbers.every(Number.isInteger)) {
В строгом режиме, если функция вызывается без аргументов, то аргумент numbers будет иметь значение undefined. Затем, когда функция пытается вызвать метод every на numbers, будет выброшена ошибка TypeError, потому что undefined не имеет метода every.

Чтобы избежать этой ошибки, добавил проверку на наличие аргументов в функции.

2024-09-06 12:19 UTC, Danil-Zlo commented on source/euclid.js
> +    return 'Error';
Исправил: в случае ошибки функция теперь выбрасывает ошибку, а не возвращает строку.

2024-09-06 12:19 UTC, Danil-Zlo commented on source/euclid.js
> +  let result = numbers[0];
var message = 'Hello';
Ключевое слово var – почти то же самое, что и let. Оно объявляет переменную, но немного по-другому, «устаревшим» способом.

Можно создать переменную простым присвоением значения без использования let. Это работает, если мы не включаем use strict в наших файлах, чтобы обеспечить совместимость со старыми скриптами.

num = 5;

Чтобы объявить константную переменную используют const вместо let:

const myBirthday = '18.04.1982';

2024-09-06 12:19 UTC, Danil-Zlo commented on source/euclid.js
> +  for (let i = 1; i < numbers.length; i++) {
Переписал циклы через метод массива .reduce()

2024-09-06 12:20 UTC, Danil-Zlo commented on source/euclid.js
> +    while (b !== 0) {
Вынес поиск НОД в отдельную функцию findNOD()

Варианты сравнения переменных в JS:

1. Строгое равенство (===)
Строгое равенство проверяет, является ли значение левой части оператора равным значению правой части, учитывая тип данных. Если типы данных не совпадают, оператор возвращает false.

Пример: a === b

2. Нестрогое равенство (==)
Нестрогое равенство проверяет, является ли значение левой части оператора равным значению правой части, не учитывая тип данных. Если типы данных не совпадают, JavaScript пытается преобразовать значения к одному типу перед сравнением.

Пример: a == b

3. Строгое неравенство (!==)
Строгое неравенство проверяет, не является ли значение левой части оператора равным значению правой части, учитывая тип данных.

Пример: a !== b

4. Нестрогое неравенство (!=)
Нестрогое неравенство проверяет, не является ли значение левой части оператора равным значению правой части, не учитывая тип данных.

Пример: a != b

5. Object.is() 
Метод Object.is() определяет, являются ли два значения одинаковыми значениями.

Синтаксис
var isSame = Object.is(value1, value2);

2024-09-06 12:59 UTC, F4lkr4m commented on source/euclid.js
> +function euclid(...numbers) {
Да, они отличаются написанием, но не только, есть еще конкретные отличия в работе стрелочной функции и не стрелочной, можешь подсказать какие еще есть отличия?

2024-09-06 13:06 UTC, F4lkr4m commented on source/euclid.js
> +function euclid(...numbers) {
Давай еще эту функцию поменяем на модную стрелочную

2024-09-06 13:10 UTC, F4lkr4m commented on README.md
Это не удаляем

2024-09-06 13:10 UTC, F4lkr4m commented on screenshot.png
Это тоже не удаляем

2024-09-06 13:11 UTC, F4lkr4m commented on homework_2024_2
А зачем нам тут сабмодуль?  О.О

2024-09-06 13:11 UTC, F4lkr4m commented on source/max.js
Эти файлы тоже не удаляем
Мы лишь добавляем файл euclid.js в source и больше ничего не удаляем

2024-09-06 16:23 UTC, Danil-Zlo commented on source/euclid.js
> +function euclid(...numbers) {
Главное отличие между стрелочной функцией и обычной функцией в JS - это контекст this. В традиционных функциях this ссылается на объект, который вызвал функцию, а в стрелочных функциях this ссылается на контекст, в котором была определена функция.

2024-09-06 22:36 UTC, F4lkr4m commented on source/euclid.js
> +function euclid(...numbers) {
Также еще нет у стрелочных массива arguments, а также контекста super

2024-09-06 22:40 UTC, F4lkr4m requested changes
Хорошее решение, немного лишь поправить

2024-09-06 22:40 UTC, F4lkr4m commented on source/euclid.js
> +    [a, b] = [b, a % b];
Давай соблюдать чистоту функций не менять входные переменные

2024-09-06 22:40 UTC, F4lkr4m commented on source/euclid.js
> +let euclid = (...numbers) => {
Почему тут используешь let? Какие варианты создания переменных существуют и чем они отличаются?

2024-09-06 22:40 UTC, F4lkr4m commented on source/euclid.js
> + * @param {...number} числа Массив чисел.
Забыл `@throws`

2024-09-06 22:40 UTC, F4lkr4m commented on source/euclid.js
> +    throw new Error('No arguments provided');
В Js есть уже готовые типы ошибок https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error - выбери наиболее подходящую отсюда

2024-09-06 22:40 UTC, F4lkr4m commented on source/euclid.js
> +    throw new Error('No arguments provided');
И еще, а что если на вход ничего не подать?

2024-09-07 08:11 UTC, Danil-Zlo commented on source/euclid.js
> +    throw new Error('No arguments provided');
Исправил

Если на вход ничего не подать, то функция вернёт undefined (если убрать обработку этого кейса)

2024-09-07 08:12 UTC, Danil-Zlo commented on source/euclid.js
> + * @param {...number} числа Массив чисел.
Исправил

2024-09-07 08:15 UTC, Danil-Zlo commented on source/euclid.js
> +    [a, b] = [b, a % b];
Исправил

2024-09-07 08:33 UTC, Danil-Zlo commented on source/euclid.js
> +let euclid = (...numbers) => {
let используется для объявления переменной, которая может быть переопределена в будущем. Она имеет блочную область видимости, что означает, что она доступна только внутри блока, в котором была объявлена (например, внутри функции или цикла). Если переменная объявлена с помощью let вне блока, то она будет глобальной.

const используется для объявления константы, которая не может быть переопределена. Она также имеет блочную область видимости, как и let. Если переопределить константу, возникнет ошибка.

var - имеет функциональную область видимости, что означает, что переменная доступна внутри всей функции, в которой была объявлена, а не только внутри блока. Однако, var имеет некоторые недостатки, такие как "hoisting" (переменная будет поднята вверх к началу блока, даже если она была объявлена в середине), что может привести к ошибкам.

2024-09-07 11:02 UTC, F4lkr4m requested changes

2024-09-07 11:02 UTC, F4lkr4m commented on source/euclid.js
> +let euclid = (...numbers) => {
Так и почему тут не const?

2024-09-07 11:02 UTC, F4lkr4m commented on source/euclid.js
> +function findNOD(a, b) {
Давай эту функцию тоже стрелочной сделаем

2024-09-07 15:17 UTC, Danil-Zlo commented on source/euclid.js
> +let euclid = (...numbers) => {
Теперь сделал обе функции const, так как они не предназначены для переопределения

2024-09-07 15:17 UTC, Danil-Zlo commented on source/euclid.js
> +function findNOD(a, b) {
Исправил

2024-09-07 16:07 UTC, F4lkr4m requested changes

2024-09-07 16:07 UTC, F4lkr4m commented on source/euclid.js
> +"use strict";
Тут двойные кавычки, а далее одинарные, давай выберем что-то одно

2024-09-07 16:13 UTC, F4lkr4m approved these changes
lgtm

2024-09-08 18:36 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 18:36 UTC, DPeshkoff commented on index.html
> +  </head>
Давай уберем отсюда изменения - кажется, эти файлы не надо трогать

2024-09-08 18:36 UTC, DPeshkoff commented on source/euclid.js
> +    throw new RangeError("No arguments provided");
Одиночные кавычки)

2024-09-08 18:36 UTC, DPeshkoff commented on source/euclid.js
> +}
Давай добавим перенос в конце файла

2024-09-08 18:36 UTC, DPeshkoff commented on tests/euclid.js
> +		}, Error, 'euclid("a", 2) выбрасывает ошибку');
Предлагаю больше тестов на некорректный ввод

2024-09-08 18:36 UTC, DPeshkoff commented on source/euclid.js
> +  if (!numbers.every(Number.isInteger)) {
А что такое isInteger? Мы его вызываем?

2024-09-08 18:43 UTC, Danil-Zlo commented on source/euclid.js
> +    throw new RangeError("No arguments provided");
Исправил

2024-09-08 18:43 UTC, Danil-Zlo commented on source/euclid.js
> +}
Исправил

2024-09-08 18:45 UTC, Danil-Zlo commented on source/euclid.js
> +  if (!numbers.every(Number.isInteger)) {
.isInteger() - это статический метод, который возвращает true, если переданное значение является целым числом, и false в противном случае.

Здесь Number.isInteger используется как функция-предикат в методе every() для проверки, являются ли все элементы массива numbers целыми числами.

Метод every() возвращает true, если все элементы массива удовлетворяют условию, заданному функцией-предикатом, и false в противном случае.

В данном случае, если хотя бы один элемент массива не является целым числом, метод every() вернёт false, и будет выброшено исключение TypeError.

2024-09-08 19:04 UTC, Danil-Zlo commented on tests/euclid.js
> +		}, Error, 'euclid("a", 2) выбрасывает ошибку');
Исправил

2024-09-10 21:10 UTC, DPeshkoff requested changes

2024-09-11 07:22 UTC, Danil-Zlo commented on tests/euclid.js
> +        assert.strictEqual(euclid(6006), 6006, "euclid(6006) === 6006");
Что значит кодстайл? Вернуть увеличенную табуляцию?

2024-09-12 07:49 UTC, closed without merging