Исаев Тимур
frontend-park-mail-ru/homework_2024_2 pull request #21
Opened 2024-09-03 14:54 UTC by timurIsaevIY

2024-09-03 19:47 UTC, let-robots-reign reviewed
Привет, Тимур!
Рад видеть тебя на 2-м семестре обучения, уверен, что будет очень интересно)
Я дам фидбек по твоему ДЗ0, мой контакт в Телеграме: @let_robots_reign. Можешь писать по любым вопросам

Ниже оставил замечания по коду и несколько вопросов по JS.

Несколько общих моментов:

1. Добавь в описание PR номер варианта и условие задачи
2. В PR залилось очень много лишнего(
Если ты зайдешь во вкладку 'Files changed' ты увидишь, что ты хочешь влить 15,256 строчек. Что добавилось в твою ветку, хотя не должно было:
- .idea
- node_modules - это мы никогда не добавляем, если почитаешь для чего эта директория, будет понятно почему
- package.json, package-lock.json - здесь это не нужно

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +'use strict';
Расскажи, что делает эта строчка и для чего мы это используем?

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +const inverse = (numbers, val) => {
Не хватает проверки того, что numbers - это действительно массив

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +const inverse = (numbers, val) => {
Еще хорошо бы проверить, что если val передан, то это целое число

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +        return numbers.reverse();
`reverse` - это метод, который вносит изменения in-place, то есть меняет входной параметр твоей функции. Из-за этого она перестает быть [чистой](https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D1%81%D1%82%D0%BE%D1%82%D0%B0_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8). Предлагаю сделать нашу функцию чистой

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +    if (val === undefined) {
Что делает оператор `===` и в чем разница между ним и привычным из других языков `==`?

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +        if ( val < 0) {
Лишний пробел после скобки
В остальном со стилем у тебя хорошо, но на всякий случай можно прочитать [советы](https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda) по форматированию

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +    else {
У тебя до этого был `return` по условию, так что здесь else не нужен. Если его убрать, это уменьшит вложенность кода ниже

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +            return [...numbers.slice(0,val).reverse(), ...numbers.slice(val)];
Не хватает пробела после `0,`

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +            return [...numbers.slice(0,val).reverse(), ...numbers.slice(val)];
И что делает такая конструкция перед массивом `...`?

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +        return [...numbers.slice(0,val), ...numbers.slice(val).reverse()];
Здесь тоже пробел добавить

2024-09-03 19:47 UTC, let-robots-reign commented on source/inverse.js
> +console.log(inverse([1, 2, 3, 4, 5], -1))
Лог тут лишний
Чтобы проверить, как работает функция, мы написали тесты)

2024-09-03 19:47 UTC, let-robots-reign commented on tests/inverse.js
> +	// Мои тесты
Не хватает краевых случаев
1) numbers - не массив
2) val - нецелое число/строка/null/Infinity и т. д.
3) Вызов вообще без аргументов

Думаю, что-то еще можно придумать

2024-09-03 19:49 UTC, let-robots-reign commented on source/inverse.js
> +const inverse = (numbers, val) => {
Еще мне кажется, что val - не очень хорошее название для параметра, без чтения кода совсем непонятно, что он должен делать

2024-09-03 19:50 UTC, let-robots-reign commented
И еще 2 момента:

1. Добавь, пожалуйста, JSDoc для своей функции
2. Было бы хорошо добавить пустые строки в конце js-файлов. Это такое "правило хорошего тона", вот [тут](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file) есть несколько причин, почему разработчики условились так делать

2024-09-04 14:45 UTC, timurIsaevIY commented on source/inverse.js
> +'use strict';
Строка `use strict` включает строгий режим выполнения JavaScript.

2024-09-04 14:48 UTC, timurIsaevIY commented on source/inverse.js
> +    if (val === undefined) {
pycharm ругался, предложил поменять

2024-09-04 14:56 UTC, timurIsaevIY commented on source/inverse.js
> +            return [...numbers.slice(0,val).reverse(), ...numbers.slice(val)];
... распаковывает массив

2024-09-04 17:07 UTC, let-robots-reign commented on source/inverse.js
> +'use strict';
А что значит "строгий режим", что он делает?

2024-09-04 17:09 UTC, let-robots-reign commented on source/inverse.js
> +    if (val === undefined) {
Это хорошо, а все же в чем разница?

2024-09-04 17:49 UTC, timurIsaevIY commented on source/inverse.js
> +'use strict';
интерпретатор более строг к синтаксису, тихие ошибки, как исключения обрабатываются

2024-09-04 17:51 UTC, timurIsaevIY commented on source/inverse.js
> +    if (val === undefined) {
== преобразует переменные в один тип, а === нет. Из-за этого в некоторых случаях может по-разному сравниваться

2024-09-04 19:04 UTC, let-robots-reign reviewed
Уже лучше, но появились какие-то другие лишние файлы) Сейчас +12000 строк, должно быть только inverse.js, новые тесты и +1 строчка в html

2024-09-04 19:04 UTC, let-robots-reign commented on source/inverse.js
> +    if (!Array.isArray(numbers)) return;
Нужно добавить тут фигурные скобки, помним про код-стайл

2024-09-04 19:04 UTC, let-robots-reign commented on source/inverse.js
> +        return [...numbers].reverse();
Вот теперь не изменяется) Можно так, можно `numbers.slice().reverse()`, тем более ты уже применял slice ниже

2024-09-04 19:04 UTC, let-robots-reign commented on source/inverse.js
> +        return [...[...numbers.slice(0, partition)].reverse(), ...numbers.slice(partition)];
`[...numbers.slice(0, partition)]` - тут спред лишний, slice и так создает тебе копию ([дока](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/slice))

2024-09-04 19:04 UTC, let-robots-reign commented on source/inverse.js
> +    return [...numbers.slice(0, partition), ...[...numbers.slice(partition)].reverse()];
Здесь аналогично

2024-09-05 09:35 UTC, let-robots-reign reviewed
Изменения увидел, уже немного осталось поправить

И на будущее: старайся добавлять осмысленные названия к коммитам

2024-09-05 09:35 UTC, let-robots-reign commented on source/inverse.js
> +
Между JSDoc и функцией не должно быть пустой строки, иначе некоторые IDE могут не подтянуть информацию о функции при наведении на нее

2024-09-05 09:35 UTC, let-robots-reign commented on source/inverse.js
> +        return [];
Я бы тут все-таки выбрасывал ошибку, так как очевидно, что функцию используют неправильно

2024-09-05 09:35 UTC, let-robots-reign commented on source/inverse.js
> +    if (Number.isInteger(partition) && partition < 0) {
Зачем тут еще раз проверять `Number.isInteger(partition)`, если ты уже проверил это строкой выше?

2024-09-05 09:35 UTC, let-robots-reign commented on source/inverse.js
> +        partition = numbers.length + partition;
Пропустил этот момент, ты тут снова меняешь входной параметр

2024-09-05 09:35 UTC, let-robots-reign commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], ""), [ 5, 4, 3, 2, 1 ]);
Краевые случаи лучше выносить в отдельный `QUnit.test`

2024-09-05 09:35 UTC, let-robots-reign commented on tests/inverse.js
> -		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], -15), [ 1, 2, 3, 4, 5 ]);
А вот эти тесты зачем удалил?

2024-09-05 11:09 UTC, let-robots-reign reviewed
И последнее от меня

2024-09-05 11:09 UTC, let-robots-reign commented on source/inverse.js
> +        throw new Error("numbers должен быть массивом");
Тут больше подходит `TypeError`

2024-09-05 11:09 UTC, let-robots-reign commented on source/inverse.js
> +        return [...numbers.slice(0, numbers.length + partition).reverse(), ...numbers.slice(numbers.length + partition)];
Сделал функцию чистой, но дублирование `numbers.length + partition` лучше убрать, заменив на отдельную переменную

2024-09-05 14:42 UTC, timurIsaevIY commented on source/inverse.js
> +        let reversePartition = numbers.length + partition;
у let и const более ограниченная область видимости, поэтому лучше их использовать

2024-09-05 14:51 UTC, let-robots-reign commented on source/inverse.js
> +        let reversePartition = numbers.length + partition;
Отличия от var ок, а между ними в чем разница? И почему тут выбрал let?

2024-09-05 14:56 UTC, timurIsaevIY commented on source/inverse.js
> +        let reversePartition = numbers.length + partition;
const неизменяемая, let изменяемая. Думаю обе в принципе подходят

2024-09-05 15:24 UTC, let-robots-reign commented on source/inverse.js
> +        let reversePartition = numbers.length + partition;
Если не планируется менять значение переменной, используем `const`, тут как раз такой случай

2024-09-06 08:47 UTC, let-robots-reign approved these changes
LGTM, ставлю аппрув

2024-09-08 18:44 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 18:44 UTC, DPeshkoff commented on source/inverse.js
> +        throw new TypeError("numbers должен быть массивом");
Гоу одиночные кавычки

2024-09-08 18:44 UTC, DPeshkoff commented on source/inverse.js
> +const inverse = (numbers, partition) => {
А какие особенности у таких функций?

2024-09-10 16:22 UTC, timurIsaevIY commented on source/inverse.js
> +const inverse = (numbers, partition) => {
Стрелочный функции позволяют сократить код и у них нет своего контекста this, он будет такой же, как и в той области видимости, где была определена.

2024-09-10 21:04 UTC, DPeshkoff approved these changes

2024-09-10 21:04 UTC, closed without merging