chess added, tests passed
frontend-park-mail-ru/homework_2024_2 pull request #22
Opened 2024-09-03 15:58 UTC by KonstantinGalanin

Не знаю насколько по джаваскриптски, но самый эффективный вариант, который я смог придумал

2024-09-03 21:09 UTC, F4lkr4m commented
Привет! Меня зовут Сережа, я ментор по фронтенду и буду проверять у тебя ДЗ №0. К твоему решению я задам несколько вопросов и оставлю комментарии) Как поправишь замечания можешь смело меня пинговать в личку (https://t.me/Falkr4m), так мы сможем ускорить процесс проверки.

![image](https://github.com/user-attachments/assets/5201d1e5-a15e-440d-a744-2d1dfbd493b1)

2024-09-03 21:30 UTC, F4lkr4m requested changes
Не хватает тестов, следует накинуть несколько) 
А так молодец, хорошо получилось)
Жду правок, как сделаешь - смело пингуй меня

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +const chess = size => {
В JS'е есть такая директива `'use strict'`, ее необходимо добавить и заодно тут рассказать для чего она нужна)

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +const chess = size => {
Тут ты использовал создание функции через стрелочный вариант, а какой вариант создания функции в JS еще есть? И чем эти способы отличаются?

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +const chess = size => {
Давай, для читаемости все конструкции стрелочных функций оборачивать в скобки `const chess = (size) => {} `

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +    size = Number(size);
Такс, по правилам хорошего кода, надо соблюдать чистоту функций и не переопределять внешние параметры)

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +    if (size < 2 || isNaN(size)) {
Все, что не -1, 0, 1 - это MagicNumbers, давай 2 положим в константу и назовем ее понятным названием

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +        return null;
Хорошо, что проверяешь входные параметры, но давай возвращать не null, а выкидывать какую то ошибку)

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +    for (let i = 0; i < size; i++) {
Предлагаю создать функцию, которая будет создавать строчку. Например, `getChessLine(isWhiteFirst)`, потом ее два раза вызвать и получить конкретные строчки доски

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +            first += '*';
Можно использовать тернарник: `first += i % 2 ? '*' : ' '`

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +        if (i % 2 == 0) {
Тут ты используешь двойное равно, какие еще способы сравнения переменных в js есть? И чем они отличаются?

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +            result += first;
Тут тоже можно заиспользовать тернарный оператор

2024-09-03 21:30 UTC, F4lkr4m commented on source/chess.js
> +const chess = size => {
Также еще стоит добавить описание функции в JSDoc)

2024-09-04 12:43 UTC, KonstantinGalanin commented on source/chess.js
> +const chess = size => {
> Тут ты использовал создание функции через стрелочный вариант, а какой вариант создания функции в JS еще есть? И чем эти способы отличаются?

Я использовал стрелочные функции(так вроде принято сейчас), они как обычные функции, но лаконичнее. Есть еще анонимные, которые могут присваиваться переменной

2024-09-04 12:59 UTC, KonstantinGalanin commented on source/chess.js
> +const chess = size => {
> В JS'е есть такая директива `'use strict'`, ее необходимо добавить и заодно тут рассказать для чего она нужна)

'use strict' включает строгий режим, который убирает совместимость с предыдущими обновлениями языка, например раньше не было ключевого слово let,  поэтому можно было писать var let x, что запрещено с use strict

2024-09-04 13:29 UTC, F4lkr4m commented on source/chess.js
> +const chess = size => {
Ну да, use strict включает так сказать современный режим

2024-09-04 13:29 UTC, F4lkr4m commented on source/chess.js
> +const chess = size => {
По поводу функций отличие между обычной и стрелочной немного больше чем просто написание, можешь рассказать поподробнее про отличия?

2024-09-04 13:31 UTC, F4lkr4m commented on source/chess.js
> +        return null;
Там нужно null выбрасывать в случае если size === 1, а в остальных случаях давай ошибку выбрасывать

2024-09-04 13:31 UTC, F4lkr4m commented on source/chess.js
> +        if (i % 2 == 0) {
Отлично, по правилам хорошего тона, в js используют строгое тройное равно

2024-09-04 13:37 UTC, F4lkr4m requested changes

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> +"use strict";
Тут `""` а далее по коду есть `''`. Определись какие кавычки будешь использовать)

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> + *
Не хватает текстового описания функции

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> + * @param {number} isWhiteFirst
Почему number?

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> + * @param {number} isWhiteFirst
Также было бы клево пояснить что значат параметры

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> + *
Тут тоже самое что и к функции выше

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> +    const minSize = 2;
Давай вынесем эту константу за пределы функции, и обзовем ее через PASCAL_CASE

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> +    if (isNaN(size) || size < minSize) {
Если тип не число и если не получается сконвертить строку в число, то надо кидать ошибку

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> +    if (isNaN(size) || size < minSize) {
null ток в случае единичного размера

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> + * @returns {string}
а null где?)

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> +    let first = getChessLine(size, false);
Почему тут используешь let? Как еще можно инициализировать переменную?

2024-09-04 13:37 UTC, F4lkr4m commented on source/chess.js
> +        result += i % 2 === 0 ? first : second;
`result += i % 2 ? second : first;`

2024-09-04 15:40 UTC, KonstantinGalanin commented on source/chess.js
> +        result += i % 2 === 0 ? first : second;
Исправил

2024-09-04 15:42 UTC, KonstantinGalanin commented on source/chess.js
> +    let first = getChessLine(size, false);
let тоже по привычке, в целом строки first и second не меняются и по логике не должны меняться, поэтому исправил на const. Еще есть var, но он устарел

2024-09-04 15:42 UTC, KonstantinGalanin commented on source/chess.js
> + * @returns {string}
не знал, что надо)

2024-09-04 15:48 UTC, KonstantinGalanin commented on source/chess.js
> + * @param {number} isWhiteFirst
isWhiteFirst -  boolean, конечно, поторопился
пояснения написал

2024-09-04 19:47 UTC, F4lkr4m requested changes

2024-09-04 19:47 UTC, F4lkr4m commented on source/chess.js
> +    if (isNaN(size)) {
А если в size передать 'kekw', {}, [] или undefined?

2024-09-04 19:47 UTC, F4lkr4m commented on source/chess.js
> + * @returns {string, null} chess deck
типы описываются через `|` , например `string | null`

2024-09-04 19:47 UTC, F4lkr4m commented on source/chess.js
> +    let line = '';
Что-то ты начал переусложнять. Тебе что вообще надо тут понять изначально - у тебя есть два знака: первый и второй - они меняются в зависимости от `isWhiteFirst`. Поэтому в начале ты должен определить какой будет первым а какой вторым просто на просто, а потом по условию их добавлять.

`const [first, second] = isWhiteFirst ? ['*', ' '] : [' ', '*'];`

2024-09-04 19:47 UTC, F4lkr4m commented on tests/chess.js
> +	QUnit.test('Шахматной доски отрицательного размера не бывает', function (assert) {
Давай добавить проверки на {}, null, undefined, 'kekw' в аргументах

2024-09-05 09:56 UTC, KonstantinGalanin commented on tests/chess.js
> +	QUnit.test('Шахматной доски отрицательного размера не бывает', function (assert) {
Добавил, были только проблемы с [], возвращало null, поэтому добавил в условие
typeof size !== 'number' && typeof size !== 'string'

2024-09-05 10:00 UTC, KonstantinGalanin commented on source/chess.js
> +    let line = '';
Не хотел мудрить в тернарнике, поэтому перемудрил с логикой)
Мне просто по логике функции не подходит, предложенная тобой, конструкция, поэтому я по-другому немного поменял, вроде читабильнее стало

2024-09-05 10:10 UTC, F4lkr4m commented on source/chess.js
> +    let line = '';
У тебя прям код один в один, что снизу, можно цикл снизу скопировать :D

2024-09-05 10:13 UTC, F4lkr4m requested changes

2024-09-05 10:13 UTC, F4lkr4m commented on source/chess.js
> +    if (isNaN(size) || typeof size !== 'number' && typeof size !== 'string') {
Можно просто проверять `Number.isInteger()`

2024-09-05 10:13 UTC, F4lkr4m commented on source/chess.js
> +        throw new Error('The wrong type of size');
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error   - есть готовые ошибки в js, давай использовать их

2024-09-05 15:00 UTC, KonstantinGalanin commented on source/chess.js
> +        throw new Error('The wrong type of size');
Изменил на TypeError (это же имелось ввиду?)

2024-09-05 15:05 UTC, KonstantinGalanin commented on source/chess.js
> +    if (isNaN(size) || typeof size !== 'number' && typeof size !== 'string') {
У нас ведь строки тоже могут подходить( '4' - например )

2024-09-05 16:21 UTC, F4lkr4m approved these changes
lgtm

2024-09-08 18:48 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, накидал чуть-чуть)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 18:48 UTC, DPeshkoff commented on source/chess.js
> +    let line = ''
Не забывай ставить ;

Иначе словим что-то такое(

<img width="387" alt="Снимок экрана 2024-09-08 в 21 45 16" src="https://github.com/user-attachments/assets/3ffa2679-216b-457f-8e41-03fee034b80d">

2024-09-08 18:48 UTC, DPeshkoff commented on source/chess.js
> +    if (!Number.isInteger(+size) || Array.isArray(size)) {
Немного избыточная проверка - давай упростим

<img width="209" alt="Снимок экрана 2024-09-08 в 21 46 06" src="https://github.com/user-attachments/assets/3ed3e0cf-78cd-4d24-9ecb-1b1224598162">

2024-09-09 13:19 UTC, KonstantinGalanin commented on source/chess.js
> +    let line = ''
Поставил

2024-09-09 13:20 UTC, KonstantinGalanin commented on source/chess.js
> +    if (!Number.isInteger(+size) || Array.isArray(size)) {
Написал вопрос в тг

2024-09-10 21:11 UTC, DPeshkoff approved these changes

2024-09-10 21:11 UTC, closed without merging