Селянинов Дмитрий
frontend-park-mail-ru/homework_2024_2 pull request #23
Opened 2024-09-03 17:46 UTC by nonrep

2024-09-05 06:30 UTC, mafin1799 reviewed
Привет
Меня зовут Никита, буду проверять твое ДЗ№0
Оно у тебя получилось достаточно лаконично))

Но нужно доработать решение, чтобы выполнялись только арифметические операции.
Добавить тесты для функции
И ответить на вопросы

2024-09-05 06:30 UTC, mafin1799 commented on source/solve.js
> +function solve(formula, value) {
Почему используешь function?
Какие еще есть варианты объявления функций?

2024-09-05 06:30 UTC, mafin1799 commented on source/solve.js
> +function solve(formula, value) {
Возможно стоит добавить директиву 'use strict' и посмотреть что будет?
Для чего требуется директива 'use strict'

Когда она подключается автоматически?

2024-09-05 06:30 UTC, mafin1799 commented on source/solve.js
> +        let x = value
Почему let, а не const или var
Какая между ними разница?

2024-09-05 06:30 UTC, mafin1799 commented on source/solve.js
> +    try {
Как работает try/catch?

2024-09-05 06:30 UTC, mafin1799 commented on source/solve.js
> +        const result = eval(formula)
eval классно
Но стоит проверять регулярками что там передается
Он же просто выполняет какой то код

И если передать туда alert, fetch и тд то нет ничего что бы предотвратило их выполнение

2024-09-05 18:37 UTC, nonrep commented on source/solve.js
> +function solve(formula, value) {
еще есть Function Expression и стрелочные функции. Использую Function Declaration, т.к. функцию нельзя сократить до одной строчки и функция не используется единожды, чтобы использовать Function Expression.

'use strict' используется для включения строгого режима, он защищает от использования неинициализированных переменных и многое другое. Подключается автоматически, если код состоит из классов и модулей

2024-09-05 18:37 UTC, nonrep commented on source/solve.js
> +        let x = value
var является устаревшим, вместо него принято использовать let. const используется, чтобы указать, что значение не должно изменяться, и ловить ошибки, если была попытка изменения

2024-09-05 18:39 UTC, nonrep commented on source/solve.js
> +    try {
если в блоке try произошла ошибка - управление передается catch

2024-09-05 19:29 UTC, nonrep commented on source/solve.js
> +        const result = eval(formula)
сделал валидацию

2024-09-06 04:17 UTC, mafin1799 commented on source/solve.js
> +function solve(formula, value) {
А какая разница между этими тремя типами функций.
Нужно перечислить конкретные различия

2024-09-06 04:19 UTC, mafin1799 commented on source/solve.js
> +        let x = value
Про const не совсем понял.
Там всегда про значения.

https://learn.javascript.ru/let-const

2024-09-06 04:21 UTC, mafin1799 commented on source/solve.js
> +        let x = value
И давай будем проверять что value это число)

Чтобы туда не проскочил какой-нибудь объект.

2024-09-06 04:23 UTC, mafin1799 commented on source/solve.js
> +function solve(formula, value) {
И почему бы тут не заиспользовать стрелочную функцию?

2024-09-06 04:24 UTC, mafin1799 commented
Добавил еще вопросов.
Нужно сделать валидацию входных параметров.

2024-09-06 09:10 UTC, nonrep commented on source/solve.js
> +function solve(formula, value) {
Function Declaration можно вызывать до объявления, Function Expression можно вызывать только после объявления. У стрелочных функций нет this, его значение берется снаружи.

Я не использую стрелочную функцию, т.к. функцию нельзя сократить до одной строчки и мне не нужно сохранения this для родительской функции

2024-09-06 09:31 UTC, nonrep commented on source/solve.js
> +        let x = value
добавил проверку типа данных (переименовал value на x, чтобы убрать лишнее действие)
if (typeof x !== 'number') {
        return null;
    }

2024-09-07 03:28 UTC, mafin1799 commented on source/solve.js
> +function solve(formula, value) {
Ну раз тебе не нужен this 
То тут смело можно использовать стрелочные функции они более модные и современные

2024-09-07 03:28 UTC, mafin1799 commented on source/solve.js
> +function solve(formula, value) {
И какое еще есть отличие у стрелочной функции

2024-09-07 03:30 UTC, mafin1799 commented on source/solve.js
> +function solve(formula, value) {
А формула это строка
Договорились где то проверять регулярками

А что будет если туда передать строку через конструктор

New String('x * x')

Давай добавим это в тесты
Убедимся что ничего не падает
А если падает то потюним проверки

2024-09-07 03:31 UTC, mafin1799 commented on source/solve.js
> +        let x = value
А если число к тебе придет через new Number(4) то эта проверка не прокатит

2024-09-07 03:33 UTC, mafin1799 commented on source/solve.js
> +        let x = value
И что будет если числа очень большие?

Какой диапазон у чисел в js и что будет если выйти за его пределы

2024-09-07 03:37 UTC, mafin1799 commented on source/solve.js
> +    try {
А какой еще есть блок в try catch в js и зачем он нужен?

А можно ли сюда добавить какой нибудь throw new Error?

https://learn.javascript.ru/exception?ysclid=m0rld9ebv131535232

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

2024-09-07 03:37 UTC, mafin1799 commented on source/solve.js
> +    try {
А как перехватить вообще все ошибки на страничке?

2024-09-07 03:38 UTC, mafin1799 commented
Еще порция вопросов
+ не заметил JsDoc комментарии 
Их стоит добавить

2024-09-07 13:00 UTC, nonrep commented on source/solve.js
> +        let x = value
если число чем 1.8 ** 308 , то результат будет Infinity
  если число чем 5 * 10 ** (-324) , то результат будет 0

2024-09-07 14:22 UTC, nonrep commented on source/solve.js
> +    try {
А какой еще есть блок в try catch в js и зачем он нужен?
в try catch есть блок finally, он выполняется независимо от того, было ли исключение. 

А можно ли сюда добавить какой нибудь throw new Error?
Добавил несколько вызовов исключений с различными комментариями ошибки

А как перехватить вообще все ошибки на страничке?
Для этого можно использовать глобальный обработчик ошибок window.onerror

2024-09-07 14:32 UTC, nonrep commented on source/solve.js
> +function solve(formula, value) {
Заменил на стрелочную функцию

2024-09-07 16:04 UTC, mafin1799 commented on source/solve.js
> +function solve(formula, value) {
Еще у нее нет arguments

2024-09-07 16:08 UTC, mafin1799 commented on source/solve.js
> +    try {
Отлично

По ошибкам можно подобрать еще конструкторы. Чтобы ошибка была интереснее

Посмотри всякие RangeError и тд

2024-09-07 19:57 UTC, nonrep commented on source/solve.js
> +    try {
Добавил разные классы ошибок и JSDoc комментарии

2024-09-08 12:02 UTC, mafin1799 approved these changes

2024-09-08 18:53 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 18:53 UTC, DPeshkoff commented on source/solve.js
> +}
Не теряй перенос в конце файла

2024-09-08 18:53 UTC, DPeshkoff commented on source/solve.js
> +    if (x === Infinity || x === -Infinity) {
А можем как-то методом проверить? Сто процентов в Number что-то есть - давай найдем)

2024-09-08 18:53 UTC, DPeshkoff commented on source/solve.js
> +    if (formula instanceof String) {
А если мы туда массив засунем? Не вижу пока препятствий

2024-09-09 08:30 UTC, nonrep commented on source/solve.js
> +}
добавил

2024-09-09 08:31 UTC, nonrep commented on source/solve.js
> +    if (x === Infinity || x === -Infinity) {
сделал проверку через метод isFinite

2024-09-10 21:11 UTC, DPeshkoff approved these changes

2024-09-10 21:12 UTC, closed without merging