Станислав Кригер
frontend-park-mail-ru/homework_2024_2 pull request #24
Opened 2024-09-03 20:56 UTC by MoyStasik

Вариант-8. Напишите функцию sort, которая будет сортировать буквы в словах по алфавиту, а потом получившиеся слова в предложении — тоже. Первую букву каждого слова она сделает прописной, остальные — строчными

2024-09-05 13:06 UTC, Shureks-den commented
Привет! Поздравляю с поступлением на курс фронтенда! Меня зовут Саша и я буду смотреть твой мр. По всем срочным вопросам можешь писать в тг https://t.me/alexklonov

2024-09-05 13:07 UTC, Shureks-den commented on index.html
>  <script src="source/max.js"></script>
Давай уберем этот код для примера

2024-09-05 13:07 UTC, Shureks-den commented on source/sort.js
> +'use strict';
Первый вопрос - для чего нужна эта строка?

2024-09-05 13:08 UTC, Shureks-den commented on source/sort.js
> +*/
Очень круто, что заюзал JSDoc, ты пока первый, кто его сразу прикрутил)

2024-09-05 13:10 UTC, Shureks-den commented on source/sort.js
> +const sort = function (str){
Тут сразу два вопроса и один-спойлер предложение:

1) Как помимо `const` можно объявить переменные и в каких случаях лучше их использовать
2) Какие способы объявлений функций ты знаешь и чем они отличаются

Давай везде использовать стрелочные функции

2024-09-05 13:10 UTC, Shureks-den commented on source/sort.js
> +    if (typeof(str) != 'string') throw new RuntimeError('Некорректные данные');
Давай по код стайлу всегда использовать {} для if, даже если там одна строка

2024-09-05 13:12 UTC, Shureks-den commented on source/sort.js
> +    let arrayOfStrings = str.split(' ');
К вопросу о типах переменных, тут можно `const`, а почему расскажешь ты) Почитай о типах данных и как они хранятся в памяти

2024-09-05 13:13 UTC, Shureks-den commented on source/sort.js
> +    arrayOfStrings.forEach(function(item, i, arrayOfStrings){
Давай во всех похожих методах использовать стрелочную функцию, как у тебя в sort

2024-09-05 13:14 UTC, Shureks-den commented on source/sort.js
> +    arrayOfStrings.sort((a, b) => a.localeCompare(b));
Еще мне кажется не очень удачным использование forEach где ты перезаписываешь исходный массив. Вариант попроще - использовать `.map`. Наилучший вариант - использовать `.reduce`

2024-09-06 06:45 UTC, MoyStasik commented on source/sort.js
> +'use strict';
Эта строковое выражение, добавленное в ECMAScript 5 (ES5), которое включает строгий режим, он нужен, чтобы предотвращать ошибки в коде.

2024-09-06 07:19 UTC, MoyStasik commented on source/sort.js
> +const sort = function (str){
1. существует 3 типа объявления переменных: var, let, const.
    let - используется для создания переменной
    var - аналог ключевого слова let, но более устаревший вариант объявления переменной
    const - создание переменной, значение которой в процессе программы изменяться не будет, иначе это приведет к ошибке.

Сейчас в коде var лучше не использовать, потому что он позволяет создавать ряд путаниц, таких как повторное создание переменной и для var не существует блочной области видимости

2024-09-06 08:13 UTC, MoyStasik commented on source/sort.js
> +const sort = function (str){
2. Первый способ объявления функции - это function declaration
<img width="804" alt="image" src="https://github.com/user-attachments/assets/a255806a-926c-4ead-854c-f66a13e45ba0">
 Второй способ - это function expression, когда мы функцию приравниваем какой-то переменной, в этом случае название функции можем опустить.
<img width="801" alt="image" src="https://github.com/user-attachments/assets/d7ba2765-cbb1-44b0-b4e0-32fcb8069b83">
 Третий способ - это стрелочные функции и выглядит следующим образом. 
<img width="801" alt="image" src="https://github.com/user-attachments/assets/470617f6-a466-4d9e-beca-d25ef6f19563">
Это создаёт функцию func, которая принимает аргументы arg1..argN, затем вычисляет expression в правой части с их использованием и возвращает результат.
У стрелочных функций нет this, если происходит обращение к this, то его значение берется снаружи. Из-за отсутствия this стрелочные функции не могут использоваться как конструкторы, поэтому не могут быть вызваны с new.
У стрелочных функций также нет переменной arguments. 
Стрелочные функции предназначены для небольшого кода, который не имеет своего «контекста», выполняясь в текущем.

2024-09-06 09:20 UTC, MoyStasik commented on source/sort.js
> +    let arrayOfStrings = str.split(' ');
Лучше использовать const, чтобы нельзя было изменить объект, во избежание ошибок.
Переменная для хранения массива находится в куче.

2024-09-06 14:47 UTC, MoyStasik commented on index.html
>  <script src="source/max.js"></script>
Убрал.

2024-09-06 14:48 UTC, MoyStasik commented on index.html
>  <script src="tests/max.js"></script>
Убрал.

2024-09-06 14:48 UTC, MoyStasik commented on source/sort.js
> +    if (typeof(str) != 'string') throw new RuntimeError('Некорректные данные');
Исправил.

2024-09-06 14:48 UTC, MoyStasik commented on source/sort.js
> +    arrayOfStrings.forEach(function(item, i, arrayOfStrings){
Сделал.

2024-09-06 14:48 UTC, MoyStasik commented on source/sort.js
> +    arrayOfStrings.sort((a, b) => a.localeCompare(b));
Исправил.

2024-09-06 17:07 UTC, Shureks-den requested changes

2024-09-06 17:07 UTC, Shureks-den commented on index.html
> -<script src="tests/sort.js"></script>
Чет ты тут погорячился) нужно оставить импорт своего кода, нужно только max убрать. И добавь скринов прохода тестов

2024-09-06 17:07 UTC, Shureks-den commented on source/sort.js
> +    const result = arrayOfStrings.reduce( (result_array_string, item) => {
Отступ не нужен у  скобок и давай везде camelCase юзать. `((res, cur) => {`

2024-09-06 17:07 UTC, Shureks-den commented on source/sort.js
> +        if (item){
Добавь плз пробел после ()

2024-09-06 18:19 UTC, MoyStasik commented on index.html
> -<script src="tests/sort.js"></script>
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/c8fb9887-1b98-412a-bca9-c5540a7fcc5c">

2024-09-06 18:22 UTC, MoyStasik commented on source/sort.js
> +        if (item){
Сделал.

2024-09-06 18:22 UTC, MoyStasik commented on source/sort.js
> +    const result = arrayOfStrings.reduce( (result_array_string, item) => {
Исправил

2024-09-08 18:58 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 18:58 UTC, DPeshkoff commented on index.html
> -<script src="source/max.js"></script>
Давай не будем убирать старый код и вернем как было

2024-09-08 18:58 UTC, DPeshkoff commented on source/sort.js
> +'use strict';
Какие именно? Чем отличается строгий от нестрогого?

2024-09-08 18:58 UTC, DPeshkoff commented on source/sort.js
> +    if (typeof(str) != 'string'){
Не пройдем

<img width="233" alt="Снимок экрана 2024-09-04 в 18 32 35" src="https://github.com/user-attachments/assets/9f789f48-56fd-44a1-8855-a092190cb65c">

2024-09-08 18:58 UTC, DPeshkoff commented on tests/sort.js
> +
Давай еще напишем тесты на некорректный ввод

2024-09-08 20:13 UTC, MoyStasik commented on source/sort.js
> +'use strict';
Если включить строгий режим, то при попытки необъявленной переменной сохранить значение, он выдаст ошибку 
<img width="405" alt="image" src="https://github.com/user-attachments/assets/cb506e06-0d75-433d-80e4-6b58f421735a">
<img width="77" alt="image" src="https://github.com/user-attachments/assets/e86b71c3-bb16-4ccd-aab3-f3b95d03caef">
В строгом режиме присваивание NaN значения выбрасывает исключение.
Строгий режим требует, чтобы имена аргументов в объявлении функций встречались только один раз, иначе тоже будет ошибка.

2024-09-08 20:15 UTC, MoyStasik commented on source/sort.js
> +'use strict';
В обычном режиме синтаксические правила языка не так строги, а когда происходят некоторые ошибки об этом не оповещает

2024-09-08 20:16 UTC, MoyStasik commented on index.html
> -<script src="source/max.js"></script>
Вернул

2024-09-08 21:06 UTC, MoyStasik commented on source/sort.js
> +    if (typeof(str) != 'string'){
исправил

2024-09-08 21:06 UTC, MoyStasik commented on tests/sort.js
> +
добавил тесты

2024-09-11 20:51 UTC, DPeshkoff approved these changes

2024-09-11 20:51 UTC, closed without merging