Бочарова Татьяна В3
frontend-park-mail-ru/homework_2024_2 pull request #25
Opened 2024-09-03 21:12 UTC by bocharovatd

2024-09-04 12:56 UTC, F4lkr4m commented
Привет! Меня зовут Сережа, я ментор по фронтенду и буду проверять у тебя ДЗ №0. К твоему решению я задам несколько вопросов и оставлю комментарии) Как поправишь замечания можешь смело меня пинговать в личку (https://t.me/Falkr4m), так мы сможем ускорить процесс проверки.

![image](https://github.com/user-attachments/assets/7501a34d-5478-4200-8781-f4324fa735ec)

2024-09-04 12:57 UTC, F4lkr4m commented
Сразу давай поменяем название Пулл Реквеста - убери "В3", будет достаточно лишь фамилии и имени

2024-09-04 13:15 UTC, F4lkr4m requested changes
Хорошее решение получилось, жду поправок и как сделаешь смело пингуй меня

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +        if (Number(numberOrNumeral) > 0 && numberOrNumeral % 1 === 0) {
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger - я думаю это тебе больше тут подойдет)

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +        if (typeof numberOrNumeral === 'string') {
А если передать строку 'kekw'?

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +    throw new Error('Неверный тип данных');
Молодец, что обрабатываешь ошибку, предлагаю улучшение - выбрасывать уже определенный тип ошибки из Js - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +    const arabicRomanMap = {
А чем arabicRomanMap отличается от romanArabicMap?

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +    if (!/^[IVXLCDM]+$/.test(romanNumeral)) {
Предлагаю это вынести на уровень выше, функция получает уже корректные данные на вход

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +    if (!/^[IVXLCDM]+$/.test(romanNumeral)) {
Также предлагаю регулярку вынести в константу, чтобы было понятно, что она проверяет

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +    return [...romanNumeral].reduce(
Классно, что используешь reduce! 
Можно было не раскрывать спредом, reduce возвращает результат и не мутирует массив

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +        (result, currentSymbol, i, arrRomanNumeral) => {
Предлагаю arrRomanNumeral не доставать здесь, а использовать romanNumeral

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +            return result + (romanArabicMap[currentSymbol] < romanArabicMap[nextSymbol] ?
Очень тут сложночитаемая логика в тернарнике, давай как нибудь по красивше переделаем

2024-09-04 13:15 UTC, F4lkr4m commented on source/roman.js
> +                arabicNumber -= arabicValue;
Мутация входных параметров, давай соблюдать чистоту функций и создадим копию входного параметра.

2024-09-04 13:15 UTC, F4lkr4m commented on tests/roman.js
> +    QUnit.test('roman выдает ошибку при передаче невалидного типа данных', function (assert) {
Здорово, что добавила свои тесты! 

Давай ток тут как нибудь порефакторим, очень много повторений здесь.

2024-09-04 19:48 UTC, bocharovatd commented on .idea/.gitignore
Папку .idea убрала

2024-09-04 20:05 UTC, bocharovatd commented on source/roman.js
> +'use strict';
Стандарт ECMAScript 5, в отличие от всех используемых до него, внес измения в функциональность JS. По умолчанию эти изменения в языке не применяются, чтобы не было проблем с поддержанием старого кода. Но директива 'use strict' позволяет их активировать. Она необходима, чтобы предупреждать об ошибках при использовании небезопасных конструкций и о наличии слов, которые могут быть стать ключевыми в будущем.

2024-09-04 21:43 UTC, bocharovatd commented on source/roman.js
> +function roman(numberOrNumeral) {
1. Добавила описание функций в JSDoc.
2. Также можно создавать стрелочные функции
### Стрелочные функции
#### Особенности
- имеют более компактный синтаксис
- не имеют собственного контектса this
#### Синтаксис
```
let func = (arg1, arg2, ..., argn) => {
   return expression;
};
let func = (arg1, arg2, ..., argn) => expression;
```
#### Пример использования
```
let sum = (a, b) => {
    return a + b;
};
let sum = (a, b) => a + b;
```

2024-09-04 21:46 UTC, bocharovatd commented on source/roman.js
> +        if (typeof numberOrNumeral === 'string') {
В этом случае выпадет ошибка 'Неверный формат римского числа',  т.к. пользователь, желая подать на вход римское число, может ошибиться в наборе символов римского числа. Добавила пример в тесты

2024-09-05 09:09 UTC, F4lkr4m requested changes

2024-09-05 09:09 UTC, F4lkr4m commented on source/roman.js
> +        throw new TypeError('Неверный формат римского числа');
Давай проверку входных данных поднимем на уровень выше в функцию `roman`. Так будет более правильно, что у тебя функция `roman` она валидирует входные данные, а уже правильные данные отдает либо в одну, либо в другую функцию

2024-09-05 09:09 UTC, F4lkr4m commented on source/roman.js
> + * @return {string|number} - converted Roman numeral
Почему строку или число? Разве не просто число?

2024-09-05 09:09 UTC, F4lkr4m commented on source/roman.js
> +function roman(numberOrNumeral) {
Давай еще все функции поменяем на модные стрелочные)

2024-09-05 09:09 UTC, F4lkr4m commented on source/roman.js
> +    if (!/^[IVXLCDM]+$/.test(copiedRomanNumeral)) {
Давай регулярку вынесем в константу и обзовем, что она проверяет

2024-09-05 18:44 UTC, bocharovatd commented on source/roman.js
> + * @return {string|number} - converted Roman numeral
В функцию arabicToRoman могло быть передано число в виде строки, но при вычитании (copiedArabicNumber -= arabicValue) тип приводился к number. Изменила эту логику и теперь в arabicToRoman подаю только number. В  JSDoc поправила.

2024-09-05 21:12 UTC, F4lkr4m commented on source/roman.js
> +    let copiedRomanNumeral = romanNumeral.toUpperCase();
Тут можно const, переменная не меняется у тебя

2024-09-05 21:17 UTC, F4lkr4m requested changes

2024-09-05 21:17 UTC, F4lkr4m commented on source/roman.js
> +    return [...copiedRomanNumeral].reduce((result, currentSymbol, i) => {
можно здесь массив не копировать, reduce его не мутирует, а лишь возвращает результат
просто `romanNumeral.reduce(...)`

2024-09-05 21:29 UTC, F4lkr4m commented on source/roman.js
> +    return [...copiedRomanNumeral].reduce((result, currentSymbol, i) => {
Да, тут же достаем символы строки, извиняюсь

2024-09-05 21:37 UTC, F4lkr4m approved these changes
lgtm

2024-09-08 19:00 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 19:00 UTC, DPeshkoff commented on tests/roman.js
> -
Предлагаю не изменять старый кодстайл - лишние изменения в ПР, да и в чужой монастырь со своим кодстайлом как-то не очень)

2024-09-11 08:38 UTC, bocharovatd commented on source/roman.js
> +    if (typeof numberOrNumeral === 'number' || typeof numberOrNumeral === 'string') {
Внесла изменения

2024-09-11 08:38 UTC, bocharovatd commented on tests/roman.js
> -
Внесла изменения

2024-09-11 20:48 UTC, DPeshkoff approved these changes

2024-09-11 20:48 UTC, closed without merging