Variant 14 Амбарцумова Екатерина
frontend-park-mail-ru/homework_2024_2 pull request #26
Opened 2024-09-04 10:50 UTC by kataamb

Амбарцумова Екатерина

2024-09-05 08:05 UTC, AlexandraSmirnova commented
Привет, Катя! Меня зовут Саша. Поздравляю с переходом на 2-ой семестр. Я твой ментор по ДЗ0 и уже скоро приступлю к проверке. Если будут вопросы - мой ник в телеге @alexandrius23

2024-09-06 05:25 UTC, kataamb commented
Спасибо!

2024-09-06 09:56 UTC, AlexandraSmirnova requested changes
Привет, отличная реализация!) есть несколько небольших комментариев

2024-09-06 09:56 UTC, AlexandraSmirnova commented on source/set.js
> +const changeNestedProperty = (object, propertyList, newProperty) =>
Давай добавим  jsdoc к этой функции

2024-09-06 09:56 UTC, AlexandraSmirnova commented on source/set.js
> +            if (propertyList.length == 0)
Лучше использовать строгое сравнение и в данном случае сравнение можно убрать, подумай как)

2024-09-06 09:56 UTC, AlexandraSmirnova commented on source/set.js
> +    let propertyList = (path.split(".")).slice(1);
лишние скобки

2024-09-06 09:56 UTC, AlexandraSmirnova commented on source/set.js
> +'use strict';
Расскажи, для чего нужна эта строка

2024-09-06 09:56 UTC, AlexandraSmirnova commented on source/set.js
> +    let propertyList = (path.split(".")).slice(1);
Давай добавим проверку для path. При каких значения path эта строка не сработает?

2024-09-06 09:56 UTC, AlexandraSmirnova commented on source/set.js
> +    let newObject = changeNestedProperty(object, propertyList, newProperty);
можно не создавать тут переменную, а сразу возвратить результат функции

2024-09-09 05:27 UTC, kataamb commented on source/set.js
> +'use strict';
'use strict' - этто директива, ее подключаем, чтобы активировать стандарт ECMAScript 5;  как я поняла, в этом стандарте появились новые возможности в языке и некоторые ограничения стали строже (для лучше читаемости кода в том числе), например, обязательно указывать перед переменными const/let, точку с запятой ставить в конце каждого выражения

2024-09-09 05:29 UTC, kataamb commented on source/set.js
> +    let propertyList = (path.split(".")).slice(1);
Поправила, но не совсем уверена, что я правильно поняла: попробовала случай, когда у нас в path отсутствует первая точка, и тогда первое свойство "отлетает", мы используем только последующие. Поэтому проверяю, что есть первая точка, иначе не изменяю объект, просто возвращаю его в исходном виде)

2024-09-09 05:29 UTC, kataamb commented on source/set.js
> +    let newObject = changeNestedProperty(object, propertyList, newProperty);
Поправила)

2024-09-09 05:30 UTC, kataamb commented on source/set.js
> +            if (propertyList.length == 0)
Поправила, теперь проверяю, что !(propertyList.length )

2024-09-09 05:30 UTC, kataamb commented on source/set.js
> +    let propertyList = (path.split(".")).slice(1);
Поправила)

2024-09-09 05:36 UTC, kataamb commented
Также добавила JSDoc к вспомогательной функции

2024-09-09 09:20 UTC, AlexandraSmirnova requested changes

2024-09-09 09:20 UTC, AlexandraSmirnova commented on source/set.js
> +            if ( !( propertyList.length ) )
тут лишние скобки внутри

2024-09-09 09:20 UTC, AlexandraSmirnova commented on source/set.js
> +            if ( !( propertyList[0] in object ) )
Тут лучше использовать  метод hasOwnProperty и тогда скобки тоже можно будет убрать

2024-09-09 09:20 UTC, AlexandraSmirnova commented on source/set.js
> +    if ( path[0] !== "." )
А что будет если тут передать пустой path или не строку? можно кстати добавить тест на это

2024-09-09 09:20 UTC, AlexandraSmirnova commented on source/set.js
> +    if ( path[0] !== "." )
По поводу двойных кавычек, лучше выбрать и придерживаться единого стиля кода. Поэтому или везде "" или везде ''
Рекомендую статью к ознакомлению: https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2024-09-09 09:20 UTC, AlexandraSmirnova commented on source/set.js
> + * @returns {Object} Returns modified object
Опиши, пожалуйста, какие здесь параметры принимает функция

2024-09-09 09:20 UTC, AlexandraSmirnova commented on source/set.js
> +const set = (object, path, newProperty) =>
Здесь тоже давай добавим jsdoc

2024-09-09 09:23 UTC, AlexandraSmirnova commented on source/set.js
> +    let propertyList = (path.split(".")).slice(1);
Отлично что добавила эту проверку, далее добавила еще комент о проверке, как проверку этого параметра можно докрутить

2024-09-10 12:42 UTC, kataamb commented on source/set.js
> +    if ( path[0] !== "." )
Поправила

2024-09-10 12:45 UTC, kataamb commented on source/set.js
> +    if ( path[0] !== "." )
Я теперь проверяю, что  есди
1) переданный объект - не строка, или
2) строка пустая или
3) вначале строки нет ".", то путь некорректен, и я возвращаю исходный объект

2024-09-10 12:50 UTC, kataamb commented on source/set.js
> +const set = (object, path, newProperty) =>
Добавила, здесь аналогично для параметра newProperty: добавила все основные типы данных

2024-09-11 12:48 UTC, AlexandraSmirnova requested changes

2024-09-11 12:48 UTC, AlexandraSmirnova commented on source/set.js
> + * @returns {Object} Returns modified object
Отлично, что знаешь основные типы данных) По поводу jsdoc, то для таких случаев можно писать {*} , что означает: любой тип данных

2024-09-11 12:48 UTC, AlexandraSmirnova commented on source/set.js
> + *          |Number[]|String[]|BigInt[]|Boolean[]|Object[]|Symbol[]} newProperty - instance of any type: number, string, etc.
Тут тоже давай укажем, что любой тип данных

2024-09-11 12:48 UTC, AlexandraSmirnova commented on source/set.js
> +    let newObject = changeNestedProperty(object, propertyList, newProperty);
тут не поменялось, давай не создавать переменную newObject

2024-09-11 12:48 UTC, AlexandraSmirnova commented on tests/set.js
> +	QUnit.test('set работает правильно c объектами со свойством null', function (assert) {
Тут момент по единому стилю кода. Если в тестах перед скобками `{` нет переносов на новую строку, давай и в set.js тоже так сделаем для одинаковости

2024-09-11 18:43 UTC, kataamb commented on source/set.js
> + *          |Number[]|String[]|BigInt[]|Boolean[]|Object[]|Symbol[]} newProperty - instance of any type: number, string, etc.
О, спасибо большое)) А то я вчера намучилась эти типы вбивать)

2024-09-11 18:43 UTC, kataamb commented on tests/set.js
> +	QUnit.test('set работает правильно c объектами со свойством null', function (assert) {
Тоже изменила)

2024-09-11 18:46 UTC, kataamb commented
Поправила '{' в source/set.js, убрала newObject - сразу возвращаю объект, который в рез-тате рекурсивного вызова получается, в jsdoc'е изменила тип на *

2024-09-12 19:23 UTC, kataamb commented on source/set.js
> +    let propertyList = path.split('.').slice(1);
Есть переменные и константы - переменные, которые нельзя изменять. Обычные переменные можно объявлять с помощью ключевых слов `let` и `var`,  `var` - более устаревшая форма объявления переменной.
Константы объявляют с помощью ключевого слова `const`, их нельзя изменять - это приведет к ошибке TypeError. 
Если какие-то переменные не нужно изменять, их лучше объявлять через  `const`

2024-09-12 19:24 UTC, kataamb commented on source/set.js
> +    let propertyList = path.split('.').slice(1);
Я поэтому у себя тоже поправила этот момент, массив `path` не нужно ведь изменять

2024-09-12 19:32 UTC, kataamb commented on source/set.js
> +    let propertyList = path.split('.').slice(1);
Кстати, с объектами немного интереснее момент с `const` и `let`. Даже если объявить объект с `const`, его поля можно будет изменять, потому что на самом деле это будет ссылка на объект;  нельзя только будет конкретно переменной с `const` (т.е., ссылке на этот объект) присвоить другое значение

2024-09-14 10:30 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-14 10:30 UTC, DPeshkoff commented on source/set.js
> +    if (typeof path !== 'string' || !path.length || path[0] !== '.') {
сломаем(

<img width="253" alt="Снимок экрана 2024-09-14 в 13 29 11" src="https://github.com/user-attachments/assets/a5de73cb-09ab-4e62-adf4-1c62b0f6192b">

2024-09-14 10:30 UTC, DPeshkoff commented on source/set.js
> +const set = (object, path, newProperty) => {
А чем стрелочные функции отличаются от обычных?

2024-09-15 15:53 UTC, kataamb commented on source/set.js
> +    if (typeof path !== 'string' || !path.length || path[0] !== '.') {
Поправила, теперь проверяю с помощью оператора instanceof - можно определить, является ли объект определенного класса

2024-09-15 15:58 UTC, kataamb commented on source/set.js
> +    if (typeof path !== 'string' || !path.length || path[0] !== '.') {
Скобки в `!(path instanceof String)` для переопределения приоритета поставила: у оператора `instanceof` меньше приоритет, чем у оператора `!`

2024-09-15 16:42 UTC, kataamb commented on source/set.js
> +const set = (object, path, newProperty) => {
Как я понимаю, у стрелочных функций более короткий синтаксис (особенно однострочных) + с помощью этих функций удобно работать с объектами классов: у стрелочных функций нет this, и если происходит обращение к this, его значение берётся снаружи, и это удобно для доступа к атрибутам объекта (втутри метода), как следствие, не могут быть использованы как конструкторы, не могут быть вызваны с new

2024-09-16 16:34 UTC, Sarafa2n commented on source/set.js
> +    object[propertyList[0]] = changeNestedProperty(object[propertyList[0]], propertyList.slice(1), newProperty);
propertyList[0] в отдельную переменку

2024-09-16 17:05 UTC, kataamb commented on source/set.js
> +    object[propertyList[0]] = changeNestedProperty(object[propertyList[0]], propertyList.slice(1), newProperty);
Поправила)

2024-09-16 17:28 UTC, closed without merging