added tree function by Polina Tikunova
frontend-park-mail-ru/homework_2024_2 pull request #28
Opened 2024-09-04 17:50 UTC by PtFux

Создана функция отрисовки дерева.
Полина Тикунова, студентка 2 семестра, 6 вариант

2024-09-05 10:54 UTC, ValdimirDenisov commented
Привет! Поздравляю тебя с переходом на второй семестр!)
Меня зовут Вова, я буду проверять твое ДЗ №0. Если возникнут любые вопросы, можешь смело писать мне в [телегу](https://t.me/Alfredodanger).

2024-09-07 17:47 UTC, PtFux commented
Привет! Спасибо
Вроде всё исправила

2024-09-08 18:00 UTC, ValdimirDenisov commented on source/tree.js
> +      if (i === a - 1) {
Присмотрись, у тебя в теле условия и исключения есть строки которые дублируются, хоть это не совсем очевидно

2024-09-09 12:43 UTC, PtFux commented on source/tree.js
> +'use strict';
Костыль для поддержки легаси кода. Если эту директиву не написать, устаревшие код с кучей всякого, сможет исполняться. А с ней - нет, потому что более строгие правила

2024-09-09 16:23 UTC, PtFux commented on source/tree.js
> +function tree(a) {
Декларативное (как у меня), стрелочное (как в макс) и через функциональное выражение. Последним способом еще анонимные делают

2024-09-09 16:33 UTC, PtFux commented on source/tree.js
> +    let result = "";
Примитивные:
Числовые -'number', 'BigInt'
Строки - 'string'
Булевый - 'boolean'
нулевое - 'null' и неопределенный - 'undefined '
'symbol' - тип данных, используемых в объектах как идентификатор

Тип объект - 'object ' - сложные структуры, в том числе самописные

2024-09-12 13:40 UTC, Sarafa2n commented on source/tree.js
> +}
нет в конце файла пустой строки, не очень хорошая практика, даже гитхаб показывает

2024-09-12 13:40 UTC, Sarafa2n commented on source/tree.js
> +      throw new RangeError('The height must be greater than 3');
а почему вот тут скобочки

2024-09-12 15:29 UTC, PtFux commented on source/tree.js
> +      throw new RangeError('The height must be greater than 3');
что имеется ввиду?

2024-09-12 15:58 UTC, Sarafa2n commented on source/tree.js
> +      throw new RangeError('The height must be greater than 3');
у тебя сверху if в одну строку с {}, а тут нет, давай стараться писать в одном стиле

2024-09-12 15:59 UTC, Sarafa2n commented on source/tree.js
> +    if ( !( (typeof height === 'number') || (typeof height == 'string')) ) {
А если new Number или new String прокинуть

2024-09-13 06:47 UTC, DPeshkoff requested changes

2024-09-13 06:47 UTC, DPeshkoff commented on source/tree.js
> +function tree(height) {
А почему не стрелочная? Чем они отличаются от обычных?

2024-09-13 06:47 UTC, DPeshkoff commented on source/tree.js
> +  if (!((typeof height === 'number') || (typeof height == 'string'))
во втором случае у тебя нестрогая проверка - так лучше не делать, лучше строгие)

2024-09-13 07:38 UTC, PtFux commented on source/tree.js
> +function tree(height) {
Стрелочные функции не создают собственный контекст this. Также они, обычно, краткие и имеют неявный возврат значений. Эта функция достаточно сложная, гораздо удобнее использовать здесь обычную

2024-09-13 07:40 UTC, PtFux commented on source/tree.js
> +  if (!((typeof height === 'number') || (typeof height == 'string'))
Исправила! Проверьте, пожалуйста, очень небольшое изменение @DPeshkoff 🙏

2024-09-13 07:59 UTC, DPeshkoff approved these changes

2024-09-13 07:59 UTC, closed without merging