Variant 3
frontend-park-mail-ru/homework_2024_2 pull request #29
Opened 2024-09-04 19:56 UTC by KhovenOlya

2024-09-05 17:12 UTC, F4lkr4m commented
Привет! Меня зовут Сережа, я ментор по фронтенду и буду проверять у тебя ДЗ №0. К твоему решению я задам несколько вопросов и оставлю комментарии) Как поправишь замечания можешь смело меня пинговать в личку (https://t.me/Falkr4m), так мы сможем ускорить процесс проверки.

![image](https://github.com/user-attachments/assets/945e1f34-30bd-4224-b3cf-9204febf91a0)

2024-09-05 17:31 UTC, F4lkr4m requested changes
Неплохое решение получилось, давай его доработаем!
Как поправишь комменты - смело пингуй меня в тг

2024-09-05 17:31 UTC, F4lkr4m commented on source/roman.js
> +//Ховен Ольга, WEB-22
Эти комменты тут не надо, мы и так знаем кто и где)

2024-09-05 17:31 UTC, F4lkr4m commented on source/roman.js
> +'use strict'
Подскажи, для чего нужна эта директива?

2024-09-05 17:31 UTC, F4lkr4m commented on source/roman.js
> +function roman (num) {
Здесь ты инициализируешь функцию через ключевое слово `function`, подскажи, как можно еще задавать функцию в js? И чем эти способы отличаются?

2024-09-05 17:31 UTC, F4lkr4m commented on source/roman.js
> +    throw new Error('Ввод должен быть числом или строкой, представляющей число');
C код стайлом есть нюансы, а давай:
- выберем отступ - это 2 или 4 пробела и везде придерживаться одного
- будет делать пробелы между операторами например `) {` или `i < romRadix.length`

2024-09-05 18:59 UTC, KhovenOlya commented on source/roman.js
> +    throw new Error('Ввод должен быть числом или строкой, представляющей число');
У меня здесь стоит табуляция. Мне ее нужно поменять на 2 и 4 пробела?

2024-09-06 13:22 UTC, KhovenOlya commented on source/roman.js
> +'use strict'
Это строгий режим. В этом режиме применяются более строгие правила, которые помогают предотвратить большинство ошибок

2024-09-06 13:29 UTC, KhovenOlya commented on source/roman.js
> +function roman (num) {
Функцию еще можно задать как стрелочную функцию или Function Expression. Function Expression имеет отличительные особенности, что она задается внутри выражения с помощью присваивания. Function Declaration просто задается отдельной конструкцией, как это сделала я. А стрелочная, похожа на Function Expression, но задается более лаконично через '=>', опуская слово function

2024-09-06 13:49 UTC, F4lkr4m commented on source/roman.js
> +'use strict'
А что конкретно за ошибки? И в чем строгость правил?)

2024-09-06 13:50 UTC, F4lkr4m commented on source/roman.js
> +function roman (num) {
Да, действительно, они отличаются синтаксисом, но не только им. Какие еще есть различия от обычного function declaration? И давай перепишем эту функцию на модный стрелочный синтаксис)

2024-09-06 13:58 UTC, F4lkr4m requested changes

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +    const romanRadix = {
Давай эту константу вынесем за пределы функции

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +    if (typeof input === 'string') {
Предлагаю улучшение - давай создадим две функции дополнительные - одна будет конвертить арабские в римские, а другая наоборот

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +            throw new Error('Строку не удалось преобразовать в число');
Ну это тоже по идее TypeError)

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> + * @returns {string|number} - Возвращает римское число (строка) при вводе арабского числа, или арабское число (число) при вводе римского числа.
Забыла про параметр `@throws `

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +        input = input.trim().toUpperCase();
Не меняем входные параметры - соблюдаем чистоту функций

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +        if (/^[IVXLCDM]+$/.test(input)) {
Регулярку на проверку римского числа можно в константу тоже засунуть и назвать ее понятным именем

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +                let symbol = input[i];
Почему тут let? Чем const от let отличается?

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +        input = parseInt(input, 10);
Можно просто parseInt(input), по умолчанию десятиричная система

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +        input = parseInt(input, 10);
И опять же таки - входные параметры не меняем

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +        for (const [symbol, value] of Object.entries(romanRadix)) {
Давай перепишем это на forEach

2024-09-06 13:58 UTC, F4lkr4m commented on source/roman.js
> +    throw new Error('Неподдерживаемый формат ввода');
Неподдерживаемый тип ввода получается? TypeError?

2024-09-06 13:59 UTC, KhovenOlya commented on source/roman.js
> +    if (typeof input === 'string') {
так у меня так и было(

2024-09-07 00:01 UTC, KhovenOlya commented on source/roman.js
> +                let symbol = input[i];
const - это переменные, которые нельзя обновлять, let - их можно и переопределять, и обновлять. let потому, что эти переменные будут обновлены. 
num - переменная, которая копит результат (римские числа), prev - переменная, которая указывает на предыдущую цифру, т.е  они уже константой быть не могут, т.к их значения постоянно будут изменяться, пока не дойдут до конца цифры.

2024-09-07 00:14 UTC, KhovenOlya commented on source/roman.js
> +function roman (num) {
1.В стрелочной функции нельзя использовать 'this', т.к на оно , в данном случае,  остается неизменным и поэтому, если мы попытаемся вызвать this в стрелочной, то нам просто выведет undefined.
2. В стрелочной функции нельзя дублировать имена параметров. Если мы не находимся в строгом режиме, то в остальных видах функций можно дублировать.

2024-09-07 11:04 UTC, F4lkr4m commented on source/roman.js
> +function roman (num) {
2ое больше про строгий режим, чем про стрелочную
Помимо 1го стрелочная функция еще:
1. Не имеет массива arguments
2. Не имеет контекста super, поэтому ее нельзя вызвать у дочерних классов

2024-09-07 11:12 UTC, F4lkr4m requested changes

2024-09-07 11:12 UTC, F4lkr4m commented on source/roman.js
> +const RomanNum = /^[IVXLCDM]+$/;
Эту константу давай назовем через SCREAMING_SNAKE_CASE, и давай название более вразумительное - типа ROMAN_NUMBER_REGEX

2024-09-07 11:12 UTC, F4lkr4m commented on source/roman.js
> +            let symbol = trimmed[i];
У тебя тут `symbol` нигде не меняется, давай поменяем на `const`

2024-09-07 11:12 UTC, F4lkr4m commented on source/roman.js
> +            let value = romanRadix[symbol];
То же самое с value - оно у тебя не изменяется по коду

2024-09-07 11:12 UTC, F4lkr4m commented on source/roman.js
> +    if (typeof roman !== 'string') {
Давай все проверки сделаем в функции roman, а в функции `romanToArabic` и `arabicToRoman` будем передавать уже чистые правильные значения

2024-09-07 11:12 UTC, F4lkr4m commented on source/roman.js
> +        Object.entries(romanRadix).forEach(([symbol, value]) => {
Давай `forEach` поменяем на `reduce`, тут же у нас накапливается результат

2024-09-07 11:12 UTC, F4lkr4m commented on source/roman.js
> +    let parsed = parseInt(trimmed);
Тут тоже  let... :(

2024-09-07 11:12 UTC, F4lkr4m commented on source/roman.js
> +    let trimmed = roman.trim().toUpperCase();
И здесь let...(

2024-09-07 11:12 UTC, F4lkr4m commented on source/roman.js
> +        if (/^\d+$/.test(input)) {
А это проверка зачем? `parseInt()` и `isInteger()` не проверят это?

2024-09-07 13:24 UTC, KhovenOlya commented on source/roman.js
> +        if (/^\d+$/.test(input)) {
Проверка **if (/^\d+$/.test(input))**? 
Если да, то они же выполняют разные роли **isInteger()** - проверка, что значение - целое число, а **parseInt()** - преобразует строку в число.

2024-09-07 14:41 UTC, F4lkr4m requested changes

2024-09-07 14:41 UTC, F4lkr4m commented on source/roman.js
> +        return Object.entries(romanRadix).reduce((result, [symbol, value]) => {
Тут что-то с отступами случилось

2024-09-07 14:41 UTC, F4lkr4m commented on source/roman.js
> +
Лишняя пробельная строка

2024-09-07 14:41 UTC, F4lkr4m commented on source/roman.js
> +        if (/^\d+$/.test(input)) {
Так давай заранее тут произведем эти действия. 
`const parsed = parseInt(trimmed);`
а потом `if (Number.isInteger(...)) { ... }`
И тогда регулярка на проверку что это число не нужна будет

2024-09-07 14:41 UTC, F4lkr4m commented on source/roman.js
> + * @throws {TypeError} - Если входное значение имеет неверный тип
Забыла тут `RangeError`

2024-09-07 14:41 UTC, F4lkr4m commented on source/roman.js
> + * @throws {TypeError} - Если входное значение не является целым числом
Тут у тебя ошибки уже не бросаются

2024-09-07 14:41 UTC, F4lkr4m commented on source/roman.js
> + * @throws {TypeError} - Если входное значение не является строкой
Тут у тебя ошибки уже не бросаются

2024-09-07 15:08 UTC, F4lkr4m requested changes

2024-09-07 15:08 UTC, F4lkr4m commented on source/roman.js
> +    return result;
Здесь отступа не хватает

2024-09-07 16:09 UTC, F4lkr4m approved these changes
lgtm

2024-09-08 19:06 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 19:06 UTC, DPeshkoff commented on source/roman.js
> +        if (Number.isInteger(parsed) ) {
Ну там и так будет Int, по логике - зачем-то странный парс делаем

2024-09-08 19:06 UTC, DPeshkoff commented on source/roman.js
> +'use strict';
А зачем нужна эта строчка?

2024-09-08 19:06 UTC, DPeshkoff commented on source/roman.js
> +    if (typeof input === 'string') {
Не пройдем

<img width="233" alt="Снимок экрана 2024-09-04 в 18 32 35" src="https://github.com/user-attachments/assets/9f789f48-56fd-44a1-8855-a092190cb65c">

2024-09-08 19:06 UTC, DPeshkoff commented on source/roman.js
> +}
Не теряй перенос строки в конце файла)

2024-09-08 19:06 UTC, DPeshkoff commented on tests/roman.js
> +	QUnit.test('roman выводит ошибку при некорректном вводе', function (assert) {
Давай еще придумаем больше корректных кейсов

2024-09-09 08:22 UTC, KhovenOlya commented on source/roman.js
> +'use strict';
Это строгий режим. В этом режиме применяются более строгие правила, которые помогают предотвратить большинство ошибок. Например, нельзя использовать with, во имя избежания путаницы в видимости переменных; нельзя просто присвоить переменной какое-либо значения без явного ее объявления; нельзя изменить неизменяемые свойства, будет выдана ошибка, а так же есть свои зарезервированные слова, которые нельзя использовать в качестве идентификаторов.

2024-09-10 21:07 UTC, DPeshkoff requested changes

2024-09-10 21:07 UTC, DPeshkoff commented on README.md
давай вернем удаленные файлы

2024-09-13 06:47 UTC, DPeshkoff approved these changes

2024-09-13 06:48 UTC, closed without merging