Светлаков Владимир
frontend-park-mail-ru/homework_2024_2 pull request #31
Opened 2024-09-05 20:58 UTC by vovasvl

Вариант 3

Задание:
Напишите функцию roman, которая позволяет переводить римские числа в десятичные и обратно (в зависимости от того, что было в функцию передано)

![Тесты](https://github.com/user-attachments/assets/0ef7ae83-7b3f-4657-ac80-9a540db4be69)

2024-09-07 18:13 UTC, rissenberg commented
Привет! Я буду твоим проверяющим ментором. Если возникнут вопросы, не стесняйся писать мне в [телеграм](https://t.me/PassPort_Guardian), постараюсь оперативно ответить!

2024-09-07 20:04 UTC, rissenberg commented on source/roman.js
> +'use strict'; //включаем строгий режим, чтобы не думать о косяках старого js, выскакивающих в режиме обратной совместимости
Уже наперед все расписал, молодец)

2024-09-07 20:44 UTC, rissenberg requested changes
Подправь эти замечания, и пингани меня в тг - будут вопросы, обращайся!

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +const roman = (inputNumber) => {
Давай-ка ты еще распишешь, какие бывают методы объявления функции)

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +    if (inputNumber == parseInt(inputNumber, 10) && inputNumber>0){ //Проверяем, что на входе корректное число
parseInt(10) можно заменить ударным оператором +

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +    if(!inputNumber){ //Проверяем на NaN, null, undefined и т.д.
Может быть будем кидать здесь ошибку?

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +        return null;
здесь бы тоже кидать ошибку - ситуация такая, что пользователь ввел неправильные данные в функцию - нужно об этом сообщать

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +        if("mdclxvi".indexOf(inputNumber[i]) == -1){ // Проверяем, что все символы - это римские цифры
А почему сравнение не строгое?

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +    let n = inputNumber.length;
можно сделать const

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +            return null;
здесь тоже резонно на ошибку поменять

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +    if (inputNumber == parseInt(inputNumber, 10) && inputNumber>0){ //Проверяем, что на входе корректное число
Что у нас кстати с кейсом, когда переданное число меньше 0? Нужно явную проверку б сделать, иначе передается просто 0

2024-09-07 20:44 UTC, rissenberg commented on source/roman.js
> +        }else{
Я бы еще тут (и в похожих местах) ставил пробелы между ключевыми словами и операторами, так становится читаймее намного)

2024-09-07 21:09 UTC, rissenberg commented on source/roman.js
> +    if (inputNumber == parseInt(inputNumber, 10) && inputNumber>0){ //Проверяем, что на входе корректное число
Еще ты, кается, не учел кейсы с нецелыми числами - что в таком случае будем возвращать?

2024-09-08 14:31 UTC, vovasvl commented on source/roman.js
> +const roman = (inputNumber) => {
Можно еще через function. Вроде в js принято обьявлять именно стрелочные функции, поэтому я написал так.

2024-09-08 14:33 UTC, vovasvl commented on source/roman.js
> +    if (inputNumber == parseInt(inputNumber, 10) && inputNumber>0){ //Проверяем, что на входе корректное число
Тесты с нецелыми числами проходят правильно, потому что (inputNumber == parseInt(inputNumber, 10) && inputNumber>0) пропускает только целые положительные числа, а все нецелые и неположительные числа потом не проходят проверку на римское число

2024-09-08 14:34 UTC, vovasvl commented on source/roman.js
> +    if (inputNumber == parseInt(inputNumber, 10) && inputNumber>0){ //Проверяем, что на входе корректное число
Если parseInt(inputNumber, 10) нужно заменить на +inputNumber, то тогда уже нужна будет дополнительная проверка на то, целое число или нет

2024-09-08 14:35 UTC, vovasvl commented on source/roman.js
> +        if("mdclxvi".indexOf(inputNumber[i]) == -1){ // Проверяем, что все символы - это римские цифры
Потому что .indexOf и -1 являются int и нет необходимости проверять, что они одного типа через ===

2024-09-08 15:12 UTC, vovasvl commented on source/roman.js
> +    if (inputNumber == parseInt(inputNumber, 10) && inputNumber>0){ //Проверяем, что на входе корректное число
Поправил

2024-09-08 15:14 UTC, rissenberg commented on source/roman.js
> +const roman = (inputNumber) => {
Помимо стрелочных есть еще 2 типа, чем они принципиально отличаются друг от друга и чем стрелочная от них?

2024-09-08 15:16 UTC, rissenberg commented on source/roman.js
> +        if("mdclxvi".indexOf(inputNumber[i]) == -1){ // Проверяем, что все символы - это римские цифры
Поэтому и нужно ставить строгий тип - вообще, почти никогда не пишут ==, поэтому и здесь лишним не будет - заодно привыкнешь ставить строгие сравнения

2024-09-08 15:19 UTC, vovasvl commented on source/roman.js
> +        if("mdclxvi".indexOf(inputNumber[i]) == -1){ // Проверяем, что все символы - это римские цифры
Поменял == на ===

2024-09-08 15:23 UTC, vovasvl commented on source/roman.js
> +const roman = (inputNumber) => {
Можно просто как function объявить, а можно присвоить функцию переменной - тогда это будет функциональное объявляение. Стрелочные и функциональные объявления функции не поднимаются в контексте, и их нельзя вызывать до определения

2024-09-08 15:44 UTC, rissenberg requested changes
Давай еще подправим твою задачу

2024-09-08 15:44 UTC, rissenberg commented on source/roman.js
> +        return TypeError('Введено NaN, null или undefined');
Не очень информативно - я должен понимать, что случилось и что нужно сделать - я предлагаю эту проверку передалать совсем - проверять изначально инпут на тип number или string, если эта проверка не прошла - писать в ошибку сообщение по типу ``Ожидался тип number | string, получено ${type of inputNumber}``

2024-09-08 15:44 UTC, rissenberg commented on source/roman.js
> +    if ((inputNumber == +inputNumber) && (inputNumber % 1 == 0) && inputNumber>0){ //Проверяем, что на входе корректное число
Проверка `inputNumber == +inputNumber` очень странная. Лучше просто написать `+inputNumber` - если это число, или строка с числом, то проверка пройдет

2024-09-08 15:44 UTC, rissenberg commented on source/roman.js
> +    if ((inputNumber == +inputNumber) && (inputNumber % 1 == 0) && inputNumber>0){ //Проверяем, что на входе корректное число
А в другом условии сравнение сделай строгим

2024-09-08 15:44 UTC, rissenberg commented on source/roman.js
> +        if('mdclxvi'.indexOf(inputNumber[i]) == -1){ // Проверяем, что все символы - это римские цифры
опять нестрогое сравнение

2024-09-08 15:44 UTC, rissenberg commented on source/roman.js
> +        return TypeError('Введено некорректное число');
Здесь можно добавить конкретику - введено нецелое число или число меньше 1

2024-09-08 15:44 UTC, rissenberg commented on source/roman.js
> +            TypeError('Введено некорректное число');
Здесь можно добавить конкретику - Введено некорректное римское число. Допустимые символы: I, V, X, L, C, D, M

2024-09-08 15:44 UTC, rissenberg commented on source/roman.js
> +        }else{
Так и не добавил

2024-09-08 16:51 UTC, vovasvl commented on source/roman.js
> +        return TypeError('Введено NaN, null или undefined');
Добавил, еще сделал проверку на NaN, т.к. оно в ошибке высвечивается как number

2024-09-08 16:51 UTC, vovasvl commented on source/roman.js
> +    if ((inputNumber == +inputNumber) && (inputNumber % 1 == 0) && inputNumber>0){ //Проверяем, что на входе корректное число
Поправил

2024-09-08 16:51 UTC, vovasvl commented on source/roman.js
> +        if('mdclxvi'.indexOf(inputNumber[i]) == -1){ // Проверяем, что все символы - это римские цифры
Поправил

2024-09-08 16:54 UTC, vovasvl commented on source/roman.js
> +        return TypeError('Введено некорректное число');
Заменил это на проверку корректности числа сразу после проверки на число, чтобы бы было более читаемо

    if (+inputNumber){ //Проверяем, что на входе число

        if (inputNumber % 1 !== 0 || inputNumber <= 0){
            return TypeError('Введено нецелое число или число меньше 1');
        }

2024-09-08 16:54 UTC, vovasvl commented on source/roman.js
> +            TypeError('Введено некорректное число');
Поправил

2024-09-09 06:14 UTC, rissenberg approved these changes

2024-09-09 07:32 UTC, vovasvl commented on source/roman.js
> +const roman = (inputNumber) => {
Стрелочные функции не создают своего контекста this, а наследуют его от контекста, в котором они обьявлены, например, класса

2024-09-13 07:17 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа отличная, накидаю немного вопросиков)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-13 07:17 UTC, DPeshkoff commented on source/roman.js
> +    if ( !(+inputNumber) && typeof inputNumber !== 'string' ){
Сломаем

![Uploading Снимок экрана 2024-09-13 в 10.16.31.png…]()

2024-09-13 07:17 UTC, DPeshkoff commented on source/roman.js
> +        return TypeError(`Ожидался тип number | string, получено ${isNaN(inputNumber) ? NaN : typeof inputNumber}`);
Чем isNaN отличается от Number.isNaN?

2024-09-13 08:34 UTC, vovasvl commented on source/roman.js
> +        return TypeError(`Ожидался тип number | string, получено ${isNaN(inputNumber) ? NaN : typeof inputNumber}`);
isNaN кастит переменную в number перед проверкой и даёт true на все типы, которые нельзя просто перевести в number, например строки. 
Number.isNaN делает проверку без каста значения в number, и на те же строки он даст false

2024-09-13 09:21 UTC, vovasvl commented on source/roman.js
> +    if ( !(+inputNumber) && typeof inputNumber !== 'string' ){
Поправил

2024-09-14 10:30 UTC, DPeshkoff approved these changes

2024-09-14 10:30 UTC, closed without merging