created euclid
frontend-park-mail-ru/homework_2024_2 pull request #32
Opened 2024-09-06 10:04 UTC by SlashLight

Здравствуйте! Я Савватеев Андрей, это решение задачи второго варианта пока без доп тестов

2024-09-06 18:00 UTC, Shureks-den commented
Привет! Меня зовут Саша, поздравляю с поступлением на курс по фронтенд разработке! По всем вопросам пиши в телегу t.me/aklonov

2024-09-06 18:01 UTC, Shureks-den commented
Назови мр, по правилам, допиши свои тесты и после прикрепи их результаты в описание к пр

2024-09-06 18:14 UTC, Shureks-den commented
Добавь плз описание задания, не очень удобно проверять

2024-09-06 18:24 UTC, Shureks-den requested changes

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +function euclid() {
Почитай что такое строгий режим, напиши в комментах для чего он нужен и давай его использовать

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +function euclid() {
В мире фронтенда typescript является стандартом уже довольно долгое время, хоть тут мы и не можем его юзать, но существует способ описания функций и ее типов - JSDoc. Давай оформим описание функции с его помощью

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +function euclid() {
Расскажи какие способы заданий функций ты знаешь и чем они отличаются между собой. И давай тут заюзаем "стрелочную" функцию

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +    let x = arguments[0];
Какие типы переменных ты знаешь?

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +    let x = arguments[0];
Откуда ты берешь значение для x, почему это работает, и почему это плохо? Давай сделаем явный параметр

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +    for (let i = 1; i < arguments.length; i++) {
Использование arguments является по сути deprecated, потому что это супер-очевидная штука. Почитай про `rest `параметры и заиспользуй их

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +    let x = arguments[0];
Что произойдет если вызовем функцию без параметров? Можно ли явно подсказать человеку, который так делает, что он неправ?

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +    return x;
Решение хорошее с точки зрения использования наиболее простых функций, которые понятны для людей, которые знают какой-либо ЯП, не обязательно JS. Но если призадуматься, ты получаешь массив, а вернуть должен какое-то значение - для этого в JS есть функция reduce для массивов, давай ее постараемся заиспользовать, чтобы проникнуться JS)

2024-09-06 18:24 UTC, Shureks-den commented on source/euclid.js
> +}
Добавь отступ после последней строчки в файле

2024-09-08 14:26 UTC, SlashLight commented on source/euclid.js
> +function euclid() {
Если коротко, то строгий режим добавляет определенные строгие правила и ограничения, засчет которых достигается более быстрое обнаружение ошибок, что упрощает отладку, большая производительность засчет оптимизаций и совместимость с будущими версиями благодаря запрету на использование устаревших или устаревающих функций

2024-09-08 14:35 UTC, SlashLight commented on source/euclid.js
> +function euclid() {
Насколько мне известно в JS есть три способа задания функции:
1. Декларативное объявление, то есть объявление функции как отдельного блока кода, который не будет присваиваться другим переменным или передаваться в качестве аргумента в другую функцию. Этот способ объявления и использовал я в этом примере
2. Функциональное выражение, то есть const переменная = function(параметры) {...};. 
3. Стрелочная функкция. Ее особенностью является работа в той области видимости, в которой они были объявлены, а также наследование this, arguments у родительских функций и доступ к окружению, в котором они были созданы

2024-09-08 14:38 UTC, SlashLight commented on source/euclid.js
> +    let x = arguments[0];
String строка
Number число
BigInt большие целые числа
Boolean логическое значение true или false
Undefined специальное значение, которое указывает, что значение не установлено
Null указывает на отсутствие значения
Symbol представляет уникальное значение
Object комплексный объект

2024-09-08 15:00 UTC, SlashLight commented
Результаты тестов
![Снимок экрана от 2024-09-08 17-57-18](https://github.com/user-attachments/assets/890607e6-db25-4eed-babf-1cf358ba2e03)

2024-09-08 15:36 UTC, Shureks-den requested changes

2024-09-08 15:36 UTC, Shureks-den commented on source/euclid.js
> +            return euclid(b, a % b);
Давай воспользуемся тернарным оператором `return condition ? x : y`

2024-09-08 15:36 UTC, Shureks-den commented on tests/euclid.js
> +	QUnit.test('На входе два числа число', function (assert) {
Добавь негативные кейсы, чтобы проверить свои пробросы ошибок

2024-09-08 15:36 UTC, Shureks-den commented on source/euclid.js
> +    let x = arguments[0];
Еще есть так называемые примитивные типы и все остальное, какое главное отличие у них

2024-09-09 09:15 UTC, SlashLight commented
Результаты тестов
![изображение](https://github.com/user-attachments/assets/d52d1430-1ba7-4854-ae2a-e0f995b42e80)

2024-09-09 09:21 UTC, SlashLight commented
По поводу примитивных типов данных
Примитивными называются те типы данных, которые не являются объектами и не могут иметь методов и свойств

2024-09-11 20:20 UTC, Shureks-den approved these changes

2024-09-12 14:38 UTC, Sarafa2n commented on source/euclid.js
> +                throw new Error('not a natural number');
лучше написать что не число, потому что я же могу что-то другое сюда прокинуть

2024-09-14 10:31 UTC, DPeshkoff requested changes

2024-09-14 10:31 UTC, DPeshkoff commented on source/euclid.js
> +    if (numbers.length === 0) {
Можно [сократить](https://developer.mozilla.org/ru/docs/Glossary/Falsy)

2024-09-14 10:31 UTC, DPeshkoff commented on source/euclid.js
> +'use strict';
А что означает этот режим?

2024-09-14 11:27 UTC, SlashLight commented on source/euclid.js
> +'use strict';
Если коротко, то строгий режим добавляет определенные строгие правила и ограничения, засчет которых достигается более быстрое обнаружение ошибок, что упрощает отладку, большая производительность засчет оптимизаций и совместимость с будущими версиями благодаря запрету на использование устаревших или устаревающих функций

Примерами могут служить следующие моменты: опечатка в имени переменной во время присваивания не создаёт свойства глобального объекта, имена аргумента функции не могут дублироваться, имена свойств ссериализованного объекта не могут дублироваться, попытка удалить неудаляемое свойство вызовет исключение.

2024-09-15 10:59 UTC, closed without merging