Karganov Andrey
frontend-park-mail-ru/homework_2024_2 pull request #33
Opened 2024-09-06 18:30 UTC by andrey-918

variant-5

2024-09-07 18:34 UTC, rissenberg commented
Привет! Я буду твоим проверяющим ментором. Если возникнут вопросы, не стесняйся писать мне в [телеграм](https://t.me/PassPort_Guardian), постараюсь оперативно ответить!

2024-09-07 21:26 UTC, rissenberg requested changes
Добавь к своей функции JSDoc - что это можешь почитать здесь, написано достаточно хорошо: https://precodes.hashnode.dev/jsdoc-the-ultimate-guide-to-documenting-your-javascript-code

Подправь эти замечания и пингани меня в тг - будут вопросы, смело обращайся!

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +const chess = size => {
Нету в начале ключевого слова use strict - добавь его и напиши в ответе, для чего оно нужно

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +const chess = size => {
Какие знаешь методы объявления функции? Напиши об этом и расскажи, почему выбрал именно этот

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +    const numericSize = Number(size);
можно приводить к типу number с помощью унарного +

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +    if (size <= 1) return null;
Давай для этого кейс тоже ошибку кидать - выглядит, как некорректный инпут

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +    if (size <= 1) return null;
И разве для 1 мы должны возвращать null? возвращай поле с одной клеткой

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +    if (size <= 1) return null;
Почему бы нам дальше не использовать numericSize? мы ведь его уже перевели в число, давай поступать так, чтоб избавиться от лишних преобразований

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +    const board = Array.from({ length: size }, (_, line) =>
Кажется нецелесообразным сначала конструировать массив из символов, а потом переводить его обратно в строку. Давай эти лишние преобразования уберем и попробуем сделать без них?

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +        Array.from({ length: size }, (_, row) =>
Еще, у тебя каждую итерацию по строке генерируется новая последовательность этих символов - как будто бы можно избежать повторяющихся действий. Например, сгенерить 2 чередующиеся строки до цикла и потом size раз их прибавить к board

2024-09-07 21:26 UTC, rissenberg commented on source/chess.js
> +};
пустую строчку в конце добавь)

2024-09-07 21:26 UTC, rissenberg commented on tests/chess.js
> +			'* * \n' +
Почему мы проверяем chess(6) на доске размером 4?

2024-09-08 06:59 UTC, andrey-918 commented on source/chess.js
> +const chess = size => {
use strict - директива в JS, которая включает строгий режим: он запрещает неявные объявления переменных, дублирование, использование зарезервированных слов

2024-09-08 07:04 UTC, andrey-918 commented on source/chess.js
> +    if (size <= 1) return null;
в исходных тестах было, что доски 1 на 1 не бывает, и expected = null

2024-09-08 08:06 UTC, andrey-918 commented on source/chess.js
> +    if (size <= 1) return null;
теперь 1 на 1 выводит поле с одной клеткой

2024-09-08 08:15 UTC, andrey-918 commented on source/chess.js
> +const chess = size => {
я использовал стрелочную функцию из-за того, что она выглядит более лаконично
знаю также: функциональное выражение, функциональное объявление, функцию-конструктор и асинхронную функцию

2024-09-08 08:19 UTC, andrey-918 commented on source/chess.js
> +const chess = size => {
выражение используют, когда функция нужна в одном месте или когда передают функцию как аргумент
объявление нужно для того, чтобы использовать функцию в нескольких местах 
конструктор не знаю даже, где используют, редко их вижу, сам не пишу
асинхронные используют для работы с сервером, для работы с промисами

2024-09-08 08:53 UTC, rissenberg requested changes
Давай еще в одну итерацию исправим неточности, и я буду ждать от тебя сообщения

2024-09-08 08:53 UTC, rissenberg commented on source/chess.js
> +    const oddLineGen = size => {
Вынести логику генерации строки в другую функцию хорошая идея, но тогда вынеси эту функцию вовне функции chess. Еще бы я порекомендовал сделать одну функцию, которая бы возвращала объект типа:
```
{
    evenLine: string,
    oddLine: string,
}
```
И с помощью [деструктурирующего присваивания](https://learn.javascript.ru/destructuring-assignment) объявил переменные внутри chess()

2024-09-08 08:53 UTC, rissenberg commented on source/chess.js
> +    const oddLineGen = size => {
Если сделаешь одну функцию, то цикл можно тоже один оставить - еще небольшая оптимизация ;)

2024-09-08 08:53 UTC, rissenberg commented on source/chess.js
> +            i % 2 == 0 ? line += '*' : line += ' '
здесь лучше терновник поставить после приставания, а сравнение сделать строгим:
`line += i % 2 === 0 ? '*' : ' '`

2024-09-08 08:53 UTC, rissenberg commented on source/chess.js
> +        for (let i = 0; i < size; i++) {
i объяви константной

2024-09-08 08:53 UTC, rissenberg commented on source/chess.js
> +        typeof numericSize !== 'number' ||
Бесполезная проверка, мы ведь и так его преобразовали в number (NaN тоже типа number)

2024-09-08 08:53 UTC, rissenberg commented on source/chess.js
> +        size === null ||
Эта и следующие проверки не нужны, они не пройдут еще при проверке на NaN

2024-09-08 08:53 UTC, rissenberg commented on source/chess.js
> +    if (numericSize < 1) throw new Error('Size must be more than 1');
Я в условии не видел, но если пишут, что доски размером 1 не бывает - давай ее уберем из допустимых значений

2024-09-08 08:53 UTC, rissenberg commented on source/chess.js
> +        i % 2 == 0 ? board += oddLine : board += evenLine
Тут аналогично с порядком приставания и терновником

2024-09-08 08:53 UTC, rissenberg commented on tests/chess.js
> +	QUnit.test('Шахматная доска 1 на 1', function (assert) {
Сорри, я не видел, что такая проверка есть - давай вернем ее как была)

2024-09-08 09:58 UTC, rissenberg requested changes
Последняя правка и отпущу)

2024-09-08 09:58 UTC, rissenberg commented on source/chess.js
> +const lineGen = size => {
Напишешь для нее доку? @example можно не писать)

2024-09-08 10:00 UTC, rissenberg commented on source/chess.js
> +    if (size <= 1) return null;
хорошо, тогда оставляем 1 как недопустимое значение

2024-09-08 10:13 UTC, andrey-918 commented on source/chess.js
> +        for (let i = 0; i < size; i++) {
если объявить i константой, тогда не получается "крутить" цикл, тк нельзя использовать i++

2024-09-08 10:15 UTC, andrey-918 commented on source/chess.js
> +const lineGen = size => {
сделано

2024-09-08 10:34 UTC, rissenberg commented
good to go!

2024-09-08 19:16 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 19:16 UTC, DPeshkoff commented on source/chess.js
> +const lineGen = size => {
Давай в () - так полезнее будет потом (не буду спойлерить!)

2024-09-08 19:16 UTC, DPeshkoff commented on source/chess.js
> +'use strict';
А что эта строчка делает?

2024-09-08 19:16 UTC, DPeshkoff commented on source/chess.js
> +    if (typeof size !== 'number' && typeof size !== 'string') {
Не пройдем

<img width="233" alt="Снимок экрана 2024-09-04 в 18 32 35" src="https://github.com/user-attachments/assets/9f789f48-56fd-44a1-8855-a092190cb65c">

2024-09-08 19:16 UTC, DPeshkoff commented on source/chess.js
> +        throw new Error('Size must be an integer.');
А тут не TypeError?

2024-09-08 19:16 UTC, DPeshkoff commented on source/chess.js
> +        throw new Error('Size must be a positive integer more than 1.');
RangeError?

2024-09-09 21:10 UTC, andrey-918 commented on source/chess.js
> +'use strict';
Устанавливает строгий формат написания кода

2024-09-11 20:45 UTC, DPeshkoff approved these changes

2024-09-11 20:45 UTC, closed without merging