Константин Сафронов в17
frontend-park-mail-ru/homework_2024_2 pull request #34
Opened 2024-09-06 21:21 UTC by KoSafronov

2024-09-07 18:13 UTC, rissenberg commented
Привет! Я буду твоим проверяющим ментором. Если возникнут вопросы, не стесняйся писать мне в [телеграм](https://t.me/PassPort_Guardian), постараюсь оперативно ответить!

2024-09-07 20:59 UTC, rissenberg requested changes
Добавь еще к своей функции JSDoc - что это можешь почитать здесь, написано достаточно хорошо: https://precodes.hashnode.dev/jsdoc-the-ultimate-guide-to-documenting-your-javascript-code

Как будешь готов, пингани меня в тг - постараюсь оперативно ответить!

2024-09-07 20:59 UTC, rissenberg commented on index.html
> +<!--
Он нам не нужен, давай просто удалим

2024-09-07 20:59 UTC, rissenberg commented on source/plainify.js
> +
Почему без use strict? Давай-ка добавь эту директиву и напиши в ответе, для чего она нужна

2024-09-07 20:59 UTC, rissenberg commented on source/plainify.js
> +const plainify = (obj, prefix = '') => {
Какие знаешь методы объявления функции в JS и почему выбрал именно этот?

2024-09-07 20:59 UTC, rissenberg commented on source/plainify.js
> +            if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
Почему мы делаем проверку на null здесь? И почему не берем в рассмотрение массивы?

2024-09-07 20:59 UTC, rissenberg commented on source/plainify.js
> +    for (let key in obj) {
let здесь можно заменить на const

2024-09-07 20:59 UTC, rissenberg commented on source/plainify.js
> +        if (obj.hasOwnProperty(key)) {
Для меня выглядит странной эта проверка - разве мы не перебираем ключи объекта и не всегда ли она будет трушной?

2024-09-07 20:59 UTC, rissenberg commented on tests/plainify.js
> +    QUnit.test('Plain obj без вложенности', function (assert) {
Нет совсем негативных кейсов - нужно проверять, что будет, если мы передадим в функцию примитив - для этого, может быть, понадобится написать дополнительную проверку и обрабатывать такие случаи с помощью `throw new Error()` или возвращать данный примитив

2024-09-08 13:14 UTC, KoSafronov commented on source/plainify.js
> +
При использовании "use strict"; код js будет работать для всех "последних" браузеров с учетом всех модернизаций языка

2024-09-08 13:51 UTC, KoSafronov commented on source/plainify.js
> +const plainify = (obj, prefix = '') => {
Методы объявления:
Декларативный
function имяФ(параметры ) {
  // Тело Ф
};

Функциональный
const имяПеременной = function(параметры) {
  // Код Ф
};

Стрелочный
const имяФ = (параметры) => {
  // Код Ф
  }
  //Выбрал его в связи с достаточно простым оформлением и отсутствием необходимости добавлять this в данном виде использования
  
  
  Анонимный/самовызывающийся
};

2024-09-09 06:50 UTC, rissenberg approved these changes
Предварительно аппрув поставил, но ты все равно исправь эти пару замечаний, что я выделил

2024-09-09 06:50 UTC, rissenberg commented on source/plainify.js
> +        if (typeof obj[key] === 'object' && obj[key] !== null) {
Тут явную проверку на null можно опустить - давай просто напишем `&& obj[key]`

2024-09-09 06:50 UTC, rissenberg commented on source/plainify.js
> +                Object.assign(result, plainify(obj[key], newKey));
Почему мы используем тут `Object.assign`?

2024-09-09 08:56 UTC, KoSafronov commented on source/plainify.js
> +                Object.assign(result, plainify(obj[key], newKey));
Мы используем Object.assign чтобы объединить все результаты (в тч рекурсивные) и чтобы избежать перезаписи

2024-09-12 14:59 UTC, Sarafa2n commented on package.json
> +}
зачем ???

2024-09-12 15:00 UTC, Sarafa2n commented on source/plainify.js
> +    for (let key in obj) {
а почему не методы массива ?

2024-09-12 15:00 UTC, Sarafa2n commented on source/plainify.js
> +        if (typeof obj[key] === 'object' && obj[key]) {
могу сюда закинуть new Array или new String

2024-09-14 10:32 UTC, DPeshkoff requested changes

2024-09-14 10:32 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Давай вернем старое

2024-09-14 10:32 UTC, DPeshkoff commented on source/plainify.js
> +"use strict";
Одиночные кавычки

2024-09-14 10:32 UTC, DPeshkoff commented on package.json
А зачем нам этот пустой файл?

2024-09-14 11:22 UTC, KoSafronov commented on index.html
> -<script src="tests/max.js"></script>
Чтобы max.js тоже выполнялся?
Или закоментить его, но вернуть?

2024-09-16 16:36 UTC, Sarafa2n commented on source/plainify.js
> +    }
new String, new Date, new Array

2024-09-17 09:43 UTC, Sarafa2n commented on source/plainify.js
> +}
new Set, New Map, я так могу продолжать, давай посмотрим в стону как проверить что тебе пришел именно объектик, посмотри на метод toString() там его нужно правда интересно вызвать

2024-09-18 12:34 UTC, F4lkr4m commented on source/plainify.js
> +
Лишние пробелы тут не нужны

2024-09-18 12:35 UTC, F4lkr4m commented on source/plainify.js
> +        throw new Error('Invalid input: plainify expects an object');
И не забудь обновить JSDoc

2024-09-18 12:36 UTC, F4lkr4m commented on tests/plainify.js
> +
Лишние пробелы, больше одной строки пустой не оставляем

2024-09-18 12:37 UTC, F4lkr4m commented on source/plainify.js
> +            if (Array.isArray(obj[key])) {
Сверху же проверка на !isArray? O_o

2024-09-18 12:37 UTC, F4lkr4m commented on source/plainify.js
> +            if (Array.isArray(obj[key])) {
Тебе тут по факту надо проверить объект у тебя передан или не объект. Если объект - копаем дальше, если не объект, то записываем в поле

2024-09-18 12:37 UTC, F4lkr4m commented on source/plainify.js
> +            if (Array.isArray(obj[key])) {
Можно даже отдельную функцию на эту проверку сделать и переиспользовать ее

2024-09-18 12:42 UTC, F4lkr4m commented on source/plainify.js
> +    return Object.keys(obj).reduce((acc, key) => {
Можно использовать `Object.entries(obj).reduce((acc, [key, value]) => ...)`, тогда доставать value по obj[key] не будет необходимости

2024-09-18 12:52 UTC, F4lkr4m commented on source/plainify.js
> +    if (Object.prototype.toString.call(obj) !== '[object Object]') {
Можно сделать просто `obj.toString()`

2024-09-19 08:58 UTC, Sarafa2n commented on source/plainify.js
> +    if (Object.prototype.toString.call(obj) !== '[object Object]') {
<img width="226" alt="image" src="https://github.com/user-attachments/assets/41148c76-cae8-4341-b5e6-43c72c6ad6f7">

2024-09-19 09:13 UTC, F4lkr4m commented on source/plainify.js
> +    if (Object.prototype.toString.call(obj) !== '[object Object]') {
Окей))

2024-09-19 09:14 UTC, F4lkr4m commented on source/plainify.js
> +    if (Object.prototype.toString.call(obj) !== '[object Object]') {
Но это все равно исключает `'[object Object]'`

2024-09-19 09:41 UTC, closed without merging