variant-13
frontend-park-mail-ru/homework_2024_2 pull request #36
Opened 2024-09-07 08:16 UTC by Achpochmak

2024-09-07 18:31 UTC, rissenberg commented
Привет! Я буду твоим проверяющим ментором. Если возникнут вопросы, не стесняйся писать мне в [телеграм](https://t.me/PassPort_Guardian), постараюсь оперативно ответить!

2024-09-07 20:01 UTC, rissenberg requested changes
Добавь к своей функции JSDoc - что это можешь почитать здесь, написано достаточно хорошо: https://precodes.hashnode.dev/jsdoc-the-ultimate-guide-to-documenting-your-javascript-code

Подправь эти замечания и пингани меня в тг - будут вопросы, смело обращайся!

2024-09-07 20:14 UTC, rissenberg commented on source/get.js
> +    if (!path || path === '.') return obj;
Подумал, что лучше в таком случае возвращать ошибки - если параметр path не строка - `throw new Error`

2024-09-08 10:30 UTC, Achpochmak commented on source/get.js
> +'use strict';
Эта директива включает строгий режим, которая нужна для того, чтобы код работал по современным стандартам

2024-09-08 15:06 UTC, rissenberg requested changes
Подправь и пингани меня в тг снова

2024-09-08 15:06 UTC, rissenberg commented on source/get.js
> +        throw new Error;
Для этого примера лучше использовать тип ошибки `TypeError`, и в параметр напиши в виде строки словесное описание ошибки, например, `new TypeError('path is not a string')`

2024-09-08 15:06 UTC, rissenberg commented on source/get.js
> +    if (typeof path != 'string'){
но ее тогда нужно поставить после 23 строки

2024-09-08 15:06 UTC, rissenberg commented on source/get.js
> +        if (acc !== undefined) {
Неправильная проверка. Например, если в аргументы передать объект `{ a: 5, }` и попытаться найти путь `.a.b`, выполнение завершится с ошибкой. Подумай, как это исправить

2024-09-08 15:06 UTC, rissenberg commented on source/get.js
> +        if (acc !== undefined) {
Таких кейсов нет в тестах, поэтому добавь их заодно во втором файле

2024-09-08 17:03 UTC, Achpochmak commented on source/get.js
> +function get(obj, path) {
Существует 3 типа объявления функций: декларативное объявление, функциональное выражение и стрелочная функция. Декларативную можно использовать в любом месте в коде, что также может являться недостатком, т.к. можно просто забыть про нее, что в итоге приведет к ошибкам.  Ее также нельзя присвоить переменной или в качестве аргумента функции, в отличие от функционального выражения. Функциональное выражение удобно использовать в конкретном контексте и с другими функциями, но такую функцию нельзя использовать до ее объявления, если функция анонимна. Стрелочные функции не имеют имени и ключевого слова function, что может ухудшать читаемость, но зато они компактны. Их также нельзя использовать до объявления функции.

2024-09-09 06:19 UTC, rissenberg commented on source/get.js
> +function get(obj, path) {
К читаемости стрелочных функций еще привыкнешь) расскажи лучше, что это за ключевое слово `this` такое и что функции с ним делают?

2024-09-09 06:34 UTC, rissenberg requested changes

2024-09-09 06:34 UTC, rissenberg commented on source/get.js
> +            return undefined;
undefined опускаем при return

2024-09-09 06:34 UTC, rissenberg commented on source/get.js
> +            if (!isNaN(part)) {
Ты, видимо, хочешь проверить, является ли part индексом - в таком случае нужно так же проверить его на целочисленность и неотрицательность

2024-09-09 06:34 UTC, rissenberg commented on source/get.js
> +                return acc[Number(part)];
Кастовать в Number можно с помощью унарного +

2024-09-09 06:34 UTC, rissenberg commented on source/get.js
> +        if (typeof acc === 'object') {
Не забудь здесь проверку на null, а то упадет с ошибкой

2024-09-09 06:34 UTC, rissenberg commented on source/get.js
> +        return undefined;
undefined нужно опустить

2024-09-09 06:34 UTC, rissenberg commented on source/get.js
> +    if (typeof obj !== 'object' || obj === null) {
явная проверка на null мне не очень нравится - давай просто `!obj`

2024-09-09 14:36 UTC, rissenberg approved these changes
Поставил аппрув, подправь последнее замечание, и ожидай проверки Димой

2024-09-09 14:36 UTC, rissenberg commented on source/get.js
> +            if (!isNaN(part) && Number.isInteger(part) && part > 0) {
индекс может быть равен нулю)

2024-09-12 14:43 UTC, Sarafa2n commented on source/get.js
> +    if (typeof path !== 'string') {
а если строка через new String()

2024-09-13 13:10 UTC, Achpochmak commented on source/get.js
> +    }
Тогда будет undefined

2024-09-13 14:59 UTC, Achpochmak commented on source/get.js
> +    if (typeof path !== 'string') {
Поправила условия

2024-09-13 15:01 UTC, Sarafa2n commented on source/get.js
> +    }
почему ? 
<img width="281" alt="image" src="https://github.com/user-attachments/assets/a1191576-25b4-4f62-8d91-49e20db4000d">

2024-09-14 10:33 UTC, DPeshkoff requested changes

2024-09-14 10:33 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Исходное давай вернем, не будем удалять)

2024-09-14 10:33 UTC, DPeshkoff commented on tests/get.js
> +		assert.strictEqual(get(object, '.a.b'), undefined);
отступам плохо

<img width="988" alt="Снимок экрана 2024-09-14 в 13 33 31" src="https://github.com/user-attachments/assets/82af44fe-b190-4360-9c68-558c01f0213b">

2024-09-14 23:43 UTC, Achpochmak commented on index.html
> -<script src="tests/max.js"></script>
Поправила

2024-09-14 23:45 UTC, Achpochmak commented on tests/get.js
> +		assert.strictEqual(get(object, '.a.b'), undefined);
Поправила

2024-09-16 19:17 UTC, DPeshkoff approved these changes

2024-09-16 19:18 UTC, closed without merging