Балюк Андрей
frontend-park-mail-ru/homework_2024_2 pull request #37
Opened 2024-09-07 12:57 UTC by Qaleka

2024-09-09 09:26 UTC, AlexandraSmirnova commented
Привет, Андрей! Меня зовут Саша. Поздравляю с переходом на 2-ой семестр. Я твой ментор по ДЗ0 и уже скоро приступлю к проверке. Если будут вопросы - мой ник в телеге @alexandrius23

2024-09-10 09:18 UTC, AlexandraSmirnova requested changes

2024-09-10 09:18 UTC, AlexandraSmirnova commented on source/filter.js
> +function filter(html, allowedTags) {
Давай добавим jsdoc к этой функции

2024-09-10 09:18 UTC, AlexandraSmirnova commented on source/filter.js
> +function filter(html, allowedTags) {
Какие способы объявления функций знаешь? назови, как еще можно было бы объявить эту функцию и в чем различие

2024-09-10 09:18 UTC, AlexandraSmirnova commented on source/filter.js
> +                                    .replace(/&#39;/g, "'")
Если везде в коде одинарные кавычки, то и тут тоже лучше сделать одинарными. Можно внутренний символ экранировать. 
Рекомендую для ознакомления статью https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2024-09-10 09:18 UTC, AlexandraSmirnova commented on source/filter.js
> +    html = html.replace(/&/g, '&amp;')
Что будет, если html - не строка? Можно добавить тесты на это

2024-09-10 09:18 UTC, AlexandraSmirnova commented on source/filter.js
> +    html = html.replace(/&/g, '&amp;')
Функция не должна менять входящие параметры, если этого не требуется по заданию. Давай тут создадим новую переменную

2024-09-12 18:33 UTC, Qaleka commented on source/filter.js
> +function filter(html, allowedTags) {
'use strict' включает строгий режим, чтобы система выдавала исключения на все ошибки. По сути, ужесточаются синтаксические правила

2024-09-12 18:34 UTC, Qaleka commented on source/filter.js
> +}
Нашел информацию, что она нужна для git, чтобы он иногда не помечал файл как измененный, но не уверен в этом(звучит странно). Ну и для линкера иногда нужна в конце пустая строка

2024-09-12 18:34 UTC, Qaleka commented on source/filter.js
> +function filter(html, allowedTags) {
Добавил

2024-09-12 18:36 UTC, Qaleka commented on source/filter.js
> +function filter(html, allowedTags) {
1) Декларативное объявление - то, что сейчас
2) Функциональное выражение - функция присваивается переменной
3) Стрелочная функция - более компактная функция

2024-09-12 18:36 UTC, Qaleka commented on source/filter.js
> +                                    .replace(/&#39;/g, "'")
Сделал

2024-09-12 18:37 UTC, Qaleka commented on source/filter.js
> +    html = html.replace(/&/g, '&amp;')
Будет TypeError. Добавил

2024-09-12 18:37 UTC, Qaleka commented on source/filter.js
> +    html = html.replace(/&/g, '&amp;')
Сделал

2024-09-13 10:18 UTC, AlexandraSmirnova requested changes

2024-09-13 10:18 UTC, AlexandraSmirnova commented on source/filter.js
> +function filter(html, allowedTags) {
Расскажи, пожалуйста, подробнее какие правила ужесточаются? Что-то еще делает строгий режим кроме ужесточения правил?

2024-09-13 10:18 UTC, AlexandraSmirnova commented on tests/filter.js
> +        const input = '';
тут и далее едут отступы

2024-09-13 10:18 UTC, AlexandraSmirnova commented on tests/filter.js
> +	QUnit.test('filter обрабатывает пустую строку', function (assert) {
Из тестов написанных тобой нет тестов, где input c тегами, давай добавим различные варианты проверок с тегами. 
А также не вижу, чтобы в тестах достаточно покрывались варианты allowedTags. Как отработает код, если я передам этим параметром допустим число?

2024-09-13 11:53 UTC, Qaleka commented on source/filter.js
> +function filter(html, allowedTags) {
В строгом режиме нельзя:
1) использовать переменные без их объявления;
2) дублировать имена свойств в объектах;
3) дублировать параметры функций;
4) удалять переменные, функции и аргументы;
5) использовать зарезервированные слова;
6) использовать устаревшие конструкции;
Также строгий режим меняет поведение объекта this в функции.

2024-09-13 12:04 UTC, Qaleka commented on source/filter.js
> +function filter(html, allowedTags) {
Стрелочные функции работают только в той области видимости, в который были объявлены, а также не имеют своего функционального контекста выполнения. Это подразумевает, что такие сущности, как this или argument, наследуются исключительно у родительских функций. Выражение стрелочных функций не позволяют задавать имя, поэтому стрелочные функции анонимны, если их ни к чему не присвоить.

2024-09-14 15:31 UTC, AlexandraSmirnova requested changes

2024-09-14 15:31 UTC, AlexandraSmirnova commented on source/filter.js
> +function filter(html, allowedTags) {
Отлично, давай тут переделаем. на стрелочную функцию :)

2024-09-14 15:31 UTC, AlexandraSmirnova commented on tests/filter.js
> +        const input = '';
не поправлено. Где-то табы используется, где-то пробелы, поэтому едет. Давай табы везде сделаем, чтобы дифф с тестами не был целым файлом.

2024-09-14 15:31 UTC, AlexandraSmirnova commented on source/filter.js
> +    if (typeof html !== 'string') {
Давай еще один кейс для теста добавим:
```
const input = new String('<div>какой-то html</div>');
filter(input, tags); 
```

2024-09-14 18:27 UTC, Qaleka commented on tests/filter.js
> +        const input = '';
Исправил везде на табуляцию. Просто у меня по умолчанию в vs code стояла настройка на пробелы)

2024-09-14 18:28 UTC, Qaleka commented on source/filter.js
> +function filter(html, allowedTags) {
Сделал

2024-09-14 18:28 UTC, Qaleka commented on source/filter.js
> +    if (typeof html !== 'string') {
Написал

2024-09-16 07:41 UTC, AlexandraSmirnova requested changes

2024-09-16 07:41 UTC, AlexandraSmirnova commented on source/filter.js
> +									.replace(/&gt;/g, '>')
Здесь чуть отступы уехали. Выше по-другому отформатировано

2024-09-16 15:24 UTC, Sarafa2n commented on source/filter.js
> +	const allTags = /&lt;\/?([a-zA-Z0-9]+)(.*?)&gt;/g;
это константа по хорошему и можно вынести из функции

2024-09-16 15:24 UTC, Sarafa2n commented on source/filter.js
> +	let replacedHtml = html.replace(/&/g, '&amp;')
const ты нигде не переопределяешь переменную

2024-09-16 19:48 UTC, Qaleka commented on source/filter.js
> +	const allTags = /&lt;\/?([a-zA-Z0-9]+)(.*?)&gt;/g;
Вынес

2024-09-16 19:49 UTC, Qaleka commented on source/filter.js
> +	let replacedHtml = html.replace(/&/g, '&amp;')
Сделал

2024-09-16 21:00 UTC, Sarafa2n commented on source/filter.js
> +const allTags = /&lt;\/?([a-zA-Z0-9]+)(.*?)&gt;/g;
ALL_TAGS

2024-09-17 09:26 UTC, closed without merging