Variant 16 Muzalev Oleg
frontend-park-mail-ru/homework_2024_2 pull request #38
Opened 2024-09-07 16:30 UTC by Olgmuzalev13

Музалев Олег

2024-09-09 17:54 UTC, Gallaann requested changes
Интересное решение, но еще есть что поправить)

2024-09-09 17:54 UTC, Gallaann commented on source/format.js
> +		});
Очень мне не нравится вот эти строки. Они сложно читаются и не очень понятно что происходит вообще.

Предлагаю воспользоваться методом строк `padStart`
```suggestion
		padStart(maxWidth, ' ')
```

2024-09-09 17:54 UTC, Gallaann commented on source/format.js
> +	let output = Array(Math.ceil(input.length / columns)).fill("");
Не очень понимаю смысл в этом заполненном массиве, кажется, что можно обойтись пустым массивом
```suggestion
	const rows = [];
```

2024-09-09 17:54 UTC, Gallaann commented on source/format.js
> +		let maxLen = 0
Можно не инициализировать maxLen каждую итерацию цикла, а вынести нахождение максимальной длины в отдельный цикл. Используй `spread` оператор для разделения массива на отдельные элементы и `Math.max` для нахожджения максимального значения. Длину строк ты уже находить умеешь)

2024-09-09 17:54 UTC, Gallaann commented on source/format.js
> +		}
Давай тут используем встроенные методы над массивом. На колонки будем делить с помощью slice, а потом уже над каждой колонкой выполнять операции по выравниванию

2024-09-09 19:48 UTC, Gallaann commented
А еще убери из названия ПРа вариант, достаточно просто твоей фамилии и имени)

2024-09-10 16:41 UTC, Olgmuzalev13 commented on tests/format.js
> +	QUnit.test('format работает правильно c количеством колонок равным количеству чисел', function (assert) {
Так 
![123124](https://github.com/user-attachments/assets/2410068d-1cca-45c4-96b4-09bfd0034cfc)
Так в оригинальных тестах же нет переноса строки у последнего элемента, почему в этом случае должен быть?

2024-09-10 16:47 UTC, Olgmuzalev13 commented on tests/format.js
> +	QUnit.test('format работает правильно c количеством колонок равным количеству чисел', function (assert) {
Так 
![123124](https://github.com/user-attachments/assets/2410068d-1cca-45c4-96b4-09bfd0034cfc)
Так в оригинальных тестах же нет переноса строки у последнего элемента, почему в этом случае должен быть?

2024-09-10 16:49 UTC, Olgmuzalev13 commented on source/format.js
> +	let output = Array(Math.ceil(input.length / columns)).fill("");
Разве с алгоритмической точки зрения, не быстрее создать массив нужной итоговой длинны и обращаться по индексам чем добавлять в конец массива значения увеличивая его?

2024-09-10 16:55 UTC, Olgmuzalev13 commented on source/format.js
> +'use strict';
'use strict' директива активации строго режима для всего скрипта.
Строгий режим упрощает написание безопасного кода на JS.

Строгий режим меняет нежелательный синтаксис на ошибки заставляя обязательно их исправлять, в старых версиях просто игнорируется.

2024-09-10 17:04 UTC, Olgmuzalev13 commented on source/format.js
> +let format = (input, columns) => {
Стрелочная функция. Стрелочные функции очень удобны для простых действий, особенно для однострочных. Да и вообще синтаксически нагляднее. Также различие в том, что  стрелочные функции не имеют собственного элемента this вместо этого он обратится к значению this в ближайшей традиционной родительской функции.

2024-09-10 17:07 UTC, Olgmuzalev13 commented on source/format.js
> +let format = (input, columns) => {
let, var, const
let - объявление переменной в этой области видимости
var - объявление в глобальной области видимости (считается устаревшим и не рекомендуется вроде)
const - объявление констант

2024-09-10 20:12 UTC, Olgmuzalev13 commented on source/format.js
> +			if (typeof (input[i]) != "number") {
Поменял на !== так будет лучше, потому что строгие сравнивают на полное сходство, а нестрогие могут использовать приведение типа перед сравнением.

2024-09-10 20:24 UTC, Olgmuzalev13 commented on source/format.js
> +		let maxLen = 0
Да, но ведь тогда это будет алгоритмически гораздо хуже, так я за один проход по массиву нахожу и максимум и выполняю необходимые операции, а так max будет проходить по массиву и spread тоже. maxLen действительно можно инициализировать вне цикла, но тогда все равно придется обнулять его значения на каждой итерации цикла, а это просто 2 строчки вместо 1

2024-09-10 20:49 UTC, Olgmuzalev13 commented
Вроде остальное исправил.

2024-09-11 13:28 UTC, Olgmuzalev13 commented on source/format.js
> +		}
Почему-то исчез коммент, но я писал что не нашел у slice возможности указать шаг, а перебор лишних элементов алгоритмически хуже, а выравниваю я каждую колонку отдельно.

2024-09-13 08:42 UTC, Gallaann requested changes
Будь добр, дополни еще коммент условием задачи

2024-09-13 08:42 UTC, Gallaann commented on index.html
> -<script src="tests/max.js"></script>
Все же оставь этот файл, а еще было бы неплозо прикрепить к комментарию ПРа результат тестирования

2024-09-13 08:42 UTC, Gallaann commented on index.html
> +
Удали этот пробел, он не очень нужен тут

2024-09-13 08:42 UTC, Gallaann commented on source/format.js
> +let format = (input, columns) => {
Хорошо, а дополни еще про `arguments`, `new` и `yield`

2024-09-13 08:42 UTC, Gallaann commented on source/format.js
> +let format = (input, columns) => {
Хорошо, давай тогда заменим на `const`. Будет нагляднее, что переменная, в данном случае функция, не изменяется в процессе работы кода

2024-09-13 08:42 UTC, Gallaann commented on source/format.js
> +	let output = Array(Math.ceil(input.length / columns)).fill("");
Да, твой тейк понятен. Можем оставить так, я в угоду читаемости готов пожертвовать немного скоростью работы

2024-09-13 08:42 UTC, Gallaann commented on tests/format.js
> +	QUnit.test('format работает правильно c количеством колонок равным количеству чисел', function (assert) {
Перевода строки в коде между тестами)

2024-09-13 08:42 UTC, Gallaann commented on source/format.js
> +		let maxLen = 0
Не понимаю) Максимальная длина всегда одна, зачем ее несколько раз считать? Про 2 прохода согласен. В таком случае можем воспользоваться `reduce`, это будет 1 проход

Мы все же пишем не алгоритм для решения олимпиадной задачки, который больше не будет читаться, а продакшн код, который затем многократно переписывается и дополняется, а читают его другие люди в том числе, а не только оригинальный разработчик, поэтому давай писать код с меньшей когнитивной нагрузкой

2024-09-13 12:16 UTC, Gallaann commented on source/format.js
> +		let maxLen = 0
Разный код стайл, в js принято использовать camelCase

2024-09-13 15:42 UTC, Olgmuzalev13 commented on source/format.js
> +let format = (input, columns) => {
Ну еще в их контексте не определен arguments, их нельзя вызывать с помощью new, и внутри них нельзя использовать yield

2024-09-13 16:25 UTC, Olgmuzalev13 commented on source/format.js
> +		let maxLen = 0
Максимальная длинна своя для каждой колонки же, поэтому приходится вычислять ее каждый раз в цикле.
![image](https://github.com/user-attachments/assets/3b05a254-0b38-4498-b608-c2817e969a59)
вот, это видно в тесте 3 который писал не я.
И поэтому не получится формировать сразу строки, а только колонки, и тогда придется в отдельном проходе проверять все элементы на тип данных и максимум длинны, ну или запихать всё это в одну функцию вызываемую над аргументом в reduce, но это будет тоже самое что сейчас написано только вместо for foreach и reduse но дополнительная функция внутри format внутри которой будет проверка к какой колонке принадлежит элемент и все следующие проверки.
Я конечно могу попробовать но это же будет тоже самое если не хуже
![image](https://github.com/user-attachments/assets/8521ada8-259d-49ce-ab77-a48d94fa2168)
как то так только последние for еще в reduce превратить, но я не знаю пока как, но это уже хуже того что у нас есть, разве нет? Что с алгоритмической точки зрения, что с точки зрения читаблеьности

2024-09-13 16:27 UTC, Olgmuzalev13 commented
![image](https://github.com/user-attachments/assets/dff79c44-bc11-44c9-8e5c-0a33a938f028)
вот результаты тестирования

2024-09-13 21:53 UTC, Olgmuzalev13 commented
Внес дополнительные изменения полностью избавившись от циклов for
Разделил код на логические блоки
Заменил let на const  у ссылочных типов так как содержимое по ссылке все еще может быть изменено, а сама ссылка не должна меняться

2024-09-14 18:46 UTC, Olgmuzalev13 commented
Заменил for each на every
Заменил 2 for each на map+reduce
Добавил проверку на целое число

2024-09-15 10:20 UTC, Gallaann requested changes

2024-09-15 10:20 UTC, Gallaann commented on source/format.js
> +	})
1. Переименуем `maxOfColumns` в `maxWidthOfColumns` или просто в `maxWidths`
2. Зачем самому считать максимум? Можем воспользоваться `Math.max`

```suggestion
	const maxWidths = new Array(columns).fill(0);  
    input.forEach((number, index) => {  
        const columnIndex = index % columns;  
        maxWidths[columnIndex] = Math.max(maxWidths[columnIndex], String(number).length);  
    }); 
```

2024-09-15 10:20 UTC, Gallaann commented on source/format.js
> +	return columsArr[0].join("\n")
Какая-то жесть

За место этого могу предложить строить массив `rows` из `row` с `i-того` по `i-тый + columns` с помощью `slice`, а затем форматирование `row` с `padstart` и все дела, который ты так же пушнешь в `rows`. А сам `rows` склеишь символом `\n`, чтобы получить итоговый результат

2024-09-15 10:20 UTC, Gallaann commented on source/format.js
> +}
Перед каждым пробелом добавь перевод строки плиз, все еще сливается в одну кажу, а не отдельные логические блоки

2024-09-15 10:22 UTC, Gallaann commented on index.html
> -
Убери этот дифф, плиз

2024-09-15 12:00 UTC, Olgmuzalev13 commented
Всё исправил

2024-09-15 12:16 UTC, Gallaann requested changes
Последний рубеж

2024-09-15 12:16 UTC, Gallaann commented on source/format.js
> +    }
Что-то с табами, криво в саджест вставились

2024-09-15 12:16 UTC, Gallaann commented on source/format.js
> +    });
Что-то с табами, криво в саджест вставились

2024-09-15 12:16 UTC, Gallaann commented on source/format.js
> +	rows.forEach((element, iter) => {rows[iter]=element.join(" ")})
Можем подсобрать все вместе и дать пространство блоку внутри `for` с помощью пробелов после `;`

```suggestion
	const rows = [];
    for (let i = 0; i < input.length; i += columns) {
        const row = input.slice(i, i + columns); // Извлекаем подмассив
        rows.push(row.map((number, index) => (String(number).padStart(maxWidths[index]))).join(' '));
    }
```

2024-09-15 12:40 UTC, Gallaann approved these changes
Ура! LGTM

2024-09-16 15:26 UTC, Sarafa2n commented on source/format.js
> +	}
почему не forEach или every

2024-09-16 15:26 UTC, Sarafa2n commented on source/format.js
> +	});
можно заменить на map или reduce

2024-09-16 15:26 UTC, Sarafa2n commented on source/format.js
> +	}
reduce

2024-09-16 15:27 UTC, Sarafa2n commented on source/format.js
> +	return rows.join("\n")
одинарные кавычки бы

2024-09-16 16:32 UTC, Olgmuzalev13 commented
Поменял

2024-09-16 16:40 UTC, Olgmuzalev13 commented
Поменял

2024-09-16 16:46 UTC, closed without merging