HW0_Угаров_Руслан
frontend-park-mail-ru/homework_2024_2 pull request #39
Opened 2024-09-07 18:18 UTC by Rusy13

2024-09-07 20:40 UTC, Shureks-den commented
Привет! Меня зовут Саша и я буду проверять твое дз

Для начала напиши условие в пр и приложи результатов тестов

2024-09-07 20:46 UTC, Shureks-den requested changes

2024-09-07 20:46 UTC, Shureks-den commented on source/plain.js
> +'use strict';
Расскажи для чего эта строка? Что будет если написать ее?

2024-09-07 20:46 UTC, Shureks-den commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
Какие способы объявления переменных ты знаешь помимо `const`, в чем их разница и почему тут лучше использовать `const`?

2024-09-07 20:46 UTC, Shureks-den commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
Как еще можно задать функции, в чем  отличия между разными способами

2024-09-07 20:46 UTC, Shureks-den commented on .gitignore
> +*.iml
Добавь отступ в конец файлика

2024-09-07 20:46 UTC, Shureks-den commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
Давай опишем функцию при помощи JSDoc

2024-09-07 20:46 UTC, Shureks-den commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
А если мы вызовем функцию с переменной `undefined`? Давай обработаем ситуации, когда arr может прийти не массивом и явно подскажем, что, что-то идет не так

2024-09-07 20:46 UTC, Shureks-den commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
Но решение крутое! Не придраться)

2024-09-07 20:48 UTC, Shureks-den commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
И давай еще вопросик) Какие типы данных ты знаешь в js, чем они отличаются между собой, кроме очевидного, что у них разные методы

2024-09-08 10:04 UTC, Rusy13 commented on source/plain.js
> +'use strict';
Активация строгого режима, который подразумевает запрет использования необъявленных переменных, дублирование параметров функции, использование некоторых устаревших синтаксисов
Если не написать use strict JavaScript будет работать в "нестрогом" режиме, где многие из этих проверок не применяются.

2024-09-08 10:05 UTC, Rusy13 commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
var и let
Переменная, объявленная через var, имеет функциональную область видимости или глобальную область видимости, если объявлена вне функции. Она может быть переопределена и перезаписана.
Переменная, объявленная через let, имеет блочную область видимости и может быть изменена, но не переобъявлена в той же области видимости.
Переменная, объявленная через const, также имеет блочную область видимости, но она не может быть изменена после инициализации.

Скорее всего лучше использовать const тк функция plain не изменяется после инициализации.

2024-09-08 10:05 UTC, Rusy13 commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
1) 
Function Declaration (Объявление функции)
Имеет имя и определяется с помощью ключевого слова function
Function Expression (Функциональное выражение)
Функция присваивается переменной
Arrow Function (Стрелочная функция)
Более краткий синтаксис

2024-09-08 10:42 UTC, Rusy13 commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
Типы данных в JS делятся на примитивные типы и сложные типы(объекты)
Отличия:
Примитивы передаются по значению, а объекты — по ссылке
Примитивы неизменяемы (immutable), а объекты могут изменяться (mutable)
Объекты имеют методы и свойства, в то время как примитивы могут быть автоматически обернуты в объекты (String, Number, и т.д.) для доступа к методам


Примитивные типы:
string — строки
number — числа
boolean — логические значения true или false
null — специальное значение, указывающее на "отсутствие значения"
undefined — значение переменной, которая была объявлена, но не инициализирована
symbol — уникальные и неизменяемые идентификаторы
bigint — числа произвольной точности

Сложные типы (объекты):
object — объекты и массивы
Функции также являются объектами в JavaScript.

2024-09-08 13:05 UTC, Shureks-den commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
У стрелочных функций есть еще одно важное отличие, даю подсказку: что такое `this`?

2024-09-08 13:06 UTC, Shureks-den requested changes

2024-09-08 13:06 UTC, Shureks-den commented on source/plain.js
> +};
Отступ потерялся в конце файла

2024-09-08 13:33 UTC, Rusy13 commented on source/plain.js
> +const plain = arr => arr.reduce((acc, v) => acc.concat(Array.isArray(v) ? plain(v) : v), []);
они не имеют своего собственного контекста this

2024-09-08 15:31 UTC, Shureks-den approved these changes

2024-09-08 19:19 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-08 19:19 UTC, DPeshkoff commented on source/plain.js
> +const plain = arr => {
Давай обернем в () - так будет лучше потом (без спойлеров курса, хе-хе)

2024-09-08 19:19 UTC, DPeshkoff commented on source/plain.js
> +};
Давай сделаем перенос на новую строчку в конце файла - \n

2024-09-08 19:19 UTC, DPeshkoff commented on tests/plain.js
> +		assert.deepEqual(plain([ [ [ 1 ], [ 2 ] ], [ [ 3 ] ], [ [ [ 4 ] ] ] ]), [ 1, 2, 3, 4 ]);
Давай добавим тесты на некорректный ввод

2024-09-13 07:00 UTC, DPeshkoff approved these changes

2024-09-13 07:01 UTC, closed without merging