Куренков Дмитрий
frontend-park-mail-ru/homework_2024_2 pull request #4
Opened 2024-08-27 02:51 UTC by KurenkovDmitry

Выполнил:
Куренков Дмитрий Александрович WEB21 (вариант 14)

Условие:
Мы написали юнит-тесты на некоторую функцию, но саму функцию не реализовали. Тебе необходимо её реализовать, а так же написать на неё парочку дополнительных тестов. Готовое решение необходимо закоммитить, запушить и отправить нам в пулл-реквесте. Не забудь представиться (фамилии и имени будет достаточно)!

За это ДЗ можно получить до 5 баллов. Оцениваться будет качество и оптимальность кода. Чтобы получить максимальный балл, необходимо выполнить его вовремя, при этом все тесты должны проходить. Код тестов поможет тебе лучше понять условие.

Задание:
Напишите функцию set, которая получает путь к вложенному свойству объекта и устанавливает значение в это свойство

2024-08-29 18:38 UTC, mafin1799 commented
Привет)
Поздравляю с переходом на 2 семестр и началом лучшего курса по Фронтенд-разработке
Меня зовут Никита, я буду проверять твое ДЗ №0

Ниже список общих замечаний. Подробные комментарии смотри в коде
- [ ] Некорректное название ПРа. Оно должно быть «Фамилия Имя студента». 
- [ ] В комментарий к ПР можно добавить условие задачи и вариант
- [ ] Запушено что-то лишнее (.idea)
- [ ] Лишние изменения в index.html (там) должна добавиться одна строка кода на 16 строке, без смешения строк

2024-08-29 19:09 UTC, mafin1799 commented on source/set.js
> +    const pathArray = path.replace(/\[(\w+)\]|\["(.+?)"\]/g, '.$1$2').split('.').filter(Boolean);
Нужно добавить дополнительные проверки, твой код не должен падать как можно чаще. 

Давай сделаем вид что в функцию можно передать объект как null, undefined, [], "aaaa", 123 и с остальными аргументами функции тоже самое

2024-08-29 19:09 UTC, mafin1799 commented on tests/set.js
> +        set(obj, 'a.b.c', 4);
Тестов написал много, это очень хорошо))

Возможно я не заметил один кейс.

Пусть будет объект { a: { b: { c: 3 } }
А ты сделаешь set(obj, 'a', 2);

2024-08-29 19:09 UTC, mafin1799 commented on source/set.js
> +                ? (/^\d+$/.test(key) ? [] : {}) : acc[prev_key];
В проверку можно добавить instanceof

2024-08-29 19:09 UTC, mafin1799 commented on source/set.js
> +                throw new Error("Addressing an array element with a negative key is invalid");
Про виды исключений можно прочитать тут https://doka.guide/js/errors/

2024-08-30 05:31 UTC, mafin1799 commented on source/set.js
> +'use strict';
В каких случаях она нужна, а в каких не очень?)

2024-08-31 20:51 UTC, mafin1799 commented on source/set.js
> +'use strict';
При каких условиях он включается автоматически?

2024-08-31 20:53 UTC, mafin1799 commented on source/set.js
> +    const pathArray = path.replace(/\[(\w+)\]|\["(.+?)"\]/g, '.$1$2').split('.').filter(Boolean);
Суть в том, что через год ты вообще не поймешь зачем это написал. Поэтому лучше поддерживать читаемость кода. 


Есть проекты над которыми можно работать и поддерживать десятилетия))))

2024-08-31 20:55 UTC, mafin1799 commented on source/set.js
> +        return acc[key] = (index === pathArray.length - 1) ? value : (typeof acc[key] !== 'object' || acc[key] === null)
Почему нельзя == для массивов. 
Как их тогда сравнивать?

2024-08-31 20:55 UTC, mafin1799 commented on source/set.js
> +        return acc[key] = (index === pathArray.length - 1) ? value : (typeof acc[key] !== 'object' || acc[key] === null)
И чем тогда является массив

2024-08-31 20:56 UTC, mafin1799 commented on source/set.js
> +    let acc = obj;
У тебя тут и есть прямое обращение, так как ты приравниваешь acc = obj
Тут просто копируется ссылочка

2024-08-31 20:56 UTC, mafin1799 commented on source/set.js
> +    let acc = obj;
Расскажи про все способы копирования объектов в js какие найдешь

2024-08-31 20:58 UTC, mafin1799 commented on source/set.js
> +                ? (/^\d+$/.test(key) ? [] : {}) : acc[prev_key];
Н когда нельзя быть уверенным что все хорошо. 

Надо верить что всегда все может сломаться по любой причине

2024-08-31 20:58 UTC, mafin1799 commented on tests/set.js
> +        set(obj, 'a.b.c', 4);
Оки мог не заметить
Давай на ты. И с преподавателями также)))

2024-08-31 21:03 UTC, mafin1799 commented on source/set.js
> +/* Наиболее короткое решение, однако по скорости в среднем немного проигрывает, хотя разница и не значительна
Тут суть в том
Что когда делаешь тасочку
Нужно предоставить решение
И ты сам выбираешь какое лучше, знаешь почему оно лучше и тд, если от тебя не требуется иного

2024-08-31 21:05 UTC, mafin1799 commented on source/set.js
> +const set = (obj, path, value) => {
https://learn.javascript.ru/function-declaration-expression?ysclid=m0imrffdly14146448

Виде небольшую путаницу

В основном рассматриваем стрелочные функции
Function definition вот это через function имеет особенность в дом что обрабатывается в первую очередь и доступно до объявления
Function expression  это как раз про анонимки

2024-08-31 21:07 UTC, mafin1799 commented on source/set.js
> +            throw new Error("Addressing an array element with a negative key is invalid");
Регулярен в коде понижают читаемость.
Их лучше вынести 
Объединить в какой либо набор 

Иначе у теб будет 100500 регулярок в проекте на 200000+ строк кода и будет плаки плаки

2024-09-01 04:03 UTC, mafin1799 commented on source/set.js
> +        return acc[key] = (index === pathArray.length - 1) ? value : (typeof acc[key] !== 'object' || acc[key] === null)
JSON stringify точно не лучший метод.

В данном случае все будет ок.
У тебя цифри 

А что будет если у тебя окажется массив объектов со значениями полей в виде функций.

Пример из реальной жизни
Мапа колбеков для подписок json rpc 
Для какого нибудь сокета 

Вот там как раз массивы объектов с функциями и прочими прелестями.

Нужно нарыть инфу как лучше копировать объект в js
Массив это тоже объект так что ищи про объекты)))

2024-09-01 04:05 UTC, mafin1799 commented on source/set.js
> +    let acc = obj;
А ок.
Вначале не понял, а потом как понял)))

2024-09-01 06:06 UTC, mafin1799 commented
Проверь наличие пустой строки в конце js файлов. 
Это важно.

2024-09-03 04:27 UTC, mafin1799 commented
JsDoc еще надо дописать для функции set

2024-09-03 16:59 UTC, mafin1799 commented
![image](https://github.com/user-attachments/assets/e08c95f2-1b67-40b1-b4c1-ef74c795e2db)

На вот этот вопросик ответь и готово)

2024-09-03 18:03 UTC, mafin1799 commented
Окей.

Про сравнение/копирование принимаю

Нужно только из гита убрать эти 20 файлов новых

Тебе нужны только коменты которые ты написать в set.js и всё

2024-09-03 18:18 UTC, mafin1799 approved these changes
Ну вот и всё)
У меня больше вопросов нету)

2024-09-06 17:44 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-06 17:44 UTC, DPeshkoff commented on index.html
> -
А что удалилось?) Давай починим, мы просто добавляли строчку же

2024-09-06 17:44 UTC, DPeshkoff commented on source/set.js
> +                    throw new Error("Addressing an array element with a negative key is invalid");
Одиночные кавычки лучше)

Еще можно какую-то другую [ошибку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA)

2024-09-06 17:44 UTC, DPeshkoff commented on source/set.js
> +    if (path !== '') {
Предлагаю проверять, вдруг там вообще не строка на входе

2024-09-06 17:44 UTC, DPeshkoff commented on source/set.js
> +        pathArray.forEach((key, index) => {
Какой перебирабщий метод массива умеет еще и аккумулировать?)

2024-09-06 17:44 UTC, DPeshkoff commented on tests/set.js
> +        let obj = { a: { b: {} } };
а в чем отличие let от const? Можем ли мы свойства изменять?

2024-09-12 07:45 UTC, closed without merging