добавила код
frontend-park-mail-ru/homework_2024_2 pull request #42
Opened 2024-09-07 21:19 UTC by VikaGuryeva

2024-09-08 16:07 UTC, let-robots-reign reviewed
Привет, Вика!
Поздравляю с переходом на 2-й семестр, желаю успехов в постижении фронтенда!
Меня зовут Алексей, я дам фидбек по твоему ДЗ0. Мой контакт в Телеграме: @let_robots_reign. Можешь писать по любым вопросам.

Работа хорошая, ниже оставил немного замечаний по коду

2024-09-08 16:07 UTC, let-robots-reign commented on source/sort.js
> +        for (let prop of props) {
В чем разница между `var`, `let`, `const`? Почему здесь использовала `let`?

2024-09-08 16:07 UTC, let-robots-reign commented on source/sort.js
> +                throw new Error(`Свойство '${prop}' отсутствует у одного из объектов.`);
TypeError тут тоже больше подходит

2024-09-08 16:07 UTC, let-robots-reign commented on tests/max.js
> +
Лишние пустые строки

2024-09-08 16:07 UTC, let-robots-reign commented on tests/sort.js
> +        // Тестирование с использованием QUnit
Тут не нужно было удалять файл с тестами и создавать новый, просто дописать новые тесты в тот же файл

2024-09-08 16:09 UTC, let-robots-reign commented
Еще добавь, пожалуйста, в описание PR'а номер варианта и условие задачи

2024-09-08 17:34 UTC, VikaGuryeva commented on source/sort.js
> +        for (let prop of props) {
Разница в их области видимости: 
1) var - область видимости переменных var ограничивается либо функцией, либо, если переменная глобальная, то скриптом. Такие переменные доступны за пределами блока. «var» допускает повторное объявление 

2) let - блочной областью видимости, т.е. видна только внутри блока, где объявлена (например, внутри цикла или условия). Если в блоке кода дважды объявить одну и ту же переменную let, будет ошибка.
3) const -  как и let, обладает блочной областью видимости. Не может быть переназначена (её значение не может быть изменено после инициализации), но это относится только к примитивам (например, числа, строки). Если же это объект или массив, его внутренние свойства можно изменять.


Здесь let подходит для цикла, то есть не должна быть доступна вне

2024-09-08 17:40 UTC, VikaGuryeva commented on source/sort.js
> +'use strict';
"use strict" — это директива в JavaScript, которая активирует строгий режим (strict mode) для всего скрипта или для отдельной функции.

1) Строгий режим заменяет исключениями некоторые ошибки, которые интерпретатор JavaScript ранее молча пропускал. 
2) Строгий режим исправляет ошибки, которые мешали движкам JavaScript выполнять оптимизацию — в некоторых случаях код в строгом режиме может быть оптимизирован для более быстрого выполнения, чем код в обычном режиме.

2024-09-08 20:52 UTC, let-robots-reign reviewed
Очень оперативно внесла правки, еще несколько осталось

2024-09-08 20:52 UTC, let-robots-reign commented on source/sorting.js
> +
После JSDoc не ставим пустую строчку по той же причине, что писал в изначальном комментарии - IDE может не подхватить документацию

2024-09-08 20:52 UTC, let-robots-reign commented on source/sorting.js
> +            if (result !== 0) return result; // Если уже не равно, возвращаем результат
Тут лучше обернуть в фигурные скобки, есть [памятка](https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda) по code style

2024-09-08 20:52 UTC, let-robots-reign commented on source/sorting.js
> +            if (result !== 0) return result; // Если уже не равно, возвращаем результат
Также можно `if (result) { ... }`

2024-09-08 20:52 UTC, let-robots-reign commented on tests/sorting.js
> +        QUnit.module("Sorting Function Tests", () => {
Тут отступы и уже написанные в файле тесты должны остаться без изменений

2024-09-08 20:55 UTC, let-robots-reign commented
Еще хорошо бы добавить пустые строки в конце js-файлов. Это такое "правило хорошего тона", вот [тут](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file) есть несколько причин, почему разработчики условились так делать

2024-09-08 21:07 UTC, let-robots-reign commented on source/sort.js
> +        for (let prop of props) {
> но это относится только к примитивам

Ну объектные типы тоже нельзя переназначить, аналогично с примитивами. Другое дело, что существуют методы типа `push` у массива, которые не переназначают значение, но сам массив меняют

Есть разные подходы, что выбрать, let или const (тут команда решает). Но чаще для переменных, которые не планируется менять, как в данном случае, все-таки используют const.

2024-09-09 04:40 UTC, VikaGuryeva commented on tests/sorting.js
> +        QUnit.module("Sorting Function Tests", () => {
не понимаю, но ведь в том файле тесты, написанные для max, ты имеешь в виду туда внести тесты?

2024-09-09 04:44 UTC, VikaGuryeva commented on tests/sorting.js
> +        QUnit.module("Sorting Function Tests", () => {
не понимаю, но ведь это тесты написанные не мной, их оставить?

2024-09-09 09:17 UTC, let-robots-reign reviewed
Уже все хорошо, только несколько мелочей осталось


P.S. Еще пустую строчку в конце файла с тестами добавить

2024-09-09 09:17 UTC, let-robots-reign commented on source/sorting.js
> +    }
У этой функции лишние отступы

2024-09-09 09:17 UTC, let-robots-reign commented on source/sorting.js
> +    let result = [];
Давай `const` вместо `let`

2024-09-09 09:17 UTC, let-robots-reign commented on source/sorting.js
> +    }
Вот тут все еще не объединено условие

2024-09-09 09:17 UTC, let-robots-reign commented on tests/sorting.js
> +
Лишние отступы, в diff'е не должно быть видно, будто ты удаляешь 123 строчки

2024-09-09 15:02 UTC, let-robots-reign commented
И последний вопрос к тебе: какие ты знаешь способы объявить функцию и в чем между ними различия?

2024-09-09 15:25 UTC, VikaGuryeva commented on tests/sorting.js
> +
а как это сделать, он же автоматически показывает, что удалены строчки?

2024-09-09 15:57 UTC, VikaGuryeva commented
> И последний вопрос к тебе: какие ты знаешь способы объявить функцию и в чем между ними различия?

1 вариант - декларативное объвление
function имяФункции(параметры ) {
  // Тело функции
};

2 вариант -  анонимная функция -та же декларативная функция, но это функция без имени, так как функция присваивается переменной

3 вариант - стрелочная функция 
const имяФункции = (параметры) => {
  // Код функции
};

2024-09-09 21:59 UTC, let-robots-reign approved these changes
У меня вопросов не осталось, ставлю аппрув

2024-09-09 22:01 UTC, let-robots-reign commented on tests/sorting.js
> +
Отступы поправили, но гит все еще показывает, что удаляется 123 строчки при внешне идентичном контенте (вплоть до пробелы/табы). Причину пока не выяснили

2024-09-13 07:22 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа отличная, накидаю немного вопросиков)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-13 07:22 UTC, DPeshkoff commented on tests/sorting.js
> +	});
Тут изменения, кажется, не нужны

2024-09-13 07:32 UTC, let-robots-reign commented on tests/sorting.js
> +	});
Привет, тут странная ситуация, я написал коммент

> Отступы поправили, но гит все еще показывает, что удаляется 123 строчки при внешне идентичном контенте (вплоть до пробелы/табы). Причину пока не выяснили

2024-09-14 10:34 UTC, DPeshkoff approved these changes

2024-09-14 10:34 UTC, closed without merging