Руденко Александр
frontend-park-mail-ru/homework_2024_2 pull request #43
Opened 2024-09-08 11:14 UTC by source-Alexander-Rudenko

hw0 done, 6 additional tests added

2024-09-11 13:09 UTC, AlexandraSmirnova requested changes
Привет! 
Подключи, пожалуйста, свой код в index.html, чтобы видеть результаты тестов

2024-09-14 08:23 UTC, source-Alexander-Rudenko commented on source/filter.js
> +    function changeHTML(text) {
1. **Объявление функции**
самое классическое объявление
```js
function sayHello() {
  return `Hello`;
}
console.log(sayHello());  
```
2. **Функциональное выражение**
Функция может быть присвоена переменной.
```js
const sayHello = function() {
  return `Hello`;
};

console.log(sayHello()); 
```
3. **Стрелочная функция**
краткое объявление, не имеет своего контекста `this`
```js
const sayHello = (name) => `Hello`;

console.log(sayHello();  
```
4. **IIFE (Immediately Invoked Function Expression) .**
функция, которая выполняется сразу же после того, как она была определена
```js
(function() {
  console.log(`Hello`);
})();
```

2024-09-14 08:35 UTC, source-Alexander-Rudenko commented on source/filter.js
> +function filter(input, allowedTags) {
мой код работает с строгом режиме
В строгом режиме нельзя:
- использовать переменные без их объявления;
- дублировать имена свойств в объектах;
- дублировать параметры функций;
- удалять переменные, функции и аргументы;
- использовать зарезервированные слова;
- использовать устаревшие конструкции;

По умолчанию код в JS выполняется в sloppy mode (небрежном режиме).
Режим позволяет гибко писать код, но это может привести к неожиданным ошибкам и проблемам с безопасностью.

2024-09-14 15:33 UTC, AlexandraSmirnova commented on source/filter.js
> +function filter(input, allowedTags) {
Если по умолчанию код работает в "небрежном режиме", то как ты отключаешь поведение по умолчанию?

2024-09-14 15:49 UTC, AlexandraSmirnova requested changes

2024-09-14 15:49 UTC, AlexandraSmirnova commented on source/filter.js
> +    function changeHTML(text) {
Давай перепишем функции функции в твоем решении на их краткую форму - стрелочные

2024-09-14 15:49 UTC, AlexandraSmirnova commented on source/filter.js
> +    function changeHTML(text) {
Функция filter получилась достаточно объемная, давай вынесем за ее пределы константы и функции. Так при вызове функции они не будут каждый раз создаваться

2024-09-14 15:49 UTC, AlexandraSmirnova commented on source/filter.js
> +        if (allowedTags.includes(tagName.toLowerCase())) {
Возможно ли тут использовать тернарный оператор? Если да, давай заменим

2024-09-14 15:49 UTC, AlexandraSmirnova commented on tests/filter.js
> +
лишняя пустая строка

2024-09-14 15:49 UTC, AlexandraSmirnova commented on tests/filter.js
> +	});
Не хватает проверок на различные варианты allowedText. Что будет, если я там передам например число? А если первым параметром число или null.  Давай добавим :)

2024-09-14 15:49 UTC, AlexandraSmirnova commented on index.html
> +		<meta charset="utf-8" />
В этом файле и в тестах для отступов используются табы, предлагаю в filter.js тоже отступы сделать табами, поскольку важно соблюдать единый стиль кода. На эту тему рекомендую к прочтению: https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2024-09-16 07:25 UTC, source-Alexander-Rudenko commented on source/filter.js
> +function filter(input, allowedTags) {
При помощи директивы` 'use strict';`  которая включает строгий режим выполнения кода. Директиву включем в начале скрипта или функции, чтобы она начала действовать.

2024-09-16 07:52 UTC, source-Alexander-Rudenko commented on source/filter.js
> +    function changeHTML(text) {
Пооправил

2024-09-16 07:52 UTC, source-Alexander-Rudenko commented on source/filter.js
> +    function changeHTML(text) {
Пооправил

2024-09-16 07:52 UTC, source-Alexander-Rudenko commented on source/filter.js
> +        if (allowedTags.includes(tagName.toLowerCase())) {
Пооправил

2024-09-16 07:52 UTC, source-Alexander-Rudenko commented on tests/filter.js
> +
Пооправил

2024-09-16 07:52 UTC, source-Alexander-Rudenko commented on tests/filter.js
> +	});
Пооправил

2024-09-16 08:00 UTC, source-Alexander-Rudenko commented
оказывется линтером форматировать супер приятно)

2024-09-17 08:52 UTC, AlexandraSmirnova commented
Не проходят тесты
![Uploading Снимок экрана 2024-09-17 в 11.51.55.png…]()

2024-09-17 08:54 UTC, AlexandraSmirnova commented on source/filter.js
> +function filter(input, allowedTags) {
Я не вижу этой дерективы у тебя в filter.js, давай включим

2024-09-17 09:05 UTC, AlexandraSmirnova requested changes

2024-09-17 11:16 UTC, source-Alexander-Rudenko commented
![image](https://github.com/user-attachments/assets/0b4a79aa-e8db-4d1e-a23d-69f4bc007a8b)
у меня не 8 тестов а 15, они все проходят

2024-09-17 16:15 UTC, source-Alexander-Rudenko commented on source/filter.js
> +const specialChars = {
поправил

2024-09-17 16:15 UTC, source-Alexander-Rudenko commented on tests/filter.js
> +});
поправил

2024-09-18 10:04 UTC, AlexandraSmirnova requested changes
Проверила, тесты работают, была просто не в той ветке :) пара минорных замечаний осталось, а так все ок

2024-09-18 18:00 UTC, source-Alexander-Rudenko commented on source/filter.js
> +const filter = (input, allowedTags) => {
написал

2024-09-19 09:13 UTC, Sarafa2n commented on source/filter.js
> +	input = typeof input === "string" ? input : input == null ? "" : String(input);
вот это сложно читать, давай хотяб раскидаем это по строчкам

2024-09-19 09:40 UTC, source-Alexander-Rudenko commented on source/filter.js
> +	input = typeof input === "string" ? input : input == null ? "" : String(input);
поправил

2024-09-19 09:42 UTC, closed without merging