Шаклеина Дана
frontend-park-mail-ru/homework_2024_2 pull request #44
Opened 2024-09-08 11:55 UTC by AnnHarvard

2024-09-08 11:59 UTC, AnnHarvard commented
Вариант 5. Напишите функцию `chess`, которая рисует ASCII-шахматрую доску размером N*N символов из звёздочек (в левом верхнем углу всегда стоит звёздочка)

2024-09-10 11:11 UTC, Gallaann requested changes
Привет, меня зовут Вова, я буду проверять твое ДЗ №0. Поздравляю с переходом на 2-ой семестр. По любым вопросам можешь писать в [ТГ](https://t.me/Gallaaan)

Хорошее решение получилось, но можем его еще немного улучшить и хотелось бы услышать от тебя ответы на вопросы

А вот пока мемчик для поднятия настроения
![image](https://github.com/user-attachments/assets/d89543f3-9bf6-4da6-a02d-90b5a7c3a753)

2024-09-10 11:11 UTC, Gallaann commented on source/chess.js
> + */
Супер, что написала JSDoc, только давай дополним его еще выбрасываемыми ошибками
```suggestion
/**
 * Функция для рисования ASCII-шахматной доски размера N x N символов.
 *
 * @param {number} N - Размер шахматной доски (число строк и столбцов)
 * @returns {string} - Строка, представляющая шахматную доску
 * @throws {TypeError} - condition 1
 * @throws {TypeError} - condition 2
 * @throws {TypeError} - condition 3
 */
```

2024-09-10 11:11 UTC, Gallaann commented on source/chess.js
> +'use strict';
Расскажешь для чего нужна эта директива?

2024-09-10 11:11 UTC, Gallaann commented on source/chess.js
> +const chess = (N) => {
Какие еще есть способы объяления функций и чем они отличаются?

2024-09-10 11:11 UTC, Gallaann commented on source/chess.js
> +  let board = '';
Какие еще способы объявления переменных есть и чем они отличаются?)

2024-09-10 11:11 UTC, Gallaann commented on source/chess.js
> +    for (let j = 0; j < N; j++) {
Расскажи какие еще знаешь способы объявления циклов. Как можно итерироваться по объекту? Массиву? Строке?

2024-09-10 11:11 UTC, Gallaann commented on source/chess.js
> +      board += (i + j) % 2 === 0 ? '*' : ' ';
Напиши, пожалуйста, чем отличается `==` от `===`)

2024-09-10 11:11 UTC, Gallaann commented on tests/chess.js
> +	});
Круто, что добавила новых тестов, но давай еще добавим. Что будет, если в функцию передать undefined, null, объект, массив

2024-09-12 20:34 UTC, AnnHarvard commented on source/chess.js
> +'use strict';
Эта директива активирует строгий режим выполнения кода. Он помогает избежать ошибок и делает код более безопасным. Например, при строгом режиме нельзя создавать глобальные переменные, удалять переменные, функции, аргументы функций, также нельзя использовать зарезервированные слова и др.

2024-09-13 07:10 UTC, AnnHarvard commented on source/chess.js
> +const chess = (N) => {
В моем коде использована стрелочная функция - она полезна тем, что сохраняет контекст окружения, а не создает свой собственный. Это полезно, когда нужно сохранить контекст и избежать ошибок. 
Также функцию можно объявить при помощи ключевого слова function - полезно использовать, кг=огда не планируем записывать функцию в переменную или передавать в качестве аргмуента. Можем использовать функцию в любом месте, даже до ее фактического объявления (хостинг функции).
function chess() {
   ...
}
Для функции, которую хотим записать в переменную нужно использовать функциональное выражение. Функция, объявленная таким способом, будет доступна только после ее объявления. Чаще всего это анонимная функция, тк имя опускается. 
const name = function () {
   ...
}

2024-09-13 07:33 UTC, AnnHarvard commented on source/chess.js
> +    for (let j = 0; j < N; j++) {
Есть циклы с условиями: while и do .. while.
Цикл for .. of подходит для итерабельных объектов (массивы, строки, мапы).
Цикл for .. in используется для перебора всех перечисляемых свойств объекта.

2024-09-13 07:36 UTC, AnnHarvard commented on source/chess.js
> +      board += (i + j) % 2 === 0 ? '*' : ' ';
Оператор == - оператор нестрогого равенства. Сравнивает два значения, выполняя автоматическое приведение типов, если они различаются. 5=='5' - это true
Оператор === - оператор строго равенства. Сравнивает без приведения типов. 5==='5' - это false.

2024-09-13 07:58 UTC, AnnHarvard commented on source/chess.js
> + */
добавила

2024-09-13 07:59 UTC, AnnHarvard commented on tests/chess.js
> +	});
добавила

2024-09-13 07:59 UTC, AnnHarvard commented on source/chess.js
> +  }
исправила

2024-09-13 12:34 UTC, Gallaann requested changes

2024-09-13 12:34 UTC, Gallaann commented on source/chess.js
> +  }
Давай все же проверять на `typeof number` и `instanceof Number`, чтобы понимать, что число или не число, а то у тебя там в тестах null проходит эту проверку)

2024-09-13 12:34 UTC, Gallaann commented on source/chess.js
> +  let boardArray = [];
Давай заменим на `const`, потому что сама переменная меняться не будет, меняется ее наполненность

2024-09-13 12:34 UTC, Gallaann commented on source/chess.js
> +  for (let i = 0; i < size; i++) {
Расскажешь какие способы прохождения в цикле еще есть? Например, как можно итерироваться по строке, по объекту, по массиву?

2024-09-13 12:34 UTC, Gallaann commented on source/chess.js
> +  }
Тут бы использовать только массив, а не склеивать строки на месте, вот можно почитать тут
https://vk.com/@we_use_js-effektivnaya-rabota-so-strokami-v-javascript

2024-09-13 21:19 UTC, Gallaann requested changes
Микроправка и от меня будет аппрув

2024-09-13 21:19 UTC, Gallaann commented on source/chess.js
> +  }
А ты пробовала без этого условия запускать функцию, передав на вход new Number? Подумай над этим)

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/6e65840a-4eb2-4b0c-a38b-4fbbf3df5e68">

2024-09-13 21:37 UTC, Gallaann approved these changes
Lgtm)

2024-09-14 10:35 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-14 10:35 UTC, DPeshkoff commented on source/chess.js
> +  if (isNaN(size)) {
чем isNaN отличается от Number.isNaN? Почему тут использовала именно эту?

2024-09-16 10:34 UTC, AnnHarvard commented on source/chess.js
> +  if (isNaN(size)) {
isNaN() сначала пытается преобразовать значение в число (isNaN() можно сравнить с ==, а Number.isNaN() с ===).  На 17 строчке я уже провожу преобразование в число и разницы не будет в этом случае что конкретно я буду использовать. Но я выбрала isNaN() из-за более короткого синтаксиса

2024-09-16 19:18 UTC, DPeshkoff approved these changes

2024-09-16 19:19 UTC, closed without merging