Беляк София - 17 вариант
frontend-park-mail-ru/homework_2024_2 pull request #45
Opened 2024-09-08 13:01 UTC by sofiabelyak

2024-09-12 13:00 UTC, rissenberg commented
Привет! Я буду твоим проверяющим ментором. Если возникнут вопросы, не стесняйся писать мне в [телеграм](https://t.me/PassPort_Guardian), постараюсь оперативно ответить!

2024-09-12 16:09 UTC, rissenberg requested changes
Исправь эти замечания и отпиши мне в тг - постараюсь ответить как можно скорее!

2024-09-12 16:09 UTC, rissenberg commented on source/plainify.js
> +}
В конце файлов лучше оставлять пустую строку, чтобы гит не чудил

2024-09-12 16:09 UTC, rissenberg commented on tests/plainify.js
> +		assert.deepEqual(plainify("ВК - самый лучший работадатель"), "ВК - самый лучший работадатель")
работOдатель)

2024-09-13 08:58 UTC, sofiabelyak commented on source/plainify.js
> +function plainify(nested) {
Существуют три типа объявления функций 
1)традиционные функции
Ключевое слово, используем function и имя. Могут использоваться с помощью ключевого слова new. 
Работают в контексте того, как функция была вызвана. 
2) стрелочные функции 
Отличаются компактным синтаксисом и поведением this. Работают с анонимными функциями в контексте включающей их области видимости. Не могут использоваться с помощью ключевого слова new.
3) анонимные функции, объявляется так же как обычно, но без названия имени.

2024-09-14 19:06 UTC, rissenberg commented
Good to go!

2024-09-16 15:19 UTC, Sarafa2n commented on README.md
> -Мы написали юнит-тесты на некоторую функцию, но саму функцию не реализовали. Тебе необходимо её реализовать, а так же написать на неё парочку дополнительных тестов. Готовое решение необходимо закомми
а давай не удалять

2024-09-16 15:22 UTC, Sarafa2n commented on source/plainify.js
> +    if (!nested || typeof nested !== 'object') {
а если на вход будет new String, new Array, new Date

2024-09-16 18:52 UTC, sofiabelyak commented on source/plainify.js
> +        }
map для работы с массивами, а не обьектами

2024-09-16 20:59 UTC, Sarafa2n commented on source/plainify.js
> +};
пустую строку в конце файла нужно + у тебя в мр лишние изменения есть, давай их уберем

2024-09-16 21:31 UTC, closed without merging