Ксения Агеева
frontend-park-mail-ru/homework_2024_2 pull request #46
Opened 2024-09-08 13:03 UTC by ksuysshaa

2024-09-09 21:26 UTC, Gallaann commented
Привет! Поздравляю с переходом на 2-ой семестр. Меня зовут Вова, и я буду проверять твое ДЗ №0.  По любым вопросам можешь писать в [ТГ](https://t.me/Gallaaan)

А вот пока мемчик для поднятия настроения
![image](https://github.com/user-attachments/assets/4afa1e7b-502a-4e9f-8cd3-46b68acf2bf7)

2024-09-09 21:39 UTC, Gallaann requested changes
Хорошее решение получилось, давай его еще немного допилим!

2024-09-09 21:39 UTC, Gallaann commented on index.html
> -<script src="tests/max.js"></script>
Давай все-таки вернем эти строчки, они нам не мешают)

2024-09-09 21:39 UTC, Gallaann commented on source/get.js
> +
Спасибо, что написала здесь условие, очень удобно!)

2024-09-09 21:39 UTC, Gallaann commented on source/get.js
> +'use strict';
Расскажи для чего нужна эта директива

2024-09-09 21:39 UTC, Gallaann commented on source/get.js
> + * @returns {object} - Value of needed property.
По условию у тебя функция возвращает не только объект, но еще и undefined, а это примитив, давай это допишем в JSDoc

2024-09-09 21:39 UTC, Gallaann commented on source/get.js
> +}
Как поведет себя функция, если object не является объктом?

2024-09-09 21:39 UTC, Gallaann commented on source/get.js
> +const get = (object, pathToProperty) => {
Расскажешь чем отличается стрелочная функция от обычной?

2024-09-09 21:39 UTC, Gallaann commented on source/get.js
> +    let currentObject = object;
Обясни, пожалуйста, чем отличаются директивы `const`, `let` и `var` и какие в каких случаях нужно использовать или не использовать)

2024-09-09 21:39 UTC, Gallaann commented on tests/get.js
> +	});
Супер, что добавила тестов!) Давай еще допишим варианты, когда в get передали не объект

2024-09-10 05:16 UTC, ksuysshaa commented on index.html
> -<script src="tests/max.js"></script>
вернула :)

2024-09-10 05:24 UTC, ksuysshaa commented on source/get.js
> +'use strict';
при добавлении этой директивы весь сценарий работает в строгом режиме. 
к ограничениям, накладываемым строгим режимом можно отнести: выбрасывает ошибки, когда в коде используются некоторые небезопасные конструкции, выключает функции языка, которые запутывают код и потому не должны использоваться, предотвращает использование слов, которые могут быть использованы в качестве ключевых в будущем

2024-09-10 07:30 UTC, ksuysshaa commented on source/get.js
> + * @returns {object} - Value of needed property.
добавила)

2024-09-10 07:51 UTC, ksuysshaa commented on tests/get.js
> +	});
добавила)

2024-09-10 07:51 UTC, ksuysshaa commented on source/get.js
> +}
добавила проверку - теперь выкинет ошибку :)

2024-09-10 08:03 UTC, ksuysshaa commented on source/get.js
> +const get = (object, pathToProperty) => {
отличия стрелочной функции от обычной: 
1) синтаксис; 
2) время создания - стрелочная функция создается в момент выполнения кода, при вызове до объявления появится ошибка, а декларативная функция создается и доступна в любом месте кода до объявления; 
3) присваивание переменной - стрелочная функция создается и сразу присваивается переменной, которую можно использовать для вызова функции или передачи в качестве параметра, при декларативном объявлении функция не присваивается переменной; 
4) видимость - при стрелочном объявлении видимость функции ограничена областью видимости переменной, которой она присвоена, при декларативном объявлении функция становится видимой внутри этого и следующих блоков кода.

2024-09-10 08:12 UTC, ksuysshaa commented on source/get.js
> +    let currentObject = object;
Директивы const и let более новые, поэтому лучше использовать их. Использование var оправданно только если пишем код для старых браузеров. 
Используя ключевое слово let, можно объявить переменную без присвоения ей начального значения (будет равна unitialized). При помощи const нельзя объявлять переменные без значения. Значение в переменной, созданной через let, можно изменять. Стартовое значение const изменить нельзя. Оба типа переменных имеют блочную область видимости и не становятся частью глобального объекта. 

Переменные, объявленные через var, имеют функциональную область видимости. Они доступны только в пределах текущей функции или глобального объекта, если функции нет. К переменным, объявленным при помощи ключевого слова var, можно обращаться до момента объявления.

2024-09-10 08:28 UTC, Gallaann commented on source/get.js
> +const get = (object, pathToProperty) => {
Напиши еще про лексические особенности стрелочной функции, я про `this` и подобные ключевые слова

2024-09-10 08:33 UTC, Gallaann commented on source/get.js
> +    let currentObject = object;
Да, все верно. Принято объявлять через `let` только изменяемые переменные, а все остальные через `сonst`, чтобы сразу можно было понимтаь что в процессе работы будет изменяться

2024-09-10 08:34 UTC, Gallaann commented on tests/get.js
> +		assert.throws(function() {get(true, '.foo'); }, Error, 'Invalid data');
Давай еще сюда запихнем undefined, null и массив

2024-09-10 08:36 UTC, Gallaann requested changes
Давай еще одну итерацию и я ставлю аппрув

2024-09-10 13:12 UTC, ksuysshaa commented on tests/get.js
> +		assert.throws(function() {get(true, '.foo'); }, Error, 'Invalid data');
добавила)

2024-09-10 13:46 UTC, Gallaann approved these changes
Вот теперь гуд

2024-09-12 15:06 UTC, Sarafa2n commented on source/get.js
> +    let currentObject = object;
первое тут const
второе, а зачем, ты же позже кидаешь в reduce как init value

2024-09-13 10:09 UTC, ksuysshaa commented on source/get.js
> +    if (typeof pathToProperty !== 'string' || typeof object !== 'object' || !pathToProperty || Array.isArray(object)) {
добавила проверку на это, теперь выбрасывает ошибку
тест тоже добавила

2024-09-13 10:09 UTC, ksuysshaa commented on source/get.js
> +    let currentObject = object;
убрала

2024-09-14 10:36 UTC, DPeshkoff approved these changes

2024-09-14 10:36 UTC, closed without merging