Николай Сычев WEB-22 ДЗ 0 выполнено
frontend-park-mail-ru/homework_2024_2 pull request #47
Opened 2024-09-08 13:22 UTC by sychnico

Напишите функцию zip, которая будет принимать на вход несколько объектов (любое количество), и возвращать единственный объект, содержащий все поля из всех объектов. Если одно и то же поле было в нескольких объектах, необходимо оставить значение, которое встретилось раньше.

2024-09-11 21:33 UTC, let-robots-reign requested changes
Привет, Николай!
Поздравляю с переходом на 2-й семестр, желаю успехов в постижении фронтенда!
Меня зовут Алексей, я дам фидбек по твоему ДЗ0. Мой контакт в Телеграме: @let_robots_reign. Можешь писать по любым вопросам.

Ниже оставил немного замечаний по коду

2024-09-11 21:33 UTC, let-robots-reign commented on source/zip.js
> +"use strict";
Расскажи, что значит `use strict`

2024-09-11 21:33 UTC, let-robots-reign commented on source/zip.js
> +function zip(){
Какие есть способы объявить функцию и в чем разница между ними?

2024-09-11 21:33 UTC, let-robots-reign commented on source/zip.js
> +  for (let i = 0; i < arguments.length; i++){
Какие есть альтернативы использования `arguments` тут?

2024-09-11 21:33 UTC, let-robots-reign commented on source/zip.js
> +  for (let i = 0; i < arguments.length; i++){
Кажется, что этот двойной цикл выглядит очень по C++-ному, давай добавим сюда больше возможностей из JS)

2024-09-11 21:33 UTC, let-robots-reign commented on source/zip.js
> +  let c = {}
В чем разница между `var`, `let`, `const`? Почему здесь использовал `let`?

2024-09-11 21:33 UTC, let-robots-reign commented on source/zip.js
> +  let c = {}
Имя `с` не очень хорошее, как мне кажется, без чтения кода непонятно ее назначение

2024-09-11 21:33 UTC, let-robots-reign commented on source/zip.js
> +        c[key] = arguments[i][key]
Давай добавим точки с запятой в код
Есть [code style](https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda), которого хорошо бы придерживаться в проектах

2024-09-11 21:38 UTC, let-robots-reign commented
Еще несколько моментов:
1. Название PR'а должно быть "Фамилия Имя".
2. Нужно добавить JSDoc к твоей функции.
3. Не хватает обработки краевых кейсов: что если какой-то из элементов в массиве null/undefined/примитив? И обязательно добавить тесты на это.
4. Хорошо бы добавить пустые строки в конце js-файлов. Это такое "правило хорошего тона", вот [тут](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file) есть несколько причин, почему разработчики условились так делать.
5. Давай использовать одинарные кавычки

2024-09-11 21:40 UTC, let-robots-reign commented on source/zip.js
> +  for (let i = 0; i < arguments.length; i++){
Есть полезная [ссылочка](https://learn.javascript.ru/array-iteration) в качестве подсказки

2024-09-11 21:42 UTC, let-robots-reign commented on source/zip.js
> +      if (!(key in c)){
Вот тут еще хитрый момент: в чем разница между `if (key in c)` и `if (c.hasOwnProperty(key))`?

2024-09-13 09:10 UTC, sychnico commented on source/zip.js
> +  let c = {}
переменная, объявленная с помощью let видна только после объявления, var - и до, и после, const - константа, которую нельзя менять, а в остальном аналогично let

2024-09-13 09:19 UTC, sychnico commented on source/zip.js
> +  for (let i = 0; i < arguments.length; i++){
указать в скобках массив аргументов ...args

2024-09-13 09:28 UTC, sychnico commented on source/zip.js
> +function zip(){
объявление функции, функциональное выражение и с помощью стрелочки (=>).
Объявленная функция может быть использована раньше своего объявления, а функциональное выражение только после, т. к. кладется в переменную. Стрелочная функция - краткий вариант функционального выражения.

2024-09-13 09:38 UTC, sychnico commented on source/zip.js
> +"use strict";
"use strict" активирует новые возможности языка, которые по умолчанию выключены ради обратной совместимости со старым кодом

2024-09-13 09:45 UTC, sychnico commented on source/zip.js
> +      if (!(key in c)){
in вернет true, если свойство есть у объекта или его прототипа, а hasOwnProperty - только если оно есть у самого объекта

2024-09-13 10:51 UTC, let-robots-reign commented on source/zip.js
> +function zip(){
Верно, давай перепишем на стрелочную функцию, так как их используют чаще всего

2024-09-13 13:08 UTC, let-robots-reign reviewed
Немного осталось до аппрува

2024-09-13 13:08 UTC, let-robots-reign commented on source/zip.js
> +function zip(...args){
Как я написал в другом треде, давай сделаем стрелочную функцию

2024-09-13 13:08 UTC, let-robots-reign commented on source/zip.js
> +      }
forEach использовал, но тут тоже можно уйти от стандартного цикла for

2024-09-13 13:08 UTC, let-robots-reign commented on tests/zip.js
> -	});
Здесь не должно быть изменений

2024-09-13 13:08 UTC, let-robots-reign commented on tests/zip.js
> +  QUnit.test('Функция работает с объектами со свойствами с разными именами, некоторые из которых встречаются в нескольких объектах', function (assert) {
В своих тестах приведи отступы к тем, что были в изначальном файле

2024-09-13 13:08 UTC, let-robots-reign commented on tests/zip.js
> +
Зачем столько пустых строк тут?

2024-09-13 13:08 UTC, let-robots-reign commented on source/zip.js
> +
Зачем столько пустых строк тут?) Одной достаточно

2024-09-13 13:09 UTC, let-robots-reign commented on source/zip.js
> +      if (!(key in c)){
Судя по условию лучше использовать как раз `hasOwnProperty`

2024-09-13 16:09 UTC, let-robots-reign reviewed
Осталось немного
И поправь название PR, пожалуйста

2024-09-13 16:09 UTC, let-robots-reign commented on source/zip.js
> +
Тут убери строчки между JSDoc и функцией, иначе IDE может не подхватить документацию при наведении

2024-09-13 16:09 UTC, let-robots-reign commented on tests/zip.js
> -	QUnit.test('Функция работает с единственным объектом', function (assert) {
Здесь все еще не то с отступами
Гит не должен показывать -73 строки

2024-09-13 16:09 UTC, let-robots-reign commented on source/zip.js
> +let zip = (...args) => {
`const zip`, нам ведь не нужно будет это переопределять

2024-09-13 16:10 UTC, let-robots-reign commented on tests/zip.js
> +  QUnit.test('Функция работает с объектами со свойствами с разными именами, некоторые из которых встречаются в нескольких объектах', function (assert) {
И вот это еще не сделано

2024-09-13 17:18 UTC, let-robots-reign approved these changes
От меня аппрув! По-моему, хорошее решение получилось)
Удачи в работе над проектами!

2024-09-13 17:20 UTC, sychnico commented
Спасибо!

пт, 13 сент. 2024 г., 20:18 Alexey Zotov ***@***.***>:

> ***@***.**** approved this pull request.
>
> От меня аппрув! По-моему, хорошее решение получилось)
> Удачи в работе над проектами!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/47#pullrequestreview-2303676114>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZSXTUNMBXDGX6HMOYBE72LZWMNABAVCNFSM6AAAAABN27VODSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMBTGY3TMMJRGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-09-14 10:37 UTC, DPeshkoff approved these changes
Привет и добро пожаловать на второй семестр!

Работа отличная, мне ок)

2024-09-14 10:37 UTC, closed without merging