Cherepnin Mikhai Variant-
frontend-park-mail-ru/homework_2024_2 pull request #48
Opened 2024-09-08 14:30 UTC by Ifelsik

Черепнин Михаил
Сделал вариант 4

2024-09-11 18:51 UTC, SergTyapkin commented
Привет! Я ментор по фронтенду 3-го семестра. По всем вопросам, а так же когда исправишь замечания, пиши в телегу https://Tyapkin_S.t.me

2024-09-11 18:54 UTC, SergTyapkin commented
Привет! Я ментор по фронтенду 3-го семестра. По всем вопросам, а так же когда исправишь замечания, пиши в телегу https://Tyapkin_S.t.me

ПР следует назвать просто именем и фамилией

2024-09-11 19:09 UTC, SergTyapkin requested changes

2024-09-11 19:09 UTC, SergTyapkin commented on tests/inverse.js
> +	const obj = new Map;
Объект используется только в  одном тесте. Потому именно там он и должен быть создан

2024-09-11 19:09 UTC, SergTyapkin commented on source/inverse.js
> +    if (!Array.isArray(array) || !Number.isInteger(shift)) {
А что будет, если shift указан больше, чем длина массива? На это нужно тоже добавить тест

2024-09-11 19:09 UTC, SergTyapkin commented on tests/inverse.js
> +		assert.deepEqual(
Добавить ещё пару проверок с разными числами во втором аргументе, и вообще без него

2024-09-11 19:09 UTC, SergTyapkin commented on tests/inverse.js
> +		assert.deepEqual(inverse(new String('abcdf')), null);
Здесь лучше использовать не deepEqual. Он нужен для сложных объектов

2024-09-11 19:09 UTC, SergTyapkin commented on tests/inverse.js
> +	QUnit.test('Функция обрабатывает случай, если на вход подано что-то не то', function (assert) {
Давай будем передавать функции в test, используя стрелочный синтаксис. Оригинальные тесты тогда тоже придется изменить

2024-09-11 19:09 UTC, SergTyapkin commented on tests/inverse.js
> +	})
Добавить тесты на shift, равный длине массива или больший. А так же на shift = 0.

И куда потерялась ;

2024-09-12 15:10 UTC, Ifelsik commented on source/inverse.js
> +'use strict';
Директива позволяет избегать многих ошибок, например не позволяет объявить в теле функции переменной, которая будет доступна в глобальной области

2024-09-13 10:18 UTC, Ifelsik commented on source/inverse.js
> +const inverse = function (array, shift = 0) {
Стрелочная функция не имеет своего контекста this, при использовании с this значения будут браться из контекста выше, в котором стрелочная функция определена. Поэтому стрелочную функцию не получится использовать как метод объекта, а в обычном объявлении функции, её можно использовать как метод, поскольку this будет ссылаться на вызывающий объект

2024-09-13 10:21 UTC, Ifelsik commented on source/inverse.js
> +'use strict';
Например при использовании this в стрелочной функции, вызываемой в глобальном контексте this будет ссылаться на глобальный контекст, а строгий режим в этом случае вызвал бы ошибку

2024-09-13 11:28 UTC, Ifelsik commented on source/inverse.js
> +    if (!Array.isArray(array) || !Number.isInteger(shift)) {
Тут проблемы быть не должно, метод slice обрабатывает это

2024-09-13 15:19 UTC, Ifelsik commented on tests/inverse.js
> +	})
; поставил. Тесты на shift больший и равный длине массива есть выше

2024-09-13 15:31 UTC, Ifelsik commented on tests/inverse.js
> +	QUnit.test('Функция обрабатывает случай, если на вход подано что-то не то', function (assert) {
поправил

2024-09-13 15:37 UTC, Ifelsik commented on tests/inverse.js
> +		assert.deepEqual(
Есть в тестах исходных

2024-09-13 20:52 UTC, SergTyapkin requested changes

2024-09-13 20:52 UTC, SergTyapkin commented on source/inverse.js
> +'use strict';
Хорошо

2024-09-13 20:52 UTC, SergTyapkin commented on source/inverse.js
> +};
Нужна пустая строка в конце файла

2024-09-13 20:52 UTC, SergTyapkin commented on tests/inverse.js
> +		assert.throws(() => inverse([1, 2, 3], null), TypeError, 'Передано null вместо');
Конечно, можно было бы добавить ещё другие типы данных, но в целом нормально

2024-09-13 20:52 UTC, SergTyapkin commented on tests/inverse.js
>  });
Нет пустой строки в конце файла

2024-09-14 10:10 UTC, Ifelsik commented on source/inverse.js
> +};
Я делал в конце пустые строки. Долго ломал голову почему они не видны, как оказалось это интерфейс гитхаба её не отображает, если открыть через встроенный редактор гитхаба или скачать файл как raw, то там они отображаются

2024-09-14 10:10 UTC, Ifelsik commented on tests/inverse.js
>  });
Аналогично

2024-09-14 10:11 UTC, Ifelsik commented
jsDoc добавил

2024-09-15 10:35 UTC, SergTyapkin approved these changes

2024-09-16 15:28 UTC, Sarafa2n commented on source/inverse.js
> +    }
а может перепишем через ?

2024-09-16 15:49 UTC, Ifelsik commented on source/inverse.js
> +    }
Мне кажется, что это читабельность вообще в ноль сведёт
Но если надо, то переделаю

2024-09-16 16:58 UTC, closed without merging