Чупраков Сергей
frontend-park-mail-ru/homework_2024_2 pull request #49
Opened 2024-09-08 15:01 UTC by chsd0

Напишите функцию `letters`, которая будет удалять из строки символы, которые встречаются в ней больше одного раза. Если вторым аргументом передано true, то функция будет искать повторяющиеся символы в строках и удалять их, оставляя на месте только первую встречающуюся букву. Если вторым аргументом передано false, то функция будет оставлять только последнюю встречающуюся букву

2024-09-08 16:56 UTC, Gallaann commented
Что же, поздравляю с переходом на 2-ой семестр и приветсвую на курсе по фронтенду. Меня зовут Вова, и я буду проверять твое ДЗ №0.  По любым вопросам можешь писать в [ТГ](https://t.me/Gallaaan)

А вот пока мемчик для поднятия настроения
![image](https://github.com/user-attachments/assets/d89543f3-9bf6-4da6-a02d-90b5a7c3a753)

2024-09-08 17:44 UTC, Gallaann requested changes
Интересное решение, но нужно немного доработать. Пингани в тг, когда можно будет посмотреть повторно!)

2024-09-08 17:44 UTC, Gallaann commented on source/letters.js
> +'use strict';
Подскажешь что это за волшебная фраза такая?

2024-09-08 17:44 UTC, Gallaann commented on source/letters.js
> +const letters = (str, flag) => {
Здесь ты использовал стрелочную функцию. Чем она отличается от обычной?

2024-09-08 17:44 UTC, Gallaann commented on source/letters.js
> +
Не хватает описание функции через JSDoc, можешь почитать что это и с чем его едят здесь: https://precodes.hashnode.dev/jsdoc-the-ultimate-guide-to-documenting-your-javascript-code

2024-09-08 17:44 UTC, Gallaann commented on source/letters.js
> +        if(!uniqueLetters.includes(str[i])){
Кажется, не очень эффективное решение, `String.prototype.includes` это проход в цикле, а этот метод уже внутри цикла находится...
Лучше заменить на объект, `Map` или `Set`, в котором`key` - символ, `value` - количество встреченных символов, это потребует переписать код, зато сделает его более читаемым и оптимизированным

2024-09-08 17:44 UTC, Gallaann commented on source/letters.js
> +    let repeatingLetters = '', uniqueLetters = '';
Здесь ты использовал `let`, а какие еще директивы есть и чем они отличаются?

2024-09-08 17:44 UTC, Gallaann commented on source/letters.js
> +    for(let i = 0; i < str.length; i++){
Здесь у тебя использован обычный цикл `for`, какие еще есть варианты итерироваться по строке? По массиву? По объекту?

2024-09-08 17:44 UTC, Gallaann commented on source/letters.js
> +            if(flag == false){
Здесь и на строке 17 у тебя сравнение через `==`, почему не через `===`. Чем они отличаются и чем вызвано такое разнообразие операторов сравнения в js?

2024-09-08 17:44 UTC, Gallaann commented on tests/letters.js
> +	})
Давай к этому тесту добавим еще `undefined`, массив и какой-нибудь объект

2024-09-09 10:04 UTC, chsd0 commented on source/letters.js
> +'use strict';
`'use strict'` используется для работы в "современном" режиме js, который позволяет не думать об особенностях старых версий

2024-09-09 10:05 UTC, chsd0 commented on source/letters.js
> +const letters = (str, flag) => {
Стрелочная функция не имеет своего `this`, а наследует его от контекста объявления, например объекта или класса. Также она не имеет `arguments` и ее нельзя вызвать до определения

2024-09-09 10:05 UTC, chsd0 commented on source/letters.js
> +    let repeatingLetters = '', uniqueLetters = '';
Есть также `const` - объявление неизменяеимой переменной и `var` - старый вариант `let`, который может объявляться несколько раз, не имеет блочной области видимости, может быть использован до объявления

2024-09-09 10:05 UTC, chsd0 commented on source/letters.js
> +    for(let i = 0; i < str.length; i++){
Итерироваться по строке и массиву можно также с помощью конструкции `for( let char of str)` , а по объектам с помощью конструкции `for( let key in obj)`

2024-09-09 10:05 UTC, chsd0 commented on source/letters.js
> +            if(flag == false){
Сравнение через `==`, а не через `===` потому что не привык к js. Оператор `==` при сравнении разных типов пытается привести их к одному и сравнивать уже их, в то время как `===` сравнивает изначальные данные. Могу только предположить, что такое разнообразие операторов сравнения вызвано недоработками старых версий js.

2024-09-09 12:56 UTC, Gallaann commented on source/letters.js
> +const letters = (str, flag) => {
Все верно)
Могу еще добавить, что она не может быть использована как конструктор, а еще у нее нет `yield`, то есть она не может быть функцией-генератором

2024-09-09 13:00 UTC, Gallaann commented on source/letters.js
> +            if(flag == false){
Все верно)

2024-09-09 13:01 UTC, Gallaann commented on source/letters.js
> +    let repeatingLetters = '', uniqueLetters = '';
Верно, расскажи еще почему не рекомендуется использовать `var`

2024-09-09 13:04 UTC, Gallaann commented on source/letters.js
> +'use strict';
Хотелось бы, чтобы ты немного раскрыл в чем заключается этот "современный" режим

2024-09-09 14:20 UTC, Gallaann commented on source/letters.js
> +        }
Можем упростить этот кусок используя оператор нулевого слияния до
```suggestion
            map.set(char, (map.get(char) ?? 0) + 1);
```

2024-09-09 14:25 UTC, Gallaann commented on source/letters.js
> +
Вот тут лишняя строчка, просто выглядит не очень)

2024-09-09 14:25 UTC, Gallaann commented on source/letters.js
> +    for(let char of str){
Тут тоже `const`

2024-09-09 14:25 UTC, Gallaann commented on source/letters.js
> +    for(let char of str){
Добавь тут перевод строки, чтобы отделить логические блоки друг от друга

2024-09-09 14:26 UTC, Gallaann commented on source/letters.js
> +    for(let char of str){
Добавь тут перевод строки, чтобы отделить логические блоки друг от друга

2024-09-09 14:26 UTC, Gallaann commented on source/letters.js
> +    return finalString;
Добавь тут перевод строки, чтобы отделить логические блоки друг от друга

2024-09-09 14:47 UTC, chsd0 commented on source/letters.js
> +'use strict';
Строгий режим заменяет "тихие" ошибки исключениями, в некоторых случаях он может оптимизировать выполнение кода

2024-09-09 14:52 UTC, Gallaann commented on source/letters.js
> +    for(let char of str){
И хорошо бы переименовать `map` во что-то типа `charsCount`

2024-09-09 20:50 UTC, chsd0 commented on source/letters.js
> +    let repeatingLetters = '', uniqueLetters = '';
В браузере переменные, объявленные с помощью `var` становятся свойствами глобального объекта, например `window`

2024-09-09 20:56 UTC, Gallaann approved these changes
lgtm

Добавь еще плиз описание задачи в коммент к ПРу, а от меня аппрув, микрофикс на решение уже не влияет)

2024-09-09 20:56 UTC, Gallaann commented on source/letters.js
> +}
Хотелось бы тут еще перевод строки в конце файла
Вот статья про это - https://semakin.dev/2020/05/no_newline_at_end_of_file/

2024-09-13 07:20 UTC, DPeshkoff approved these changes
Привет и добро пожаловать на второй семестр!

Работа огонь, аппрув)

2024-09-13 07:20 UTC, closed without merging