variant-4 is done by Volkova web-21
frontend-park-mail-ru/homework_2024_2 pull request #5
Opened 2024-08-27 10:09 UTC by grozaqueen

Функция inverse принимает массив и число skip, определяющее диапазон инверсии. Она переворачивает часть элементов массива, начиная с позиции skip, если оно положительное, или оставляя skip последних элементов на своих местах, если оно отрицательное. Если skip выходит за границы массива или массив пустой, возвращается копия исходного массива.

Волкова Юлия,
web-21

2024-08-30 12:38 UTC, Nikita-hub000 commented
Привет! Меня зовут Никита. Поздравляю с переходом на 2 семестр и желаю успехов в учебе:)
Я буду твоим проверяющим ДЗ№0. Если возникнут вопросы, не стесняйся обращаться)

1. Некорректное название ПРа. Оно должно быть «Фамилия Имя студента»
2. Произошел лишний пуш чего-то в .idea:) Лучше это поправить и стараться не допускать такого в будущем
3. Отсутствует пустая строка в коне файлов .js

2024-08-30 13:12 UTC, Nikita-hub000 commented on tests/inverse.js
> +		}
Добавь еще тестик на число но нецелое вторым аргументом

2024-08-30 20:58 UTC, grozaqueen commented on source/inverse.js
> +function inverse(arr, skip = 0) {
'use strict' - директива, которая нужна для написания более чистого и правильного кода, так как она выявляет "опасные" места, из-за неточности/неправильности которых в дальнейшем возможны ошибки. В обычном режиме такое игнорируется

2024-08-30 21:03 UTC, Nikita-hub000 commented
Увидел правки) Все гуд. Осталось только пустую строчку добавить в конец файлов. Ну и на будущее на теоретические вопросики можешь ( если хочешь конечно) отвечать прям в диалоге с правкой:)

2024-08-30 21:09 UTC, Nikita-hub000 commented on source/inverse.js
> +function inverse(arr, skip = 0) {
Приведи плз пару примеров таких опасных мест:)

2024-08-31 10:10 UTC, Nikita-hub000 commented
Отличная работа! От меня ок)

2024-08-31 10:21 UTC, grozaqueen commented on source/inverse.js
> +function inverse(arr, skip = 0) {
Например, в строгом режиме нужно, чтобы параметры функции имели уникальные имена, иначе параметр примет значение последнего переданного аргумента с этим именем, эта неточность может повлечь за собой проблемы
Еще пример: нельзя присваивать значение в неопределённую переменную (без указания var, let, const), так как автоматически они определятся глобальными, что может привести к непредсказуемым ошибкам

2024-09-06 17:50 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть чуть-чуть вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-06 17:50 UTC, DPeshkoff commented on source/inverse.js
> +'use strict'; // Включение строгого режима
А что такое строгий режим? Чем от обычного отличается?

2024-09-06 17:50 UTC, DPeshkoff commented on source/inverse.js
> +        throw new Error("Первый аргумент должен быть массивом");
Предлагаю одиночные кавычки - так чаще пишут)

А еще у ошибок есть [типы](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA) - давай выберем лучший

2024-09-06 17:50 UTC, DPeshkoff commented on source/inverse.js
> +};
[Почему важен перенос на новую строку в конце файла](https://semakin.dev/2020/05/no_newline_at_end_of_file/)

2024-09-06 17:50 UTC, DPeshkoff commented on tests/inverse.js
> +		try {
Лучше [так](https://qunitjs.com/api/assert/throws/)

2024-09-06 21:15 UTC, grozaqueen commented on source/inverse.js
> +'use strict'; // Включение строгого режима
Строгий режим - это режим, который повышает надежность кода путем запрета "плохих" синтаксических конструкций, в свою очерередь это помогает предостеречь от ошибок на раннем этапе, код становится более читаемым и предсказуемым. Обычный режим отличается от строгого тем, что он более лоялен к ошибкам и неявным преобразованиям. Например, в нестрогом режиме если в коде есть ошибки, такие как неопределенные переменные, неправильно указанные типы данных, и т. д., обычный режим будет игнорировать их и продолжать выполнение кода. В строгом режиме в таком случае код не выполнится.

2024-09-10 21:00 UTC, DPeshkoff approved these changes

2024-09-10 21:00 UTC, closed without merging