Новак Александр
frontend-park-mail-ru/homework_2024_2 pull request #50
Opened 2024-09-08 15:29 UTC by AlexNov03

дз 0 сделано

2024-09-11 19:15 UTC, SergTyapkin commented
Привет! Я ментор по фронтенду 3-го семестра. По всем вопросам, а так же когда исправишь замечания, пиши в телегу https://Tyapkin_S.t.me

2024-09-11 19:19 UTC, SergTyapkin requested changes

2024-09-11 19:19 UTC, SergTyapkin commented on source/solve.js
> +'use strict';
Зачем нужна эта строчка?

2024-09-11 19:19 UTC, SergTyapkin commented on source/solve.js
> +const solve = (str, xval) => eval(str.replaceAll('x', xval));
Классно, что ты использовал стрелочную функцию. Кстати, расскажешь в ответе, чем они отличаются от классических?

Решение могло бы быть красивым, если бы всё было так просто, но тебе нельзя использовать функцию `eval`, ведь иначе все решение сводится к её использованию. К сожалению придется переписать без неё.

Также ты забыл пустую толку в конце файла.

А ещё тебе нужно добавить тесты на твою функцию, которых не хватает в изначальном файле тестов. Они должны быть исчерпывающими.

2024-09-11 23:09 UTC, AlexNov03 commented on source/solve.js
> +'use strict';
Привет ! Я изучал learn javascript , там эта строка используется чтобы использовать ограниченный синтаксис языка и не допускать таких конструкций как присвоение переменных без let

2024-09-11 23:11 UTC, AlexNov03 commented on source/solve.js
> +const solve = (str, xval) => eval(str.replaceAll('x', xval));
Переписать придется получается прям с большой вот этой функцией со стеком и приоритетом операций ?

2024-09-12 01:42 UTC, AlexNov03 commented
Сделал solve с помощью обратной польской записи и ее решения стеком, проверьте пожалуйста.

2024-09-12 14:06 UTC, SergTyapkin commented on source/solve.js
> +'use strict';
При работе с переменными в этом случае есть ещё одна важная особенность. А конкретнее - с их использованием по отношению к их декларации.

Найди, в чем она заключается)

2024-09-12 14:10 UTC, SergTyapkin commented on source/solve.js
> +function ParseStr (str) {
Убери лишний пробел)
https://learn.javascript.ru/coding-style

2024-09-12 14:10 UTC, SergTyapkin commented on source/solve.js
> +    let res = [];
Здесь как-то по-другому стоит определить переменную (не `let`)

2024-09-12 14:11 UTC, SergTyapkin commented on source/solve.js
> +
Зачем тут пустая строка... Смотрится вырвиглазно

2024-09-12 14:13 UTC, SergTyapkin commented on source/solve.js
> +            case '+':
Давай вместе перечисления и проверки через `switch` вынесем список операций а какой-то отдельный объект, и будет проверять через какой-то метод этого объекта

2024-09-12 14:14 UTC, SergTyapkin commented on source/solve.js
> +                curNum = curNum == -1 ? Number(elem) : curNum * 10 + Number(elem)
А если в строке присутстуют буквы? Посмотри, как можно сделать проверку символа на число, и в обратном случае следует выбрасывать ошибку

2024-09-12 14:15 UTC, SergTyapkin commented on source/solve.js
> +                curNum = curNum == -1 ? Number(elem) : curNum * 10 + Number(elem)
Забыл `;`

2024-09-12 14:15 UTC, SergTyapkin commented on source/solve.js
> +    if (curNum != -1) {
Используй строгое сравнение

2024-09-12 14:15 UTC, SergTyapkin commented on source/solve.js
> +                curNum = curNum == -1 ? Number(elem) : curNum * 10 + Number(elem)
Используй строгое сравнение

2024-09-12 14:16 UTC, SergTyapkin commented on source/solve.js
> +    let masStr = ParseStr(str);
`masStr` не изменяется после создания. Почему `let` ?

2024-09-12 14:16 UTC, SergTyapkin commented on source/solve.js
> +    let priorities = new Map([
Почему Map, а не обычный объект?
И опять `let`

2024-09-12 14:19 UTC, SergTyapkin commented on source/solve.js
> +        if (val === '+' || val === '-' || val === '*') {
Тоже можно упростить проверку

2024-09-12 14:22 UTC, SergTyapkin commented on source/solve.js
> +        }else if (val === '('){
Проверь стиль кода. Причем везде

2024-09-12 14:23 UTC, SergTyapkin commented on source/solve.js
> +            while (priorities.get(val) <= priorities.get(myStack.at(-1))){
Зачем метод `at` и в чем его разница с обычными `[]`

2024-09-12 14:24 UTC, SergTyapkin commented on source/solve.js
> +                let oper1 = myStack.pop();
`const`

2024-09-12 14:26 UTC, SergTyapkin commented on source/solve.js
> +    return solvePolish(toPolish(str.replaceAll('x', String(val))));
String не нужно

2024-09-12 14:26 UTC, SergTyapkin commented on source/solve.js
> +function solve (str, val) {
Нужна проверка входящих аргументов на типы

2024-09-12 14:26 UTC, SergTyapkin commented on source/solve.js
> +    return myStack.at(-1);
Тоже вопрос к `at`

2024-09-12 14:27 UTC, SergTyapkin commented on tests/solve.js
>  	});
Нужно больше тестов. На неправильные типы аргументов, на неправильные символы в строке. На то что аргументов вообще нет, и т.п. 
Нужно разобрать максимально все возможные случаи

2024-09-12 15:28 UTC, AlexNov03 commented on source/solve.js
> +    return myStack.at(-1);
в at можно обращаться через -1 к последнему элементу массива. Мне кажется это удобно и хорошо читается

2024-09-12 15:36 UTC, AlexNov03 commented on source/solve.js
> +'use strict';
если не использовать use strict и вывести значение необъявленной переменной выведется undefined, иначе - ошибка

2024-09-12 15:45 UTC, AlexNov03 commented on source/solve.js
> +function ParseStr (str) {
разность в this, в обычных функциях this определяется динамически, а в стрелочных она привязана к окружению в котором они объявлены. В первом случае при обращении к свойству объекта через this - undefined. Во втором - получаем свойство объекта

2024-09-12 15:46 UTC, AlexNov03 commented on source/solve.js
> +function ParseStr (str) {
с большой буквы - функции конструкторы. Здесь это действительно невалидно

2024-09-12 22:48 UTC, AlexNov03 commented
поменял let на const, убрал лишние строки, добавил тесты и обработку ошибок. Не вынес switch в отдельный объект, в данном алгоритме мне кажется это неудобным. Насчет использования at объяснил - удобно и коротко обращаться к последнему элементу через -1, через [] этого сделать нельзя

2024-09-12 22:50 UTC, AlexNov03 commented
Проверьте пожалуйста исправления

2024-09-13 21:10 UTC, SergTyapkin requested changes
Посмотри, можно ли где-то заменить циклы на перебирающие методы массивов. (`forEach`, `map` и `reduce`)

2024-09-13 21:10 UTC, SergTyapkin commented on source/solve.js
> +        if (['+', '-', '*'].includes(val)) {
Почему здесь тебе `[].includes` нравится больше, чем switch, а в случае выше - именно switch?

2024-09-13 21:10 UTC, SergTyapkin commented on source/solve.js
> +        throw new TypeError("argument str must be string, argument val must be int");
Выход из функции по причине ошибок входных аргументов лучше писать вначале, а потом уже в конце - само тело функции, с "полезной нагрузкой"

2024-09-13 21:10 UTC, SergTyapkin commented on tests/solve.js
> +		assert.throws(() => solve(7, 'jhxhe'), TypeError);
Негативные проверки следует вынести в отдельный тест.

Добавить тесты для многосимвольных чисел. 

Добавить тесты для неправильного расположения скобок.

Постарайся по-максимуму сломать свою функцию и докажи тестами, что она не ломается

2024-09-13 21:10 UTC, SergTyapkin commented on tests/solve.js
> +		assert.throws(() => solve(), Error);
Добавь пустую строку в конце файла

2024-09-14 16:16 UTC, AlexNov03 commented
Добавил новые тесты, улучшил функцию, добавил JsDoc

2024-09-15 11:09 UTC, SergTyapkin requested changes

2024-09-15 11:09 UTC, SergTyapkin commented on source/solve.js
> +    while(myStack.length !== 0){
Можно оставить просто `myStack.length`, это читается быстрее, ведь смысл выражения в том, что "пока в myStack что-то есть, делай...."

2024-09-15 11:09 UTC, SergTyapkin commented on source/solve.js
> +            throw new Error("неправильно расставлены скобки !!!");
А почему тут текст ошибки с маленькой буквы, а в прошлый раз с большой?)

2024-09-15 11:09 UTC, SergTyapkin commented on source/solve.js
> +        //здесь switch, тк много ветвлений
Такие комментарии лучше писать внутри гитхаба такими же комментами, какие я сейчас оставляю. Они не в коде должны быть.

2024-09-15 11:09 UTC, SergTyapkin commented on source/solve.js
> +        //if так как неудобно писать switch (много однотипных case)
Такие комментарии лучше писать внутри гитхаба такими же комментами, какие я сейчас оставляю. Они не в коде должны быть.

2024-09-15 11:09 UTC, SergTyapkin commented on source/solve.js
> +    }else if (typeof str !== "string" || typeof val !== "number") {
`else` не нужен, так как выброс ошибки эквивалентен выходу из функции

2024-09-15 11:09 UTC, SergTyapkin commented on source/solve.js
> +        throw new TypeError("argument str must be string, argument val must be int");
Хорошей практикой считается указание полученных типов данных. То есть "Ошибка. Ожидалось ...., получено ....". Давай добавим сюда это

2024-09-15 11:09 UTC, SergTyapkin commented on source/solve.js
> +    }else{
`else` так же не нужен

2024-09-15 11:09 UTC, SergTyapkin commented on tests/solve.js
> +
Следует добавить тесты на то, что функция работает и без пробелов между символами. А может быть где-то с пробелами, а где-то нет.

А что будет, если в строке вместо пробела будет `\t`?

2024-09-15 11:21 UTC, AlexNov03 commented on tests/solve.js
> +
Без пробелов будет плохо работать унарный минус, его в принципе сложно обрабатывать и даже в википедии рекомендуется класть на стек отрицательное значение сразу, поэтому здесь принять так -5 например унарный минус 5 - 7 с пробелом бинарный

2024-09-16 14:01 UTC, AlexNov03 commented
Все поправил, при обработке \t выдается ошибка типа, но в задании не сказано учитывать специальные символы, поэтому я считаю корректный результат. Примите пожалуйста исправления, очень нужен approve.

2024-09-16 20:34 UTC, SergTyapkin commented
Когда исправляешь какое-либо замечание, нажимай на эту кнопку, чтобы оно исчезало
![image](https://github.com/user-attachments/assets/b8e5f34f-ed1e-43df-a24c-8823e621da4f)

2024-09-16 20:53 UTC, SergTyapkin requested changes

2024-09-16 20:53 UTC, SergTyapkin commented on source/solve.js
> +}
А где пустая строка-то?

2024-09-16 20:53 UTC, SergTyapkin commented on source/solve.js
> +'use strict';
После этой тоже бы пустую строку добавить

2024-09-16 20:53 UTC, SergTyapkin commented on source/solve.js
> +        if (['+', '-', '*'].includes(val)) {
Зачем нам два объекта со списком знаков?
Давай поменяем на `if (val in proirities)`

2024-09-16 20:53 UTC, SergTyapkin commented on source/solve.js
> + * Такое некорректно: 5 - - 6
Комментарии очень подробные, круто!

2024-09-16 20:53 UTC, SergTyapkin commented on source/solve.js
> +        throw new TypeError("argument str must be string, argument val must be int");
Так а где? Ты не добавил указания полученных типов

2024-09-16 20:53 UTC, SergTyapkin commented on source/solve.js
> +
Как выяснилось, гитхаб не отображает одну пустую строку в конце файла. Так что убери, пожалуйста, лишние и оставь только одну)

2024-09-16 20:53 UTC, SergTyapkin commented on tests/solve.js
> +	QUnit.test('Работает правильно при неправильных типах параметров ', function (assert) {
Лучше "Выбрасывает ошибку при неправильных типах параметров"
И в остальных случаях аналогично

2024-09-16 20:54 UTC, SergTyapkin commented
Там остались мелочи. Давай исправим, и я сразу поставлю аппрув

2024-09-17 11:12 UTC, AlexNov03 commented
Поправил, там гитхаб почему-то некоторое не отражает, строка перед return была в прошлый раз

2024-09-17 13:09 UTC, SergTyapkin commented on source/solve.js
> +}
И тут тоже нет...

2024-09-17 13:11 UTC, SergTyapkin commented
> Поправил, там гитхаб почему-то некоторое не отражает, строка перед return была в прошлый раз

Так строка не перед return должна быть, а между функциями

2024-09-17 16:56 UTC, AlexNov03 commented
аааа, между функциями я думал перед return

2024-09-18 12:32 UTC, Sarafa2n commented on source/solve.js
> +    for (let i = 0; i < str.length; i++) {
это можно заменить на reduce

2024-09-18 12:34 UTC, Sarafa2n commented on source/solve.js
> +    }
это можно вынести в константу

2024-09-18 12:35 UTC, Sarafa2n commented on source/solve.js
> +        if (['+', '*', '(', ')'].includes(str[i])) {
какой-то магический массив, в константу бы

2024-09-18 12:37 UTC, Sarafa2n commented on source/solve.js
> +        } else if (str[i] === '-') {
почему не заменить на switch case ?

2024-09-18 12:38 UTC, Sarafa2n commented on source/solve.js
> +    }
reduce

2024-09-18 12:39 UTC, Sarafa2n commented on source/solve.js
> +        if (val in priorities) {
кажется что тут тоже можно switch

2024-09-18 12:40 UTC, Sarafa2n commented on source/solve.js
> +    }
reduce

2024-09-18 12:40 UTC, Sarafa2n commented on source/solve.js
> +        if (['(', ')'].includes(elem)) {
это тоже в константу можно

2024-09-18 12:40 UTC, Sarafa2n commented on source/solve.js
> +            throw new Error("Неправильно расставлены скобки !!!");
одинарные кавычки бы

2024-09-18 12:41 UTC, Sarafa2n commented on source/solve.js
> +        throw new Error("str and val arguments must not be empty");
давай ошибки к одному формату приведем, а то часть на русском, часть на английском, странно очень

2024-09-18 15:51 UTC, AlexNov03 commented on source/solve.js
> +    }
а это же и есть константа (константный объект), не совсем понял этот момент

2024-09-18 15:53 UTC, AlexNov03 commented on source/solve.js
> +    }
Вы имеете в виду сделать константу глобальной ?

2024-09-18 17:19 UTC, AlexNov03 commented
Поправил ошибки

2024-09-18 17:19 UTC, AlexNov03 commented
В единственном месте не понял насчет константы, выше задал вопрос

2024-09-18 17:20 UTC, Sarafa2n commented on source/solve.js
> +    }
именно

2024-09-18 17:21 UTC, Sarafa2n commented on source/solve.js
> +    }
вынести это из функции

2024-09-18 18:17 UTC, Sarafa2n commented on source/solve.js
> +    const ops = ['+', '*', '(', ')'];
вынести из функции

2024-09-18 18:25 UTC, AlexNov03 commented
Готово, вынес

2024-09-18 18:28 UTC, closed without merging