Федосеев Владимир WEB-22
frontend-park-mail-ru/homework_2024_2 pull request #55
Opened 2024-09-09 03:18 UTC by oruchim1001

Здравствуйте. Разрешите представить реализацию решения по 2 варианту домашнего задания №0.

2024-09-09 10:25 UTC, ValdimirDenisov commented on source/euclid.js
> +        return 'Все аргументы должны быть целыми числами'; // Обработка некорректного ввода
Здесь должна возвращаться ошибка, а не строка

2024-09-09 10:25 UTC, ValdimirDenisov commented on source/euclid.js
> +
Добавь `'use strict';`, и напиши для чего это используется

2024-09-09 10:25 UTC, ValdimirDenisov commented on source/euclid.js
> +    while (n != 0) {
Должно быть строгое сравнение `!==`. Напиши различия между строгим сравнением или не строгим

2024-09-09 10:25 UTC, ValdimirDenisov commented on source/euclid.js
> +    if (inputNumbers.length == 1) return inputNumbers[0]; // Если введено одно число, то его НОД это оно само и есть!
Используй строгое сравнение

2024-09-09 10:28 UTC, ValdimirDenisov commented
Привет! Поздравляю тебя с переходом на второй семестр!)
Меня зовут Вова, я проверил твое ДЗ №0. Очень хорошее решение, но есть небольшие моменты которые нужно поправить. Если возникнут любые вопросы, можешь смело писать мне в [телегу](https://t.me/Alfredodanger).

2024-09-11 07:04 UTC, ValdimirDenisov commented on source/euclid.js
> +const euclid = (...inputNumbers) => {
![image](https://github.com/user-attachments/assets/41bb3f65-31f8-40c0-beea-ba3e50a34eaf)
ой сломали

2024-09-11 07:04 UTC, ValdimirDenisov commented on source/euclid.js
> +        [solution, n] = [n, solution % n]; //solution = n , n = solution % n
А что это такое? Как это работает? Как еще можно свапнуть элементы?

2024-09-11 07:04 UTC, ValdimirDenisov commented on source/euclid.js
> +    while (n !== 0) {
Тут можно проще https://doka-guide.vercel.app/js/if-else/

2024-09-12 05:40 UTC, ValdimirDenisov commented on source/euclid.js
> +        return 'Необходимо передать хотя бы одно число';
Замени на возврат ошибки

2024-09-12 07:01 UTC, oruchim1001 commented on source/euclid.js
> +        return 'Необходимо передать хотя бы одно число';
` if (!inputNumbers.length) {
        throw new Error('Необходимо передать хотя бы одно число');
    }` сделал как возврат ошибки. поправил тест на эту проверку.
`				assert.throws(function () { euclid() }, /Необходимо передать хотя бы одно число/, 'проверка на работу функции без аргументов');
`

2024-09-12 07:17 UTC, ValdimirDenisov commented on source/euclid.js
> +const gcd = (solution, n) => {
Добавь JSDoc

2024-09-12 07:17 UTC, ValdimirDenisov commented on source/euclid.js
> +const euclid = (...inputNumbers) => {
Добавь JSDoc

2024-09-12 19:37 UTC, oruchim1001 commented on source/euclid.js
> +const euclid = (...inputNumbers) => {
/**
 * Функция для нахождения НОД нескольких чисел с помощью алгоритма Евклида.
 * @param {...number} inputNumbers Введенные числа, для которых нужно найти НОД.
 * @throws {Error} Если передан пустой массив.
 * @throws {TypeError} Если среди аргументов есть нецелые числа.
 * @returns {number} Возвращает НОД для всех переданных в функцию целых чисел.
 */

2024-09-12 19:37 UTC, oruchim1001 commented on source/euclid.js
> +const gcd = (solution, n) => {
/**
 * Функция для нахождения наибольшего общего делителя (НОД) двух чисел с помощью алгоритма Евклида.
 * @param {number} solution Первый параметр функции, далее в данную переменную записывается текущий результат.
 * @param {number} n Второй параметр функции.
 * @returns {number} Наибольший общий делитель двух чисел.
 */

2024-09-13 07:24 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, накидаю пару вопросиков)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-13 07:24 UTC, DPeshkoff commented on out/euclid.js.html
Много лишних файлов - вот это загружать не нужно, например)

2024-09-13 07:24 UTC, DPeshkoff commented on source/euclid.js
> +const euclid = (...inputNumbers) => {
А чем стрелочные функции от обычных отличаются?

2024-09-13 07:24 UTC, DPeshkoff commented on source/euclid.js
> +};
И не теряй перенос в конце файла

2024-09-13 10:15 UTC, oruchim1001 commented on source/euclid.js
> +const euclid = (...inputNumbers) => {
1)Для стрелочной функции блок кода может быть пропущен, если тело функции состоит из одной строки
2)Значение this стрелочной функции эквивалетно this внешней функции, т.е. стрелочная функция не создает свой this. Из за этого нельзя создать объект с помощью стрелочной функции.

2024-09-13 14:38 UTC, oruchim1001 commented on source/euclid.js
> +};
Добавил пустую строчку в файле

2024-09-16 19:20 UTC, DPeshkoff requested changes

2024-09-16 19:20 UTC, DPeshkoff commented on package.json
этот файлик тут тоже не нужен)

2024-09-16 19:32 UTC, oruchim1001 commented on package.json
удалил, добавил в гитигнор

2024-09-16 21:03 UTC, Sarafa2n commented on source/euclid.js
> +    if (inputNumbers.length === 1) return inputNumbers[0];
давай описывать if однообразно, добавь {}

2024-09-16 21:47 UTC, oruchim1001 commented on source/euclid.js
> +    if (inputNumbers.length === 1) return inputNumbers[0];
согласен. добавил

2024-09-17 09:27 UTC, closed without merging