Алексей Нарыжный
frontend-park-mail-ru/homework_2024_2 pull request #6
Opened 2024-08-27 16:56 UTC by AlexeyBMSTU

2024-08-30 19:52 UTC, Nikita-hub000 commented
Привет! Меня зовут Никита. Поздравляю с переходом на 2 семестр и желаю успехов в учебе:)
Я буду твоим проверяющим ДЗ№0. Если возникнут вопросы, не стесняйся обращаться)

1. Некорректное название ПРа. Оно должно быть «Фамилия Имя студента»
2. Создай файл plain.js в source и перемести туда свою функцию, как сейчас лучше не делать. Ибо мешаются тесты и сама программа в одном файле:)
3. Отсутствует пустая строка в конце файлов .js

2024-08-30 20:05 UTC, Nikita-hub000 commented on tests/plainify.js
> +  Object.entries(obj).reduce((acc, [key, value]) => {
Отлично использованный reduce. Красиво и к месту:)

2024-08-30 20:05 UTC, Nikita-hub000 commented on tests/plainify.js
> +  QUnit.test('plainify работает правильно', function (assert) {
Стоит переименовать тест во что то более говорящее, что этот тест делает

2024-08-30 20:05 UTC, Nikita-hub000 commented on tests/plainify.js
> +    // Проверяем, что plainify работает корректно для простого объекта
Лучше следовать одному правилу. Один тест - один assert. Так повышается читаемость и документируемость

2024-08-30 20:05 UTC, Nikita-hub000 commented on tests/plainify.js
> +});
Стоит добавить тестов когда приходит не объект, когда в объекте есть null, когда в объекте есть [], когда 'случайно' кто то задал prefix не строкой.

2024-08-31 10:45 UTC, AlexeyBMSTU commented
Здравствуйте, спасибо большое). Я поправил. Не понимаю зачем нужно
оставлять пустую строчку в файлах .js. Объясните пожалуйста

пт, 30 авг. 2024 г. в 23:05, Nikita ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739347748>
> :
>
> > @@ -1,45 +1,57 @@
> +// Здравствуйте, я Алексей Нарыжный из группы WEB-21.
> +// Мои контакты:
> +// tg: fish190 | vk: vk.com/leshka_055
> +
>  'use strict';
>
> Хорошо, что использовал use strict:)
> Можешь вкратце описать что он дает и зачем он вообще нужен)
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739352410>
> :
>
> >  'use strict';
>
> +// Определяем функцию plainify, которая принимает объект
> +const plainify = (obj, prefix = '') =>
>
> Стрелочная функция - гуд. Старайся зачастую использовать именно их. Очень
> редко возникают ситуации когда они только вредят. А читается все так
> намного лучше:)
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739355490>
> :
>
> >  'use strict';
>
> +// Определяем функцию plainify, которая принимает объект
> +const plainify = (obj, prefix = '') =>
> +
> +  // Используем Object.entries для итерации по ключ-значению объекта (хеш)
> +  Object.entries(obj).reduce((acc, [key, value]) => {
> +
> +    // Создаем новый ключ, конкатенируя префикс и оригинальный ключ
> +    const newKey = prefix ? `${prefix}.${key}` : key;
> +
> +    // Если значение является объектом, рекурсивно вызываем plainify
> +    return typeof value === 'object'
>
> Не совсем верная проверка. Шальной null или [] могут все сломать. Подумай
> как это можно поправить:)
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739358132>
> :
>
> >  'use strict';
>
> +// Определяем функцию plainify, которая принимает объект
> +const plainify = (obj, prefix = '') =>
> +
> +  // Используем Object.entries для итерации по ключ-значению объекта (хеш)
> +  Object.entries(obj).reduce((acc, [key, value]) => {
> +
> +    // Создаем новый ключ, конкатенируя префикс и оригинальный ключ
> +    const newKey = prefix ? `${prefix}.${key}` : key;
> +
> +    // Если значение является объектом, рекурсивно вызываем plainify
> +    return typeof value === 'object'
> +      ? { ...acc, ...plainify(value, newKey) }
>
> Каждый раз использовать rest не очень хорошо. Ведь объект может быть с
> миллионом ключей.
> Почему rest для таких больших объектов плох? Что он по сути делает?
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739361285>
> :
>
> >  'use strict';
>
> +// Определяем функцию plainify, которая принимает объект
> +const plainify = (obj, prefix = '') =>
> +
>
> Нет обработки случаев когда на вход в функцию подается не объект и когда
> prefix не строка ( ведь prefix также может прилететь откуда то извне)
>
> В таких случаях нужно пробрасывать ошибку
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739365683>
> :
>
> >  'use strict';
>
> +// Определяем функцию plainify, которая принимает объект
> +const plainify = (obj, prefix = '') =>
> +
> +  // Используем Object.entries для итерации по ключ-значению объекта (хеш)
> +  Object.entries(obj).reduce((acc, [key, value]) => {
>
> Отлично использованный reduce. Красиво и к месту:)
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739366607>
> :
>
> > -			}
> -		};
> -
> -		const plain2 = {
> -			'deep.foobar': 0,
> -			'deep.nested.object.fields.foo': 42,
> -			'deep.nested.object.fields.bar': 42,
> -			'deep.nested.object.fields.baz': 42
> -		};
> -
> -		assert.deepEqual(plainify(nested2), plain2);
> -	});
> -});
> +
> +  // Тест: plainify работает правильно
> +  QUnit.test('plainify работает правильно', function (assert) {
>
> Стоит переименовать тест во что то более говорящее, что этот тест делает
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739367915>
> :
>
> > -
> -		const plain2 = {
> -			'deep.foobar': 0,
> -			'deep.nested.object.fields.foo': 42,
> -			'deep.nested.object.fields.bar': 42,
> -			'deep.nested.object.fields.baz': 42
> -		};
> -
> -		assert.deepEqual(plainify(nested2), plain2);
> -	});
> -});
> +
> +  // Тест: plainify работает правильно
> +  QUnit.test('plainify работает правильно', function (assert) {
> +
> +    // Проверяем, что plainify работает корректно для простого объекта
>
> Лучше следовать одному правилу. Один тест - один assert. Так повышается
> читаемость и документируемость
> ------------------------------
>
> In tests/plainify.js
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#discussion_r1739367992>
> :
>
> > +            fields: {
> +              foo: 42,
> +              bar: 42,
> +              baz: 42
> +            }
> +          }
> +        }
> +      }
> +    }), {
> +      'deep.foobar': 0,
> +      'deep.nested.object.fields.foo': 42,
> +      'deep.nested.object.fields.bar': 42,
> +      'deep.nested.object.fields.baz': 42
> +    });
> +  });
> +});
>
> Стоит добавить тестов когда приходит не объект, когда в объекте есть null,
> когда в объекте есть [], когда 'случайно' кто то задал prefix не строкой.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/frontend-park-mail-ru/homework_2024_2/pull/6#pullrequestreview-2273405207>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAQ2APSKLLFJE3B2LQBIVW3ZUDGCHAVCNFSM6AAAAABNGROF6GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENZTGQYDKMRQG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-09-01 13:58 UTC, Nikita-hub000 commented
Пустая строка является неким стандартом для разработки, т.к. существуют некоторые инструменты ( компиляторы, библиотеки, парсеры. и тд), которые могут приводить к неожиданным ошибкам из за отсутствия пустой строки в конце. ( особенно на unix системах, т.к. у них новая строка - \n является символом окончания предыдущей строки)

2024-09-01 21:01 UTC, AlexeyBMSTU commented
Спасибо большое, нужны какие-то исправления еще?

2024-09-02 10:10 UTC, Nikita-hub000 commented
Да, насчет твоего комментария по rest. 
В твоем кейсе глубина рекурсии ограничена количеством вложенностей в объект и не защищена от прилета {obj: {obj: {obj ( и так 10 тысяч раз)}}}
Ограничение можно было поставить если завести например переменную depth и инкрементить ее каждый раз при новом заходе в рекурсию, но это уже совсем другая задача) 
В твоем случае интеративный подход с использованием стека выглядит предпочтительнее рекурси, т.к. итеративный подход не переполнит стек вызовов

2024-09-02 18:11 UTC, Nikita-hub000 commented
Все круто, но maxDepth мог не добавлять:) 
Во первых этого нет в условии задачи:) 
Во вторых если и ограничивать, то ограничивать на рекурсии из за max call stack

От меня аппрув, отличная работа!)

2024-09-02 18:18 UTC, AlexeyBMSTU commented
спасибо большое)

2024-09-06 17:55 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но у меня возникли вопросы к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-06 17:55 UTC, DPeshkoff commented on source/plain.js
> +const plainify = (obj, prefix = '', maxDepth = 1000) => {
Давай добавим JSDOC

2024-09-06 17:55 UTC, DPeshkoff commented on source/plain.js
> +  if (typeof prefix !== 'string') {
Буп и все сломалось

<img width="240" alt="Снимок экрана 2024-09-06 в 20 52 34" src="https://github.com/user-attachments/assets/64201863-b02e-4392-b056-e0a4ec3bfdc7">

Давай подумаем, как починить

2024-09-06 17:55 UTC, DPeshkoff commented on source/plain.js
> +    throw new Error('Префикс должен быть строкой');
Предлагаю выбрать более подходящий [тип ошибки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA)

2024-09-06 17:55 UTC, DPeshkoff commented on source/plain.js
> +      if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
и тут сломаем

<img width="495" alt="Снимок экрана 2024-09-06 в 20 54 51" src="https://github.com/user-attachments/assets/ae84381c-0719-403d-848d-e86d0589d36c">

2024-09-06 17:55 UTC, DPeshkoff commented on tests/plainify.js
> +
кажется, отличаются отступы - предлагаю починить

2024-09-10 21:22 UTC, DPeshkoff commented on source/plain.js
> +const plainify = (obj, prefix = '', maxDepth = 1000) => {
не починил

2024-09-10 21:24 UTC, AlexeyBMSTU commented on source/plain.js
> +const plainify = (obj, prefix = '', maxDepth = 1000) => {
JsDoc не добавил?

2024-09-10 21:29 UTC, AlexeyBMSTU commented on source/plain.js
> +const plainify = (obj, prefix = '', maxDepth = 1000) => {
Только что вроде бы добавил

2024-09-12 07:45 UTC, DPeshkoff approved these changes

2024-09-12 07:45 UTC, closed without merging