Ходырев Роман
frontend-park-mail-ru/homework_2024_2 pull request #62
Opened 2024-09-10 11:59 UTC by FireSpirit171

2024-09-12 11:54 UTC, Zela2520 commented
Привет ) Меня зовут Даня.
Буду проверять твоё ДЗ0.

Хорошая работа, но есть замечание )

В название пр-а только Фамилия Имя.

2024-09-12 12:06 UTC, Zela2520 reviewed
Правь замечания и асайнь меня )

2024-09-12 12:06 UTC, Zela2520 commented on source/sort.js
> +        let sortedWord = word.toLowerCase().split('').sort((a, b) => a.localeCompare(b, 'ru')).join('');
В чем разница между let, const, var ? Почитай и рассажи про хостинг в js ?

2024-09-12 12:06 UTC, Zela2520 commented on tests/sort.js
> +		assert.strictEqual(sort('Rrrrrrrr'), 'Rrrrrrrr');
А что будет если кину тип отличающейся от строки ? Есть ли тест кейс и проверка в коде на это ? Например: undefined, null, number и тд. Какие вообще типы данных есть в js ?

Чем null отличается от undefined ? Что возвращает функция по умолчанию ?

2024-09-12 19:00 UTC, FireSpirit171 commented on source/sort.js
> +'use strict';
'use strict' - это директива, которая включает строгий режим в js. Она запрещает использование неинициализированных переменных и не дает создавать глобальные. Конкретно в этом случае код бы сработал, но мог бы содержать скрытые ошибки. Поэтому писать без этой директивы не рекомендуется

2024-09-12 19:00 UTC, FireSpirit171 commented on source/sort.js
> +function sort(sentence) {
Есть декларативное объявление, функциональное и стрелочное. У декларативного объявления (использовано в коде) простой синтаксис и есть возможность вызвать функцию до её объявления. При функциональном объявлении функция кладется в некую константную переменную и чаще всего остается без имени, что позволяет передавать её в другие функции в качестве аргумента, но тут теряется возможность вызвать её до объявления. Стрелочная функция создается, когда нет нужды в контексте this. В данном случае можно было использовать и стрелочную функцию, но в будущем это бы исключило возможность взаимодействия с объектами и контекстом this, а также ухудшило читаемость кода

2024-09-12 19:00 UTC, FireSpirit171 commented on source/sort.js
> +function sort(sentence) {
Добавил

2024-09-12 19:00 UTC, FireSpirit171 commented on source/sort.js
> +        let sortedWord = word.toLowerCase().split('').sort((a, b) => a.localeCompare(b, 'ru')).join('');
var - старый способ объявления переменных. Минус такого объявления в том, что переменная хостится a.k.a. "всплывает" вверх к началу функции или глобальной области видимости. Иногда это чревато ошибками, потому что переменную можно использовать до объявления, хотя её значение будет undefined

на замену ей пришел let - это объявление имеет блочную видимость, не хостится и как следствие при попытке использования переменной до её объявления возникает ошибка

const - то же самое, что let, но переменную нужно инициализировать сразу и изменять её будет уже нельзя

2024-09-12 19:01 UTC, FireSpirit171 commented on tests/sort.js
> +		assert.strictEqual(sort('Rrrrrrrr'), 'Rrrrrrrr');
Есть 7 базовых типов данных: number для любых чисел, bigint - для чисел произвольной длины, string - для строк, boolean - для true/false, null - для неизвестных значений, undefined - для неинициализированных значений и symbol - для  символов. Кроме того есть object - объекты для более сложных структур данных, он не относится к базовым.

null отличается от undefined тем, что первое - это намеренное отсутствие значения, а второе - значит переменная объявлена, но не инициализирована. Кроме того (могу ошибаться) null == undefined, но null !== undefined, потому что в первом случае это специальное правило, а во втором - они просто относятся к разным типам данных

Проверку в коде на другие типы данных я действительно не сделал. Добавил проверку typeof sentence и сделал под него отдельный тест

2024-09-13 07:27 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, накидаю немного вопросиков)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-13 07:27 UTC, DPeshkoff commented on source/sort.js
> +function sort(sentence) {
Давай ради тренировки перепишем на стрелочную)

2024-09-13 07:27 UTC, DPeshkoff commented on tests/sort.js
> +        assert.strictEqual(sort('   привет мир'), '   Веипрт Имр', 'Множественные пробелы с английскими буквами');
отступы

2024-09-13 07:27 UTC, DPeshkoff commented on source/sort.js
> +    if (typeof sentence !== 'string') {
сломаем

<img width="253" alt="Снимок экрана 2024-09-13 в 10 26 55" src="https://github.com/user-attachments/assets/73d5a13e-9bd9-4427-be41-31236b0f3de2">

2024-09-13 07:27 UTC, DPeshkoff commented on source/sort.js
> +        return 'Ошибка: Неверный тип данных';
Лучше выбрасывать [ошибку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error) (там еще разные типы есть, обрати внимание)

2024-09-13 16:21 UTC, FireSpirit171 commented on tests/sort.js
> +        assert.strictEqual(sort('   привет мир'), '   Веипрт Имр', 'Множественные пробелы с английскими буквами');
Исправил описание теста

2024-09-13 16:22 UTC, FireSpirit171 commented on source/sort.js
> +    if (typeof sentence !== 'string') {
действительно, так не проходит) пришлось добавить instanceof String. Добавил соответствующий тест

2024-09-13 16:22 UTC, FireSpirit171 commented on source/sort.js
> +        return 'Ошибка: Неверный тип данных';
Прочитал, выбрасываю TypeError чтобы сразу было понятно, что ошибка вылезла из за неправильного ввода данных

2024-09-16 19:22 UTC, DPeshkoff requested changes

2024-09-16 19:22 UTC, DPeshkoff commented on source/sort.js
> +    if (typeof sentence !== 'string') {
а давай если получим строку-объект - то брать само содержание?

2024-09-16 19:44 UTC, FireSpirit171 commented on source/sort.js
> +    if (typeof sentence !== 'string') {
Исправил. Беру содержимое строки с помощью метода valueOf(). Также добавил тесты на корректную обработку объектов-строк

2024-09-16 21:04 UTC, Sarafa2n commented on source/sort.js
> +    let sortedWords = words.map(word => {
const

2024-09-16 21:05 UTC, Sarafa2n commented on source/sort.js
> +        let sortedWord = word.toLowerCase().split('').sort((a, b) => a.localeCompare(b, 'ru')).join('');
const

2024-09-16 21:06 UTC, Sarafa2n commented on source/sort.js
> +    return sortedWords.join(' ');
а почему выше не сделать return str.split(' ').map().sort().join() ?

2024-09-16 21:14 UTC, FireSpirit171 commented on source/sort.js
> +    let sortedWords = words.map(word => {
Исправил

2024-09-16 21:14 UTC, FireSpirit171 commented on source/sort.js
> +        let sortedWord = word.toLowerCase().split('').sort((a, b) => a.localeCompare(b, 'ru')).join('');
Исправил

2024-09-16 21:14 UTC, FireSpirit171 commented on source/sort.js
> +    return sortedWords.join(' ');
Логические разбиение для повышения читаемости кода

2024-09-17 06:13 UTC, Zela2520 commented on source/sort.js
> +        const sortedWord = word.toLowerCase().split('').sort((a, b) => a.localeCompare(b, 'ru')).join('');
Лишняя переменная, лишняя область в памяти - она тут не нужна.
Для повышения читаемости ты можешь расписать методы по цепочке вот так:
.map
.sort
.join

2024-09-17 06:13 UTC, Zela2520 commented on source/sort.js
> +    if (typeof sentence !== 'string' && !(sentence instanceof String)) {
Господа, а разве одной проверки будет недостаточно. Например: typeof sentence.valueOf() !== 'string'. Мне кажется одной такой проверки достаточно, кейса на котором функция поломается не вижу

2024-09-17 09:46 UTC, Sarafa2n commented on source/sort.js
> +    return sortedWords.join(' ');
сделай return как я выше писал

2024-09-17 11:40 UTC, FireSpirit171 commented on source/sort.js
> +    return sortedWords.join(' ');
Исправил

2024-09-17 11:41 UTC, FireSpirit171 commented on source/sort.js
> +        const sortedWord = word.toLowerCase().split('').sort((a, b) => a.localeCompare(b, 'ru')).join('');
Исправил

2024-09-18 06:07 UTC, Zela2520 reviewed
Все хорошо )

2024-09-18 13:03 UTC, Sarafa2n commented on source/sort.js
> +        .map(word => {
(word)

2024-09-18 13:03 UTC, Sarafa2n commented on source/sort.js
> +            const sortedWord = word.toLowerCase().split('').sort((a, b) => a.localeCompare(b, 'ru')).join('');
давай разобьем на 
word.toLowerCase()
   .split()
   .sort()
   .join()

2024-09-18 13:18 UTC, FireSpirit171 commented on source/sort.js
> +        .map(word => {
Исправил

2024-09-18 13:18 UTC, FireSpirit171 commented on source/sort.js
> +            const sortedWord = word.toLowerCase().split('').sort((a, b) => a.localeCompare(b, 'ru')).join('');
Исправил

2024-09-18 13:35 UTC, Sarafa2n commented on source/sort.js
> +            .join('');
отступ бы

2024-09-18 13:38 UTC, FireSpirit171 commented on source/sort.js
> +            .join('');
Добавил

2024-09-18 13:49 UTC, closed without merging