Кожевникова Алиса. Вариант 7
frontend-park-mail-ru/homework_2024_2 pull request #63
Opened 2024-09-10 14:21 UTC by Alisa-it

2024-09-12 17:48 UTC, Gallaann commented
Привет, меня зовут Вова, поздравляю тебя с переходом на 2-ой семестр. Я буду проверять твое ДЗ№0. Смело можешь обращаться ко мне с любыми вопросами в [ТГ](https://t.me/Gallaaan)

Микромем для поддержания настроения
![image](https://github.com/user-attachments/assets/3f154782-5f3b-4b20-9184-62ee9c1dea46)

2024-09-12 17:56 UTC, Gallaann requested changes
Невероятно лаконично. Но нужно пару комментариев от тебя, а так же давай ты еще приложишь результат тестирования в коммент к ПРу и туда же условие задачи, спасибо!)

2024-09-12 17:56 UTC, Gallaann commented on index.html
>  <script src="tests/plain.js"></script>
Давай сохраним пробел между сорсами и тестами все же

2024-09-12 17:56 UTC, Gallaann commented on source/plain.js
> +const plain = arrays => arrays.flat(Infinity);
Сейчас будет душно:
1.  Добавь директиву use strict, а так же объяснен для чего она нужна
2. Добавь документацию к функции, оформленую как JSDoc
https://precodes.hashnode.dev/jsdoc-the-ultimate-guide-to-documenting-your-javascript-code
3. Объясни, чем стрелочная функция отличается от деклоративного объявления и функционального выражения
4. Чем отличаются `const`, `let` и `var` друг от друга, а так же какие директивы (не) рекомендуется использовать

2024-09-12 17:56 UTC, Gallaann commented on tests/plain.js
> +	});
Круто, что дописала тестов, давай еще попробуем передать на вход массивы с объектами какими-нибудь и с функциями

2024-09-13 20:52 UTC, Alisa-it commented
Добрый вечер! Спасибо за мем :)

### Задание варианта №7 
Напишите функцию `plain`, которая будет принимать на вход массив массивов и создавать из них один общий массив. Массивы могут быть любой вложенности.

### Результаты тестов:
![test](https://github.com/user-attachments/assets/71cd318b-a9b4-4f8c-b4b6-c721d2485bb9)

### Ответы на вопросы

1. Для чего нужна директива `"use strict"`?
`"use strict"` - строгий режим. Вводит в js ряд ограничений, с целью улучшения безопасности кода и помощи в обнаружении ошибок. В этом режиме устраняются недостатки, неоднозначности языка, устаревшие возможности, которые сохраняются в нём из соображений совместимости.

2. Чем стрелочная функция отличается от декларативного объявления и функционального выражения?
_Декларативное объявление_ - самый простой вариант функции. Используется, когда не надо записывать функцию в качестве переменной или передавать в качестве аргумента другой функции. Можно использовать до объявления.
_Функциональное выражение_ - можно записывать как переменную и передавать как аргумент, но нельзя использовать до объявления, т.к. оно анонимное (без имени).
_Стрелочная функция_ - самая компактная функция. У нее отсутствует ключевое слово function, в отличие от предыдущих вариантов и она не используется до объявления.

3. Чем отличаются `const`, `let` и `var` друг от друга, а так же какие директивы (не) рекомендуется использовать?
`var` объявляет переменную глобально или на уровне функции, а `let` и `const` на уровне блока. В случае `let` мы можем менять значение переменной, а в случае `const` — нет.
Рекомендуется использовать: `"use strict"` по причинам, приведенным в пункте 1. Не рекомендуется использовать пользовательские директивы.

2024-09-14 21:24 UTC, Alisa-it commented
Результаты работы тестов с измененной функцией:
![image](https://github.com/user-attachments/assets/d3e07265-3c04-42a2-a1d8-526ef24d3ff6)

2024-09-15 07:40 UTC, Alisa-it commented on source/plain.js
> +const plain = arrays => arrays.flat(Infinity);
### Ответы на вопросы

1. Для чего нужна директива `"use strict"`?
`"use strict"` - строгий режим. Вводит в js ряд ограничений, с целью улучшения безопасности кода и помощи в обнаружении ошибок. В этом режиме устраняются недостатки, неоднозначности языка, устаревшие возможности, которые сохраняются в нём из соображений совместимости.

2. Чем стрелочная функция отличается от декларативного объявления и функционального выражения?
_Декларативное объявление_ - самый простой вариант функции. Используется, когда не надо записывать функцию в качестве переменной или передавать в качестве аргумента другой функции. Можно использовать до объявления.
_Функциональное выражение_ - можно записывать как переменную и передавать как аргумент, но нельзя использовать до объявления, т.к. оно анонимное (без имени).
_Стрелочная функция_ - самая компактная функция. У нее отсутствует ключевое слово function, в отличие от предыдущих вариантов и она не используется до объявления.

3. Чем отличаются `const`, `let` и `var` друг от друга, а так же какие директивы (не) рекомендуется использовать?
`var` объявляет переменную глобально или на уровне функции, а `let` и `const` на уровне блока. В случае `let` мы можем менять значение переменной, а в случае `const` — нет.
Рекомендуется использовать: `"use strict"` по причинам, приведенным в пункте 1. Не рекомендуется использовать пользовательские директивы.

2024-09-15 09:17 UTC, Gallaann commented on source/plain.js
> +const plain = arrays => arrays.flat(Infinity);
Супер, расскажи еще каких ключевых слов нет в стрелочных функциях и на что это влияет и я отстану с этими вопросами)

2024-09-15 09:54 UTC, Gallaann requested changes
Еще немного духоты накинул

2024-09-15 09:54 UTC, Gallaann commented on source/plain.js
> +const plain = arrays => arrays.reduce((arr, i) => Array.isArray(i) ? arr.concat(plain(i)) : arr.concat(i), []);
Перевод строки, пожалуйста
Почем это важно - https://semakin.dev/2020/05/no_newline_at_end_of_file/

2024-09-15 09:54 UTC, Gallaann commented on tests/plain.js
> +		assert.throws(function(){plain([1,2][3])}, 'При вводе нескольких массивов');
Добавь еще тесты на object, например, `{a:1, b:2}`, undefined напрямую (чисто для наглядности), функцию, new String, new Number, new Date

2024-09-15 09:54 UTC, Gallaann commented on source/plain.js
> +
1. Не нужно добавлять перевод строки после JSDoc, после него сразу должна идти функция
2. Наверное, лучше перенести пример использования под `throw` и `return`
3. Кажется, что все же `any[]`

```suggestion
/** Принимает на вход массив массивов любой вложенности и создает из них один общий массив.
 * @param {any[]} arrays Массив массивов
 * @throws {TypeError} Если arrays это не массив
 * @returns {any[]} Объединенный массив
 * 
 * @example
 * const array = [1, [null, [3]], ['четыре']]
 * const joint_array = plain(array)
 * console.log(joint_array); // Вывод: [1, null, 3, 'четыре']
 */
```

2024-09-15 09:54 UTC, Gallaann commented on source/plain.js
> +const plain = arrays => arrays.reduce((arr, i) => Array.isArray(i) ? arr.concat(plain(i)) : arr.concat(i), []);
Кажется, что ошибка будет не очень информативная, мб стоит проверить, что на входе не массив и кидать ошибку, что передали не массив, оставивь это `TypeError`?

plain({a:2, b:3});
plain(plain);
plain(new String(1));
plain('string');
<img width="936" alt="image" src="https://github.com/user-attachments/assets/7a7efa17-a1a1-451d-86c1-503c2206d3fd">

plain(undefined);
<img width="908" alt="image" src="https://github.com/user-attachments/assets/f92fc578-814e-4c46-8696-569bd5d9afdb">

2024-09-15 13:53 UTC, Alisa-it commented on source/plain.js
> +const plain = arrays => arrays.flat(Infinity);
В стрелочных функциях не используется `function`, также можно не использовать `return`, если выполняется одно действие. Нет ключевого слова `this`, поэтому стрелочные функции нельзя использовать как конструкторы.

2024-09-15 14:54 UTC, Alisa-it commented
Результаты теста для измененной функции:
![image](https://github.com/user-attachments/assets/5b37055c-9997-461b-9a1b-99b1ab3db932)

2024-09-15 15:03 UTC, Gallaann approved these changes
LGTM

2024-09-16 15:41 UTC, closed without merging