Громыко Григорий
frontend-park-mail-ru/homework_2024_2 pull request #65
Opened 2024-09-11 19:14 UTC by SLDminor

2024-09-11 19:20 UTC, SergTyapkin commented
Привет! Я ментор по фронтенду 3-го семестра. По всем вопросам, а так же когда исправишь замечания, пиши в телегу https://Tyapkin_S.t.me

2024-09-11 19:27 UTC, SergTyapkin requested changes

2024-09-11 19:27 UTC, SergTyapkin commented on source/solve.js
> +'use strict';
Зачем нужна эта строчка?

2024-09-11 19:27 UTC, SergTyapkin commented on source/solve.js
> +function solve(expression, x) {
Давай используем здесь стрелочную функцию. Кстати, расскажи пожалуйста в ответе, чем они отличаются от классических

2024-09-11 19:27 UTC, SergTyapkin commented on source/solve.js
> +    const result = new Function('return ' + replacedExpression)();
Это не просто смело, это пипец как смело.

Эта часть кода выполняет вообще любой переданный в нее код, а это крайне небезопасно, и можно получить то, что называется unexpected behavior.

В общем это очень странный подход, который не стоит использовать.

Так же на всякий случай напомню, что нельзя использовать функцию `eval`

2024-09-11 19:27 UTC, SergTyapkin commented on source/solve.js
> +    const replacedExpression = expression.replace(/x/g, x);
Можно упростить, используя метод `String.replaceAll`

2024-09-11 19:27 UTC, SergTyapkin commented on source/solve.js
> +}
В конце файла должна быть одна пустая строка

2024-09-11 19:42 UTC, SLDminor commented on source/solve.js
> +'use strict';
Она включает "строгий режим". Он нужен, чтобы предотвратить использование необъявленных переменных, дублирование параметров и работу с недопустимыми значениями.

2024-09-11 19:58 UTC, SLDminor commented on source/solve.js
> +function solve(expression, x) {
Стрелочные функции не имеют собственного this, стрелочные функции нельзя использовать в качестве конструкторов и у стрелочных функции нет объекта arguments.

2024-09-12 01:44 UTC, SergTyapkin commented on source/solve.js
> +'use strict';
В основном - да, без него переменные будут доступны до их объявления. 
Остальное - уже достаточно редкие случаи, но надо помнить, что разница все же существует

2024-09-12 13:42 UTC, SergTyapkin requested changes
Код не работает(
![image](https://github.com/user-attachments/assets/2535647a-d5ed-4235-ab3a-15d5f67ab410)


Корректно выполняются тесты, но только потому, что в них используются односимвольные числа (<10). С многосимвольными не работает.

Ещё в задании требуется дописать недостающие тесты, чтобы обеспечить полное покрытие максимально всех возможных случаев переданных аргументов.

Так что тестов надо добавить очень и очень много

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +  const precedence = { '+': 1, '-': 1, '*': 2 };
А деление?

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +    else if (char === '(') {
Должно быть на той же строчке, что и }

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +    else if (char === ')') {
Тоже

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +  while (operators.length) {
Используй метод `Array.forEach`, он работает быстрее

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +    else if (['+', '-', '*'].includes(char)) {
Массив можно заменить на `Object.values(precedence)`

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +    else if (['+', '-', '*'].includes(char)) {
А ещё лучше взять всю конструкцию и заменить её на 
`if (precedence[char] !== undefined) {`

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +      output.push(char);
Здесь не предусмотрена обработка многосимвольных чисел. На числах < 10 все будет работать, но на 10+ нет

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +      stack.push(parseFloat(char));
Здесь не предусмотрена обработка многосимвольных чисел. На числах < 10 все будет работать, но на 10+ нет

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +    } else if (['+', '-', '*'].includes(char)) {
Тут тоже массив можно не писать, а использовать существующий

2024-09-12 13:42 UTC, SergTyapkin commented on source/solve.js
> +};
А пустая строка в конце файла так и не появилась 
![image](https://github.com/user-attachments/assets/c0dff3d0-d071-4a1b-9fd9-7ca103700826)

2024-09-13 21:40 UTC, SergTyapkin requested changes
Ко всем функциям нужно добавить jsDoc. Посмотри пример в max.js

2024-09-13 21:40 UTC, SergTyapkin commented on tests/solve.js
> +	QUnit.test('solve работает правильно с многосимвольными числами и делением', function (assert) {
Ты же в коде проработал случай, когда выражение начинается с отрицательного числа. А где тест с этим?)

2024-09-13 21:40 UTC, SergTyapkin commented on source/solve.js
> +    } else if (precedence[char] !== undefined) {
Чет меня вчера без попутал. Это так не проверяют. Наличие ключа в объекте можно проверить просто
`if (char in precedence)`

2024-09-13 21:40 UTC, SergTyapkin commented on source/solve.js
>  };
Где пустая строка в конце файла?

2024-09-13 21:40 UTC, SergTyapkin commented on source/solve.js
> +  const replacedExpression = expression.replace(/x/g, x);
Почему вернул replace вместо replaceAll?

2024-09-13 21:40 UTC, SergTyapkin commented on tests/solve.js
>  });
Пустая строка в конце

2024-09-13 21:53 UTC, SLDminor commented on tests/solve.js
> +	QUnit.test('solve работает правильно с многосимвольными числами и делением', function (assert) {
Самый последний тест с отрицательным x

2024-09-15 11:23 UTC, SergTyapkin requested changes

2024-09-15 11:23 UTC, SergTyapkin commented on source/solve.js
> +const infixToPostfix = (expression) => {
Добавить JsDoc

2024-09-15 11:23 UTC, SergTyapkin commented on source/solve.js
> +    if (/\d/.test(char) || (char === '-' && (i === 0 || /[+\-*/(]/.test(expression[i - 1])))) {
Если тебе надо проверить, является ли символ одним из списка других символов, лучше использовать метод `Array.includes()`

2024-09-15 11:23 UTC, SergTyapkin commented on source/solve.js
> +const evaluatePostfix = (expression) => {
Добавить JsDoc

2024-09-15 11:23 UTC, SergTyapkin commented on source/solve.js
> +    if (/^-?\d+(\.\d+)?$/.test(char)) {
А давай будем тестировать, является ли строка числом через `parseFloat` и проверку результата на `NaN`. Да, это работает немного медленнее, но читается намного лучше

2024-09-15 11:23 UTC, SergTyapkin commented on source/solve.js
> +    } else if (precedence[char] !== undefined) {
Почему замечание помечено как resolved, но в коде исправлений нет??

2024-09-15 11:23 UTC, SergTyapkin commented on source/solve.js
> +const solve = (expression, x) => {
Добавить JsDoc

2024-09-15 11:23 UTC, SergTyapkin commented on tests/solve.js
> +	QUnit.test('solve работает правильно с многосимвольными числами и делением', function (assert) {
Где....

2024-09-15 11:23 UTC, SergTyapkin commented on tests/solve.js
> +	});
Постарайся по-максимуму сломать свою функцию и докажи тестами, что она не ломается.

Добавь больше негативных тестов.

Проверь, работает ли функция с выражением без пробелов. А если они где-то есть, где-то нет. А что если вместо пробелов будут `\t`?

Больше тестов

2024-09-17 13:21 UTC, SergTyapkin approved these changes

2024-09-17 13:21 UTC, SergTyapkin commented on source/solve.js
> +  result = result.replaceAll(/--/g, '+');
Флаг регулярного выражения `g` не обязателен при использовании `replaceAll`. Она и так заменяет все вхождения

2024-09-17 13:21 UTC, SergTyapkin commented on source/solve.js
> +  result = result.replaceAll(/--/g, '+');
И почему тут в регулярке написано два минуса, а строкой выше минус и в фигурных скобках его количество?)

Давай везде два минуса оставим

2024-09-17 15:47 UTC, SergTyapkin approved these changes

2024-09-18 13:04 UTC, Sarafa2n commented on source/max.js
> +
пустая строка нужна

2024-09-18 13:05 UTC, Sarafa2n commented on source/solve.js
> +  const precedence = { '+': 1, '-': 1, '*': 2, '/': 2 };
константа тут просится

2024-09-18 18:34 UTC, SergTyapkin requested changes

2024-09-18 18:34 UTC, SergTyapkin commented on source/solve.js
> +        while (operators.length && operators[operators.length - 1] !== '(') {
Array.at

2024-09-18 18:34 UTC, SergTyapkin commented on source/solve.js
> +        while (operators.length && operators[operators.length - 1] !== '(') {
В других местах тоже

2024-09-18 18:34 UTC, SergTyapkin commented on source/solve.js
> +  const replacedExpression1 = expression.replaceAll('x', x);
Зачем нам тут 4 переменных отдельных

2024-09-21 16:47 UTC, SergTyapkin requested changes

2024-09-21 16:47 UTC, SergTyapkin commented on source/solve.js
> +    if (char === '-' && (i === 0 || MATHS.includes(expression[i - 1]))) {
Давай если находим минус, то без лишних проверок просто будем домножать numbersBuffer на -1. А в список операторов независимо от этого будем добавлять +, а не -. Тогда нам ещё и не нужна будет функция replaceDoubleMinus вообще

2024-09-21 16:47 UTC, SergTyapkin commented on source/solve.js
> +        while (operators.length && operators.at(-1) !== '(') {
Тоооочно никак нельзя заменить  через reverse + concat?

2024-09-21 16:47 UTC, SergTyapkin commented on source/solve.js
> +        while (operators.length && operators.at(-1) !== '(') {
Ну или там findIndex('(') + slice + reverse + concat. Короче точно есть более JS-ный путь

2024-09-21 16:47 UTC, SergTyapkin commented on source/solve.js
> +          while (operators.length && PRECEDENCE[operators.at(-1)] >= PRECEDENCE[char]) {
Будто бы тоже можно поменять на методы массива

2024-09-21 16:47 UTC, SergTyapkin commented on source/solve.js
> +  if (numberBuffer != null) {
Строгое сравнение

2024-09-21 16:47 UTC, SergTyapkin commented on source/solve.js
> +    if (numberBuffer != null) {
Строгое сравнение

2024-09-21 16:47 UTC, SergTyapkin commented on source/solve.js
> +  evaluatePostfix(
Блин, я когда говорил про функции через точку, я забыл, что мы не с объектами работаем, а с простыми типами. Сможем назад к переменным вернуть? Сейчас наоборот хуже стало, потому что вложенность большая стала, нам такого не надо. Снизу вверх читать приходится

2024-09-23 23:34 UTC, SergTyapkin commented on source/solve.js
> +  expression.split('').reduce((acc, char, i) => {
А ещё можно просто поменять на forEach, если прям совсем тяжко и смысла от reduce нет

2024-09-23 23:34 UTC, SergTyapkin commented on source/solve.js
> +      numberBuffer = numberBuffer !== null ? numberBuffer * 10 + parseInt(char) : parseInt(char);
Возвращаем в строки. Эта проверка - это ужас

2024-09-23 23:35 UTC, SergTyapkin commented on source/solve.js
> +      numberBuffer = numberBuffer !== null ? numberBuffer * 10 + parseInt(char) : parseInt(char);
+

2024-09-23 23:35 UTC, SergTyapkin commented on source/solve.js
> +  expression.split('').reduce((acc, char, i) => {
+

2024-09-23 23:35 UTC, SergTyapkin commented on source/solve.js
> +const MATHS = ['+', '-', '*', '/', '(', ')'];
+

2024-09-23 23:35 UTC, SergTyapkin commented on source/solve.js
>  const PRECEDENCE = { '+': 1, '-': 1, '*': 2, '/': 2 };
+

2024-09-23 23:35 UTC, SergTyapkin commented on source/solve.js
> +        output.push(...operators.splice(openBracketIndex + 1).reverse());
+

2024-09-23 23:36 UTC, SergTyapkin commented on source/solve.js
>          break;
В целом оно не обязательно после default;

2024-09-23 23:36 UTC, SergTyapkin commented on source/solve.js
>          break;
+

2024-09-23 23:37 UTC, SergTyapkin commented on source/solve.js
> +          operators.filter(op => PRECEDENCE[op] >= PRECEDENCE[char]).forEach(op => output.push(operators.pop()));
Меняем на ту же конструкцию, которая была выше. С поиском индекса. Тут вообще неправильная логика. Тебе надо из стека вытаскивать все операторы С КОНЦА до первого более приоритетного. А ты вытаскиваешь вообще ВСЕ БОЛЕЕ ПРИОРИТЕТНЫЕ

2024-09-23 23:37 UTC, SergTyapkin commented on source/solve.js
> +          operators.filter(op => PRECEDENCE[op] >= PRECEDENCE[char]).forEach(op => output.push(operators.pop()));
+

2024-09-23 23:38 UTC, SergTyapkin commented on source/solve.js
> +  if (numberBuffer !== null) {
В целом можно так, а можно закостылить и перед циклом прибавить к выражению пробел. Давай оставим лучше так, как есть

2024-09-23 23:39 UTC, SergTyapkin commented on source/solve.js
>          if (char in PRECEDENCE) {
Нужно сделать `break` и вывести warn'ом этот "неправильный" символ в обратном случае - уменьшаем вложенность

2024-09-23 23:39 UTC, SergTyapkin commented on source/solve.js
>          if (char in PRECEDENCE) {
+

2024-09-23 23:41 UTC, SergTyapkin commented on source/solve.js
>    return output.join(' ');
Давай не будем каждый раз джоинить это в строку и потом резать обратно. Пусть возвращает массив

2024-09-23 23:41 UTC, SergTyapkin commented on source/solve.js
>    return output.join(' ');
+

2024-09-24 00:40 UTC, SergTyapkin requested changes

2024-09-24 00:40 UTC, SergTyapkin commented on source/solve.js
> +        } else {
Не else, а break строкой выше, и избавляемся от else - всегда уменьшай вложенность, где это возможно

2024-09-24 01:12 UTC, SergTyapkin approved these changes

2024-09-25 14:41 UTC, closed without merging