Ашуров Георгий
frontend-park-mail-ru/homework_2024_2 pull request #8
Opened 2024-08-30 19:52 UTC by AshurovG

2024-08-30 20:37 UTC, Nikita-hub000 commented
Привет! Меня зовут Никита. Поздравляю с переходом на 2 семестр и желаю успехов в учебе:)
Я буду твоим проверяющим ДЗ№0. Если возникнут вопросы, не стесняйся обращаться)

1. Отсутствует пустая строка в конце файлов .js

2024-08-30 20:52 UTC, Nikita-hub000 commented on source/euclid.js
> +}
Пустая строка нужна в конце файла)
Вообще это можно настроить в eslint и не мучаться проставляя руками
https://eslint.org/docs/latest/rules/eol-last

2024-08-30 20:52 UTC, Nikita-hub000 commented on tests/euclid.js
>  });
Пустая строка нужна в конце файла)
Вообще это можно настроить в eslint и не мучаться проставляя руками
https://eslint.org/docs/latest/rules/eol-last

2024-08-31 08:35 UTC, AshurovG commented on source/euclid.js
> +"use strict";
Нужен для выполнения JS кода в строгом режиме. Т.е. позволяет обнаружить ошибки на этапе компиляции а не во время выполнения кода. Например, когда мы присваиваем переменной какое-то значение, если до этого переменная не была инициализирована, то 'use strict' выведет ошибку

2024-08-31 08:41 UTC, AshurovG commented on source/euclid.js
> +  return Math.abs(arr.reduce((res, num) => gcd(res, num), 0));
Потому что reduce берет в качестве аккумулятора берет первый элемент массива

2024-08-31 09:20 UTC, AshurovG commented on source/euclid.js
> +function euclid(...arr) {
По п.1 Так как я использую spread, в любом случае будет передан массив, если просто указать euclid('dfdf') или euclid(new Map()) это все будут элементы массива arr. 
Поэтому проверка на массив как будто не нужна
По п.2 добавил проверку по элемента, если встречаю хоть один элемент не числовой - выбрасываю ошибку

2024-08-31 09:21 UTC, AshurovG commented on tests/euclid.js
> +  });
Аналогично, п.1 на входе всегда массив, п.2 тесты для элементов массива добавил

2024-08-31 09:22 UTC, AshurovG commented on source/euclid.js
> +}
Вот здесь не понял почему так получилось, потому что у меня стоит prettier и локально все пустые строки расставлены :)
<img width="543" alt="image" src="https://github.com/user-attachments/assets/882891ba-3c71-4a24-be2c-27d0c9764145">

2024-08-31 09:22 UTC, AshurovG commented on tests/euclid.js
>  });
Аналогично предыдущему замечанию

2024-08-31 10:01 UTC, Nikita-hub000 commented on source/euclid.js
> +function euclid(...arr) {
По п.1 а если прилетит Euclid(null) или Euclid(undefined) ?:)

2024-08-31 10:16 UTC, Nikita-hub000 commented on source/euclid.js
> +}
Попробуй глянуть
1) ESLINT (или что то другое) может в теории переопределять твой prettier при пуше
2) Чекни локальные и глобальные настройки prettier. Они могут быть разными
3) Если у тебя стоит какой нибудь husky, глянь еще его

2024-08-31 11:35 UTC, AshurovG commented on source/euclid.js
> +function euclid(...arr) {
Они также буду как элементы массива и прилетит ошибка о том, что должны быть только числа

2024-08-31 12:16 UTC, AshurovG commented on source/euclid.js
> +}
Честно говоря, так и не понял в чем проблема. Даже попробовал с другого устройства склонировать, при клоне в среде разработки сразу эти пустые строки появлсяются, а в github нет никаких пустых строк (причем в оригинале репозитория домашнего задания также пустые строки не отображаются)

2024-09-01 10:32 UTC, Nikita-hub000 commented on source/euclid.js
> +function euclid(...arr) {
Да, все верно

2024-09-01 13:50 UTC, Nikita-hub000 commented on source/euclid.js
> +}
Хм,так очень сложно сказать в таком случае. Т.К. не вижу твоего компа:) 
Давай я тебя переведу дальше, т.к. задание по сути выполнено, но уточни этот вопрос у Дмитрия Пешкова еще. ( смотри его в assigners)

2024-09-06 18:00 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-06 18:00 UTC, DPeshkoff commented on source/euclid.js
> +  if (!arr.every(Number.isFinite)) {
А чем Number.isFinite отличается от isFinite? Почему использовал именно это?

Кстати, оба метода нужно вызывать)

2024-09-06 21:00 UTC, AshurovG commented on index.html
> +    <title>Домашнее задание: вариант №2</title>
Тут мой форматтер так отформатрировал при сохранении) поправлю тогда как было

2024-09-07 10:49 UTC, AshurovG commented on source/euclid.js
> +  if (!arr.every(Number.isFinite)) {
Number.isFinite метод объекта Number. Ключевое отличие от isFinite в том, что isFinite преобразует переданный аргумент в число, если это возможно, а Number.isFinite - проверяет на конечное число.
Примеры:
Number.isFinite('12') // false
isFinite('12') // true -  преобразует в число 12
isFinite(false) // true преобразует в 0
isFinite("hello world") // false
Т.е. Number.isFinite() - более надежный

Поправил в коде с вызовом через Number.isFinite(el)

2024-09-07 10:52 UTC, AshurovG commented on source/euclid.js
> +  if (arr.length === 1) return arr[0];
Оказалось, что проверка здесь вовсе не нужна)
Так как даже если передали одно число, то оно гарантировано вернется функцией euclid благодаря реализации gcd() - которая возвращает само число, в случае, если всего один элемент массива

Поэтому я удалил эту бессмысленную проверку

2024-09-07 11:04 UTC, AshurovG commented on source/euclid.js
> +function euclid(...arr) {
Я видимо забыл поправить на стрелочную.
Стрелочную функцию мы присваиваем в переменную, благодаря этому она не всплывает при запуске программы.
Когда мы объявляем функцию через ключевое слово function, то при запуске произойдет хоистинг (всплытие) все fuction declaration всплывут и мы их можем использовать до определения, в отличие от expression

Из других отличий стрелочных функций от обычных:
У стрелочных нет своего this (они берут его о родительского элемента), в отличие от функций, объявленных через function;
Обычные функции можно вызывать через оператор new;
Также стрелочные функции не имеют ссылке на объект arguments

У стрелочной функции "ожидаемое" поведение, поэтому по возможности лучше использовать ее

2024-09-10 21:16 UTC, DPeshkoff approved these changes

2024-09-10 21:16 UTC, closed without merging