Койбаев Тамерлан
frontend-park-mail-ru/homework_2024_2 pull request #9
Opened 2024-08-30 21:27 UTC by tkoibaev

Напишите функцию letters, которая будет удалять из строки символы, которые встречаются в ней больше одного раза. Если вторым аргументом передано true, то функция будет искать повторяющиеся символы в строках и удалять их, оставляя на месте только первую встречающуюся букву. Если вторым аргументом передано false, то функция будет оставлять только последнюю встречающуюся букву

2024-08-31 10:20 UTC, Shureks-den commented
Привет! Поздравляю с поступление на курс по фронтенд разработки, меня зовут Саша, и я буду проверять твое дз. По всем вопросом можешь писать в телегу t.me/aklonov

2024-08-31 10:21 UTC, Shureks-den commented
Допиши номер варианта в название пр плз

2024-08-31 10:45 UTC, Shureks-den requested changes

2024-08-31 10:45 UTC, Shureks-den commented on descs.js
> -];
Не думаю, что надо удалять эти файлы, их можно просто не подключать, а pr это нормально так раздуло) 
![image](https://github.com/user-attachments/assets/481252de-c88e-4d99-9e3e-e15596d5525d)

2024-08-31 10:45 UTC, Shureks-den commented on index.html
> +    <script src="tests/max.js"></script>
Не нужно подключать лишний тест

2024-08-31 10:45 UTC, Shureks-den commented on index.html
>  </html>
Также добавь результаты прохождения тестов в описание к пр

2024-08-31 10:45 UTC, Shureks-den commented on source/letters.js
> +const letters = (str, saveFirst) => {
Первый вопросик: ты объявил функцию таким образом, можно было ли создать функцию как-то по-другому? (спойлер можно) и в чем разница между различными объявлениями функций

2024-08-31 10:45 UTC, Shureks-den commented on source/letters.js
> +const letters = (str, saveFirst) => {
В текущем мире продуктового js, typescript является неотъемлемой частью, потому что типы наше все, давай сделаем вид, что нам нужно подумать о других и опишем эту функцию с помощью JSDoc

2024-08-31 10:45 UTC, Shureks-den commented on source/letters.js
> +    throw new TypeError("Первый аргумент должен быть строкой")
Расскажи, что тут делаешь и для чего

2024-08-31 10:45 UTC, Shureks-den commented on source/letters.js
> +  let resultArray = charArray.filter((item, index) => {
Какие способы объявления переменных ты знаешь? После того как расскажешь, подумай, можно ли тут использовать другие, если да, то почему, если нет, то тоже почему

2024-08-31 10:45 UTC, Shureks-den commented on source/letters.js
> +  let resultArray = charArray.filter((item, index) => {
Здесь метод `Array.filter` принимает функцию и ты используешь стрелочную, это круто! Расскажи в чем разница между стрелочными функциями, и функциями заданными через `function `например

2024-08-31 10:45 UTC, Shureks-den commented on source/letters.js
> +    }
Мы можем заюзать тут тернарный оператор, он тут идеально подходит

2024-08-31 10:45 UTC, Shureks-den commented on source/letters.js
> +  let resultArray = charArray.filter((item, index) => {
Можно сразу вызвать тут filter на `str.split`, не зачем создавать переменную в памяти, если мы используем один раз только

2024-08-31 10:45 UTC, Shureks-den commented on source/letters.js
> +  return resultArray.join("")
Аналогично тут, тоже создал переменную, только чтобы потом ее просто вернуть

2024-08-31 10:45 UTC, Shureks-den commented on tests/letters.js
> +"use strict"
Расскажи для чего это тут?

2024-08-31 10:45 UTC, Shureks-den commented on tests/letters.js
> +  QUnit.test(
Давай добавим отступ и ; проставим

2024-08-31 10:45 UTC, Shureks-den commented on tests/letters.js
> +  )
Круто, что подумал о негативных тест-кейсах, но давай поправим отступы по аналогии с примерами выше, как то сложно читать

2024-08-31 10:45 UTC, Shureks-den commented on tests/letters.js
> +})
Тут тоже

2024-08-31 10:45 UTC, Shureks-den commented on tests/letters.js
> +})
И давай добавим еще какой-нибудь положительный кейс, которого не было в тестах, например большая строка, где есть символы переноса '\n' и различные utf-8 символы

2024-08-31 12:36 UTC, tkoibaev commented on source/letters.js
> +const letters = (str, saveFirst) => {
Да, можно было использовать FunctionDeclaration 
function letters(){
} 
или FunctionExpression 
const letters = function(){
}.  
Для функций объявленных через FunctionDeclaration работает поднятие, т.е. вызов до их объявления, для стрелочный и FE нет. Но стрелочные функции наиболее удобные в использовании и в понимании кода.

2024-08-31 12:37 UTC, tkoibaev commented on source/letters.js
> +    throw new TypeError("Первый аргумент должен быть строкой")
Обрабатываю случай некорректного типа для обязательного аргумента. 
В случае, если передана не строка, выбрасываю TypeError.

2024-08-31 12:42 UTC, tkoibaev commented on source/letters.js
> +  let resultArray = charArray.filter((item, index) => {
Помимо let можно объявлять переменную через const и var(нежелательно).
Можно было использовать const в обоих случаях, поскольку мы не присваиваем этим переменным новые значения.

2024-08-31 12:53 UTC, tkoibaev commented on index.html
>  </html>
А как это можно сделать?

2024-08-31 13:07 UTC, tkoibaev commented on source/letters.js
> +  let resultArray = charArray.filter((item, index) => {
Но мы же еще используем CharArray внутри filter, когда проверяем уникальность символа.

2024-08-31 13:49 UTC, tkoibaev commented on tests/letters.js
> +"use strict"
При помощи "use strict" мы включаем строгий режим, который будет выдавать исключения на те ошибки, которые в грязном режиме были просто опущены.

2024-08-31 16:19 UTC, Shureks-den commented on index.html
>  </html>
Просто скрин можно в комменты скинуть

2024-08-31 16:22 UTC, Shureks-den commented on source/letters.js
> +  let resultArray = charArray.filter((item, index) => {
Действительно, сори

2024-08-31 16:23 UTC, Shureks-den commented on source/letters.js
> +    throw new TypeError("Второй аргумент должен быть булевым значением")
Давай не будем забывать про точки с запятыми после строк, иначе это может привести к очень странным багам парсера, которые потом очень сложно отследить

2024-08-31 16:24 UTC, Shureks-den commented on source/letters.js
> +    throw new TypeError("Второй аргумент должен быть булевым значением")
Поправь везде плз и апрувну

2024-08-31 16:25 UTC, Shureks-den commented on source/letters.js
> +      if (saveFirst === undefined) {
И последний вопросик, почему используешь тут `===`, можем ли тут использовать `==`?

2024-08-31 16:26 UTC, Shureks-den commented
![image](https://github.com/user-attachments/assets/bb2303a8-2a77-4692-bc44-18033b877b40)
И порешай конфликты еще

2024-08-31 20:52 UTC, tkoibaev commented on index.html
>  </html>
![image](https://github.com/user-attachments/assets/d09e89de-c45c-4882-b373-6b80751ab8f9)

2024-08-31 21:08 UTC, tkoibaev commented on source/letters.js
> +      if (saveFirst === undefined) {
Вообще можем, у нас выше проброс ошибки на !==undefined. 
Но если бы той проверки выше не было, то при передаче null в качестве второго аргумента получили случай, когда оставляем последний из дубликатов (я думаю непредвиденно)

2024-09-01 09:51 UTC, Shureks-den commented on README.md
> +>>>>>>> variant-10
Маркеры конфликта остались

2024-09-01 09:54 UTC, Shureks-den commented on source/letters.js
> +      if (saveFirst === undefined) {
Действительно, оператор == почти не используется, потому что он дает непредсказуемые результаты при касте типов

2024-09-01 12:44 UTC, Shureks-den approved these changes

2024-09-06 20:05 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть немного вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2024-09-06 20:05 UTC, DPeshkoff commented on README.md
> +
Здесь не нужны изменения - давай сделаем так, чтобы они тут не высвечивались)

2024-09-06 20:05 UTC, DPeshkoff commented on index.html
И тут тоже, кстати

2024-09-06 20:05 UTC, DPeshkoff commented on source/letters.js
> +/**
А в каком режиме работает твой код? Какие знаешь и чем они отличаются?

2024-09-06 20:05 UTC, DPeshkoff commented on source/letters.js
> +  if (typeof str !== "string") {
Буп и все сломалось

<img width="240" alt="Снимок экрана 2024-09-06 в 20 52 34" src="https://github.com/user-attachments/assets/64201863-b02e-4392-b056-e0a4ec3bfdc7">

Давай подумаем, как починить

2024-09-06 20:05 UTC, DPeshkoff commented on source/letters.js
> +    throw new TypeError("Первый аргумент должен быть строкой");
Лайк за TypeError, но давай поменяем на одиночные кавычки

2024-09-06 20:05 UTC, DPeshkoff commented on source/letters.js
> +const letters = (str, saveFirst) => {
Анрезолвлю, потому что есть вопрос - а какие еще отличия стрелочных функций от обычных?

2024-09-06 20:05 UTC, DPeshkoff commented on source/letters.js
> +  if (typeof saveFirst !== "boolean" && saveFirst !== undefined) {
Здесь можно [упростить](https://developer.mozilla.org/ru/docs/Glossary/Falsy)

2024-09-06 20:05 UTC, DPeshkoff commented on source/letters.js
> +      if (saveFirst === undefined) {
А так ли нам здесь нужно проверять, что оно именно undefined?  А если будет null?

2024-09-06 20:05 UTC, DPeshkoff commented on tests/letters.js
> +    function (assert) {
Кто-то (подозреваю, это был неправильный diff) украл изначальные тесты, предлагаю это вернуть)

2024-09-06 20:05 UTC, DPeshkoff commented on tests/letters.js
> +  // prettier-ignore
А что игнорируем?

2024-09-07 16:26 UTC, tkoibaev commented on tests/letters.js
> +  // prettier-ignore
Prettier применяет вот такое форматирование к этой функции
![image](https://github.com/user-attachments/assets/790d0e15-0042-46da-a6bb-6aac6ea5c5c1)

2024-09-07 16:31 UTC, tkoibaev commented on source/letters.js
> +const letters = (str, saveFirst) => {
Стрелочные - не имеют своего this и берут this у родительского элемента. А у обычных есть свой this.
Также стрелочные функции не имеют ссылки на arguments объект.

2024-09-07 17:23 UTC, tkoibaev commented on source/letters.js
> +/**
Код работает в нестрогом режиме, который используется в JS по умолчанию. Также существует строгий режим, который имеет более строгие правила написания кода, ругается на ошибки, который в нестрогом режиме были бы игнорированы. Например - дублирование параметров функции.

2024-09-11 20:50 UTC, DPeshkoff commented on index.html
давай уберем отсюда изменения кодстайла(

2024-09-12 07:47 UTC, DPeshkoff approved these changes

2024-09-12 07:48 UTC, closed without merging